// ========== DATABASE BUSHU UNTUK 138 KANJI PERTEMUAN 6 - 11 ==========

const bushuData = {
  // --- PERTEMUAN 6 ---
  "句": { radical: "勹", name: "Tsutsumigamae", meaning: "Membungkus / Merangkul" },
  "等": { radical: "⺮", name: "Takekanmuri", meaning: "Bambu" },
  "難": { radical: "隹", name: "Fuyutori", meaning: "Burung ekor pendek" },
  "将": { radical: "寸", name: "Sun", meaning: "Ukuran / Inci / Jempol" },
  "记": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" }, // Note: we have 記 in standard Japanese
  "記": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "功": { radical: "力", name: "Chikara", meaning: "Kekuatan / Tenaga" },
  "誌": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "夢": { radical: "夕", name: "Yuu", meaning: "Sore / Malam / Gelap" },
  "静": { radical: "青", name: "Ao", meaning: "Biru / Hijau" },
  "閉": { radical: "門", name: "Mon", meaning: "Gerbang / Pintu" },
  "想": { radical: "心", name: "Kokoro", meaning: "Hati / Pikiran" },
  "現": { radical: "王", name: "Oushin", meaning: "Raja / Permata / Batu Mulia" },
  "在": { radical: "土", name: "Tsuchi", meaning: "Tanah / Bumi" },
  "解": { radical: "角", name: "Tsuno", meaning: "Tanduk / Sudut" },
  "決": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "怖": { radical: "忄", name: "Risshinben", meaning: "Hati / Perasaan" },
  "雷": { radical: "雨", name: "Amegamuri", meaning: "Hujan / Langit" },
  "笑": { radical: "⺮", name: "Takekanmuri", meaning: "Bambu" },
  "甘": { radical: "甘", name: "Kan", meaning: "Manis / Kenikmatan" },
  "丸": { radical: "丶", name: "Ten", meaning: "Titik / Tetesan" },
  "当": { radical: "小", name: "Shou", meaning: "Kecil" },
  "信": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "震": { radical: "雨", name: "Amegamuri", meaning: "Hujan / Langit" },

  // --- PERTEMUAN 7 ---
  "助": { radical: "力", name: "Chikara", meaning: "Kekuatan / Tenaga" },
  "次": { radical: "欠", name: "Ketsu / Akabi", meaning: "Menguap / Kurang / Menginginkan" },
  "消": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "濃": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "際": { radical: "阝", name: "Kozatohen", meaning: "Dinding / Bukit / Batas" },
  "紹": { radical: "糸", name: "Itohen", meaning: "Benang / Serat" },
  "輝": { radical: "光", name: "Hikari", meaning: "Cahaya / Sinar" },
  "浮": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "並": { radical: "一", name: "Ichi", meaning: "Satu / Garis Horizontal" },
  "雲": { radical: "雨", name: "Amegamuri", meaning: "Hujan / Langit" },
  "与": { radical: "一", name: "Ichi", meaning: "Satu / Garis Horizontal" },
  "髪": { radical: "髟", name: "Kamigashira", meaning: "Rambut panjang" },
  "伸": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "共": { radical: "八", name: "Hachi", meaning: "Delapan / Menopang" },
  "済": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "技": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "術": { radical: "行", name: "Gyou", meaning: "Berjalan / Melakukan" },
  "展": { radical: "尸", name: "Shikabane", meaning: "Tubuh manusia / Bendera" },
  "関": { radical: "門", name: "Mon", meaning: "Gerbang / Pintu" },
  "様": { radical: "木", name: "Kihen", meaning: "Pohon / Kayu" },
  "影": { radical: "彡", name: "Sanzukuri", meaning: "Bulu / Sisir / Pola Hias" },
  "響": { radical: "音", name: "Oto", meaning: "Suara / Bunyi" },
  "演": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },

  // --- PERTEMUAN 8 ---
  "奏": { radical: "大", name: "Dai", meaning: "Besar" },
  "録": { radical: "金", name: "Kanehen", meaning: "Logam / Emas / Uang" },
  "喜": { radical: "口", name: "Kuchi", meaning: "Mulut" },
  "喫": { radical: "口", name: "Kuchi", meaning: "Mulut" },
  "誕": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "许": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "許": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "負": { radical: "貝", name: "Kai", meaning: "Kerang / Harta / Nilai" },
  "倒": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "域": { radical: "土", name: "Tsuchihen", meaning: "Tanah / Bumi" },
  "娯": { radical: "女", name: "Onnahen", meaning: "Wanita / Perempuan" },
  "仲": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "憶": { radical: "小", name: "Risshinben", meaning: "Hati / Perasaan" }, // Note: 憶 has 忄
  "型": { radical: "土", name: "Tsuchi", meaning: "Tanah / Bumi" },
  "財": { radical: "貝", name: "Kaihen", meaning: "Kerang / Harta / Nilai" },
  "酒": { radical: "酉", name: "Hiyominotori / Sake", meaning: "Botol sake / Alkohol / Zat cair" },
  "交": { radical: "亠", name: "Nabebuta", meaning: "Penutup / Kepala" },
  "故": { radical: "攵", name: "Bokunyou", meaning: "Memukul / Mengetuk / Aksi" },
  "飛": { radical: "飛", name: "Tobu", meaning: "Terbang" },
  "庭": { radical: "广", name: "Madare", meaning: "Bangunan / Atap Rumah terbuka" },
  "患": { radical: "心", name: "Kokoro", meaning: "Hati / Pikiran" },
  "活": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "果": { radical: "木", name: "Ki", meaning: "Pohon / Kayu" },
  "奇": { radical: "大", name: "Dai", meaning: "Besar" },

  // --- PERTEMUAN 9 ---
  "番": { radical: "田", name: "Ta", meaning: "Sawah / Ladang" },
  "号": { radical: "口", name: "Kuchi", meaning: "Mulut" },
  "準": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "備": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "偶": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "深": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "指": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "認": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "操": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "聖": { radical: "耳", name: "Mimi", meaning: "Telinga" },
  "君": { radical: "口", name: "Kuchi", meaning: "Mulut" },
  "困": { radical: "囗", name: "Kunigamae", meaning: "Kotak pembatas / Wilayah negara" },
  "郷": { radical: "⻏", name: "Oozato", meaning: "Kota / Kampung Halaman / Wilayah" },
  "黄": { radical: "黄", name: "Ki", meaning: "Kuning" },
  "伝": { radical: "亻", name: "Ninben", meaning: "Manusia / Orang" },
  "掌": { radical: "手", name: "Te", meaning: "Tangan" },
  "造": { radical: "⻌", name: "Shinnyou", meaning: "Melangkah / Berjalan / Pergerakan" },
  "遺": { radical: "⻌", name: "Shinnyou", meaning: "Melangkah / Berjalan / Pergerakan" },
  "形": { radical: "彡", name: "Sanzukuri", meaning: "Bulu / Sisir / Pola Hias" },
  "根": { radical: "木", name: "Kihen", meaning: "Pohon / Kayu" },
  "完": { radical: "宀", name: "Ukanmuri", meaning: "Atap Rumah / Bangunan" },
  "雪": { radical: "雨", name: "Amegamuri", meaning: "Hujan / Langit" },
  "壊": { radical: "土", name: "Tsuchihen", meaning: "Tanah / Bumi" },

  // --- PERTEMUAN 10 ---
  "修": { radical: "人", name: "Ninben / Hito", meaning: "Manusia / Orang" },
  "費": { radical: "貝", name: "Kai", meaning: "Kerang / Harta / Nilai" },
  "陽": { radical: "阝", name: "Kozatohen", meaning: "Dinding / Bukit / Batas" },
  "抵": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "抗": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "凉": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "涼": { radical: "氵", name: "Sanzui", meaning: "Air / Sungai" },
  "暖": { radical: "日", name: "Hihen", meaning: "Matahari / Hari / Waktu" },
  "層": { radical: "尸", name: "Shikabane", meaning: "Tubuh manusia / Bendera" },
  "階": { radical: "阝", name: "Kozatohen", meaning: "Dinding / Bukit / Batas" },
  "蚕": { radical: "虫", name: "Mushi", meaning: "Serangga / Cacing / Ulat" },
  "飼": { radical: "飠", name: "Shokuben", meaning: "Makanan / Makan / Nutrisi" },
  "製": { radical: "衣", name: "Koromo", meaning: "Pakaian / Baju" },
  "辺": { radical: "⻌", name: "Shinnyou", meaning: "Melangkah / Berjalan / Pergerakan" },
  "農": { radical: "辰", name: "Tatsu", meaning: "Naga / Bintang / Waktu Bercocok Tanam" },
  "内": { radical: "冂", name: "Keigamae", meaning: "Batas terjauh / Bingkai" },
  "条": { radical: "木", name: "Ki", meaning: "Pohon / Kayu" },
  "貢": { radical: "貝", name: "Kai", meaning: "Kerang / Harta / Nilai" },
  "期": { radical: "月", name: "Tsuki", meaning: "Bulan / Waktu" },
  "城": { radical: "土", name: "Tsuchihen", meaning: "Tanah / Bumi / Kastil" },
  "掘": { radical: "扌", name: "Tehen", meaning: "Tangan / Tindakan" },
  "豊": { radical: "豆", name: "Mame", meaning: "Kacang / Kemakmuran" },
  "権": { radical: "木", name: "Kihen", meaning: "Pohon / Kayu" },
  "植": { radical: "木", name: "Kihen", meaning: "Pohon / Kayu" },

  // --- PERTEMUAN 11 ---
  "軒": { radical: "車", name: "Kurumahen", meaning: "Kendaraan / Mobil / Kereta" },
  "管": { radical: "⺮", name: "Takekanmuri", meaning: "Bambu" },
  "価": { radical: "人", name: "Ninben", meaning: "Manusia / Orang" },
  "値": { radical: "人", name: "Ninben", meaning: "Manusia / Orang" },
  "兆": { radical: "儿", name: "Ninyou / Kaki", meaning: "Kaki manusia / Manusia berjalan" },
  "談": { radical: "言", name: "Gonben", meaning: "Kata-kata / Bicara" },
  "暮": { radical: "日", name: "Hi", meaning: "Matahari / Hari / Waktu" },
  "司": { radical: "口", name: "Kuchi", meaning: "Mulut" },
  "奥": { radical: "大", name: "Dai", meaning: "Besar" },
  "労": { radical: "力", name: "Chikara", meaning: "Kekuatan / Tenaga" },
  "略": { radical: "田", name: "Tahen", meaning: "Sawah / Ladang" },
  "騒": { radical: "馬", name: "Umahen", meaning: "Kuda" },
  "街": { radical: "行", name: "Gyou", meaning: "Berjalan / Melakukan / Jalan raya" },
  "受": { radical: "爪", name: "Tsume", meaning: "Cakar / Kuku / Mengambil" },
  "踏": { radical: "足", name: "Ashiben", meaning: "Kaki / Melangkah" },
  "販": { radical: "貝", name: "Kaihen", meaning: "Kerang / Harta / Nilai" },
  "虫": { radical: "虫", name: "Mushi", meaning: "Serangga" },
  "窓": { radical: "穴", name: "Anakanmuri", meaning: "Lubang / Gua" },
  "加": { radical: "力", name: "Chikara", meaning: "Kekuatan / Tenaga" },
  "鉄": { radical: "金", name: "Kanehen", meaning: "Logam / Emas / Uang" },
  "配": { radical: "酉", name: "Hiyominotori / Sake", meaning: "Botol sake / Alkohol / Zat cair" },
  "慮": { radical: "虍", name: "Toragashira", meaning: "Harimau / Kulit harimau" },
  "含": { radical: "口", name: "Kuchi", meaning: "Mulut" }
};
