
// ========== PERTEMUAN 9 ==========
const pertemuan9 = {
  id: 9, title: "Pertemuan 9",
  kanji: [
    { kanji:"番", meaning_core:["nomor urut","giliran","penjagaan"], onyomi:"バン", kunyomi:"つが(い)",
      jukugo:[
        {word:"番号",reading:"ばんごう",meaning:"nomor",priority:"🔥"},
        {word:"当番",reading:"とうばん",meaning:"giliran bertugas, piket",priority:"🔥"},
        {word:"番組",reading:"ばんぐみ",meaning:"program acara (TV/radio)",priority:"🔥"},
        {word:"番人",reading:"ばんにん",meaning:"penjaga, pengawas",priority:"🔥"},
        {word:"一番",reading:"いちばん",meaning:"nomor satu, paling",priority:"🔥"},
        {word:"交番",reading:"こうばん",meaning:"pos polisi",priority:"🔥"},
        {word:"順番",reading:"じゅんばん",meaning:"urutan, antrian",priority:"🔥"},
        {word:"本番",reading:"ほんばん",meaning:"pertunjukan sungguhan, take nyata",priority:"🔥"},
        {word:"番台",reading:"ばんだい",meaning:"meja/kursi kasir (di bathhouse dll)",priority:"⭐"},
        {word:"留守番",reading:"るすばん",meaning:"menjaga rumah saat pemilik tidak ada",priority:"🔥"},
        {word:"門番",reading:"もんばん",meaning:"penjaga gerbang",priority:"⭐"},
        {word:"番外",reading:"ばんがい",meaning:"di luar urutan, ekstra, bonus",priority:"🔥"},
      ],
      family:"番号・順番・当番 → berbagai konteks 'urutan/nomor'. 留守番・門番・番人 → berbagai jenis 'penjagaan'.",
      onyomi_pattern:"バン: 番号(ばん)、当番(ばん)、順番(ばん)。 ~100% sebagai バン.",
      quiz:[
        {type:"baca",question:"番組",answer:"ばんぐみ",hint:"acara TV"},
        {type:"arti",question:"留守番",answer:"menjaga rumah saat pemilik pergi",hint:"留守=tidak ada di rumah"},
        {type:"kanji",question:"こうばん (pos polisi)",answer:"交番",hint:"交=bergantian"},
        {type:"baca",question:"本番",answer:"ほんばん",hint:"pertunjukan sungguhan"},
        {type:"arti",question:"番外",answer:"di luar urutan, ekstra",hint:"外=luar"},
      ]
    },
    { kanji:"号", meaning_core:["nomor","gelar","nama samaran","kode"], onyomi:"ゴウ", kunyomi:"-",
      jukugo:[
        {word:"番号",reading:"ばんごう",meaning:"nomor",priority:"🔥"},
        {word:"信号",reading:"しんごう",meaning:"lampu lalu lintas, sinyal",priority:"🔥"},
        {word:"記号",reading:"きごう",meaning:"simbol, tanda",priority:"🔥"},
        {word:"号令",reading:"ごうれい",meaning:"komando, aba-aba",priority:"🔥"},
        {word:"暗号",reading:"あんごう",meaning:"kode rahasia, enkripsi",priority:"🔥"},
        {word:"符号",reading:"ふごう",meaning:"kode, simbol",priority:"⭐"},
        {word:"号外",reading:"ごうがい",meaning:"edisi ekstra (koran)",priority:"🔥"},
        {word:"号泣",reading:"ごうきゅう",meaning:"menangis tersedu-sedu",priority:"🔥"},
        {word:"名号",reading:"みょうごう",meaning:"nama/gelar Buddha",priority:"○"},
        {word:"型号",reading:"けいごう",meaning:"kode tipe/model (barang)",priority:"⭐"},
        {word:"称号",reading:"しょうごう",meaning:"gelar, titel",priority:"🔥"},
      ],
      family:"番号・信号・記号・暗号・符号 → berbagai jenis 'kode/nomor/sinyal'. 号令・aba-aba. 称号 → gelar/titel.",
      onyomi_pattern:"ゴウ: 番号(ごう)、信号(ごう)、記号(ごう)、号泣(ごう)。 ~100% sebagai ゴウ.",
      quiz:[
        {type:"baca",question:"暗号",answer:"あんごう",hint:"kode rahasia"},
        {type:"arti",question:"号泣",answer:"menangis tersedu-sedu",hint:"泣=menangis"},
        {type:"kanji",question:"しょうごう (gelar/titel)",answer:"称号",hint:"称=menyebut"},
        {type:"baca",question:"号外",answer:"ごうがい",hint:"edisi ekstra koran"},
        {type:"arti",question:"号令",answer:"komando, aba-aba",hint:"令=perintah"},
      ]
    },
    { kanji:"準", meaning_core:["standar","persiapan","setara dengan","semi-"], onyomi:"ジュン", kunyomi:"なぞら(える)",
      jukugo:[
        {word:"準備",reading:"じゅんび",meaning:"persiapan",priority:"🔥"},
        {word:"基準",reading:"きじゅん",meaning:"standar, tolak ukur",priority:"🔥"},
        {word:"標準",reading:"ひょうじゅん",meaning:"standar (normal)",priority:"🔥"},
        {word:"水準",reading:"すいじゅん",meaning:"level, tingkat",priority:"🔥"},
        {word:"準決勝",reading:"じゅんけっしょう",meaning:"semi-final",priority:"🔥"},
        {word:"準優勝",reading:"じゅんゆうしょう",meaning:"peringkat kedua, runner-up",priority:"🔥"},
        {word:"準拠",reading:"じゅんきょ",meaning:"berdasarkan, sesuai dengan",priority:"🔥"},
        {word:"準ずる",reading:"じゅんずる",meaning:"setara dengan, menyesuaikan diri",priority:"🔥"},
        {word:"照準",reading:"しょうじゅん",meaning:"bidikan, membidik sasaran",priority:"🔥"},
        {word:"日準",reading:"にちじゅん",meaning:"standar per hari",priority:"○"},
      ],
      family:"基準・標準・水準 → berbagai jenis 'standar/ukuran'. 準決勝・準優勝 → tingkatan dalam kompetisi. 準備 → persiapan.",
      onyomi_pattern:"ジュン: 準備(じゅん)、基準(じゅん)、標準(じゅん)。 ~100% sebagai ジュン.",
      quiz:[
        {type:"baca",question:"準備",answer:"じゅんび",hint:"persiapan"},
        {type:"arti",question:"標準",answer:"standar (normal)",hint:"標=tanda/patokan"},
        {type:"kanji",question:"じゅんけっしょう (semi-final)",answer:"準決勝",hint:"決勝=final"},
        {type:"baca",question:"基準",answer:"きじゅん",hint:"standar/tolak ukur"},
        {type:"arti",question:"照準",answer:"bidikan, membidik sasaran",hint:"照=bersinar/menerangi"},
      ]
    },
    { kanji:"備", meaning_core:["mempersiapkan","menyiapkan","perlengkapan"], onyomi:"ビ", kunyomi:"そな(える)、そな(わる)",
      jukugo:[
        {word:"準備",reading:"じゅんび",meaning:"persiapan",priority:"🔥"},
        {word:"予備",reading:"よび",meaning:"cadangan, persiapan",priority:"🔥"},
        {word:"装備",reading:"そうび",meaning:"perlengkapan, persenjataan",priority:"🔥"},
        {word:"備品",reading:"びひん",meaning:"peralatan, perlengkapan (milik kantor dll)",priority:"🔥"},
        {word:"設備",reading:"せつび",meaning:"fasilitas, instalasi",priority:"🔥"},
        {word:"警備",reading:"けいび",meaning:"keamanan, pengawasan",priority:"🔥"},
        {word:"防備",reading:"ぼうび",meaning:"pertahanan, penjagaan",priority:"🔥"},
        {word:"完備",reading:"かんび",meaning:"dilengkapi sepenuhnya",priority:"⭐"},
        {word:"整備",reading:"せいび",meaning:"pemeliharaan, perawatan",priority:"🔥"},
        {word:"備考",reading:"びこう",meaning:"catatan, keterangan tambahan",priority:"🔥"},
        {word:"備蓄",reading:"びちく",meaning:"persediaan darurat, cadangan",priority:"🔥"},
      ],
      family:"準備・予備・備蓄 → jenis-jenis 'persiapan/cadangan'. 設備・装備・備品 → 'perlengkapan/fasilitas'. 警備・防備 → 'pertahanan/keamanan'.",
      onyomi_pattern:"ビ: 準備(び)、設備(び)、警備(び)。 ~100% sebagai ビ.",
      quiz:[
        {type:"baca",question:"設備",answer:"せつび",hint:"fasilitas, instalasi"},
        {type:"arti",question:"整備",answer:"pemeliharaan, perawatan",hint:"整=mengatur/merawat"},
        {type:"kanji",question:"けいび (keamanan)",answer:"警備",hint:"警=waspada/polisi"},
        {type:"baca",question:"予備",answer:"よび",hint:"cadangan"},
        {type:"arti",question:"備蓄",answer:"persediaan darurat, cadangan",hint:"蓄=menimbun"},
      ]
    },
    { kanji:"偶", meaning_core:["kebetulan","ganjil/genap","boneka","berpasangan"], onyomi:"グウ", kunyomi:"たま(たま)",
      jukugo:[
        {word:"偶然",reading:"ぐうぜん",meaning:"kebetulan, secara tidak sengaja",priority:"🔥"},
        {word:"偶数",reading:"ぐうすう",meaning:"bilangan genap",priority:"🔥"},
        {word:"配偶者",reading:"はいぐうしゃ",meaning:"pasangan (suami/istri), spouse",priority:"🔥"},
        {word:"偶像",reading:"ぐうぞう",meaning:"idola, patung (agama)",priority:"🔥"},
        {word:"偶発",reading:"ぐうはつ",meaning:"insidental, terjadi secara kebetulan",priority:"🔥"},
        {word:"偶然性",reading:"ぐうぜんせい",meaning:"kesifatan kebetulan, kontigensi",priority:"⭐"},
        {word:"偶然に",reading:"ぐうぜんに",meaning:"secara kebetulan",priority:"🔥"},
      ],
      family:"偶然・偶発 → konsep 'kebetulan'. 偶数 → 'bilangan genap'. 偶像・配偶者 → konteks 'berpasangan/dua'.",
      onyomi_pattern:"グウ: 偶然(ぐう)、偶数(ぐう)、偶像(ぐう)。 ~100% sebagai グウ.",
      quiz:[
        {type:"baca",question:"偶然",answer:"ぐうぜん",hint:"kebetulan"},
        {type:"arti",question:"配偶者",answer:"pasangan (suami/istri)",hint:"配=mengatur/pasangan"},
        {type:"kanji",question:"ぐうぞう (idola)",answer:"偶像",hint:"像=patung/gambaran"},
        {type:"baca",question:"偶数",answer:"ぐうすう",hint:"bilangan genap"},
        {type:"arti",question:"偶発",answer:"insidental, terjadi secara kebetulan",hint:"発=terjadi/keluar"},
      ]
    },
    { kanji:"深", meaning_core:["dalam","mendalam","gelap","intens"], onyomi:"シン", kunyomi:"ふか(い)、ふか(まる)、ふか(める)",
      jukugo:[
        {word:"深い",reading:"ふかい",meaning:"dalam, mendalam",priority:"🔥"},
        {word:"深刻",reading:"しんこく",meaning:"serius, gawat",priority:"🔥"},
        {word:"深呼吸",reading:"しんこきゅう",meaning:"napas dalam-dalam",priority:"🔥"},
        {word:"深夜",reading:"しんや",meaning:"larut malam, dini hari",priority:"🔥"},
        {word:"深度",reading:"しんど",meaning:"kedalaman",priority:"🔥"},
        {word:"水深",reading:"すいしん",meaning:"kedalaman air",priority:"🔥"},
        {word:"深海",reading:"しんかい",meaning:"laut dalam",priority:"🔥"},
        {word:"奥深い",reading:"おくふかい",meaning:"sangat dalam, memiliki kedalaman",priority:"🔥"},
        {word:"深刻化",reading:"しんこくか",meaning:"semakin serius/gawat",priority:"🔥"},
        {word:"深化",reading:"しんか",meaning:"pendalaman, penguatan",priority:"⭐"},
        {word:"深層",reading:"しんそう",meaning:"lapisan dalam, deeper level",priority:"🔥"},
        {word:"深読み",reading:"ふかよみ",meaning:"membaca terlalu dalam, overanalyze",priority:"🔥"},
      ],
      family:"深刻・深刻化 → keseriusan yang meningkat. 深夜・深海・深層 → sesuatu yang sangat 'dalam/terpencil'. 深呼吸・深化 → aksi 'memperdalam'.",
      onyomi_pattern:"シン: 深刻(しん)、深夜(しん)、水深(しん)。 Kunyomi ふかい untuk kata sifat.",
      quiz:[
        {type:"baca",question:"深刻",answer:"しんこく",hint:"serius, gawat"},
        {type:"arti",question:"深夜",answer:"larut malam, dini hari",hint:"夜=malam"},
        {type:"kanji",question:"しんかい (laut dalam)",answer:"深海",hint:"海=laut"},
        {type:"baca",question:"水深",answer:"すいしん",hint:"kedalaman air"},
        {type:"arti",question:"深層",answer:"lapisan dalam, level terdalam",hint:"層=lapisan"},
      ]
    },
    { kanji:"指", meaning_core:["jari","menunjuk","mengarahkan"], onyomi:"シ", kunyomi:"ゆび、さ(す)",
      jukugo:[
        {word:"指示",reading:"しじ",meaning:"instruksi, arahan",priority:"🔥"},
        {word:"指摘",reading:"してき",meaning:"menunjukkan (masalah), menunjuk",priority:"🔥"},
        {word:"指導",reading:"しどう",meaning:"bimbingan, instruksi",priority:"🔥"},
        {word:"指定",reading:"してい",meaning:"penunjukan, penetapan",priority:"🔥"},
        {word:"指名",reading:"しめい",meaning:"penunjukan nama, nominasi",priority:"🔥"},
        {word:"指揮",reading:"しき",meaning:"memimpin, mengomando",priority:"🔥"},
        {word:"親指",reading:"おやゆび",meaning:"ibu jari",priority:"🔥"},
        {word:"人差し指",reading:"ひとさしゆび",meaning:"jari telunjuk",priority:"🔥"},
        {word:"指針",reading:"ししん",meaning:"panduan, petunjuk, pedoman",priority:"🔥"},
        {word:"指数",reading:"しすう",meaning:"indeks, eksponan",priority:"🔥"},
        {word:"指紋",reading:"しもん",meaning:"sidik jari",priority:"🔥"},
        {word:"目指す",reading:"めざす",meaning:"mengincar, bertujuan",priority:"🔥"},
      ],
      family:"指示・指導・指揮・指摘 → berbagai 'tindakan mengarahkan'. 指定・指名 → 'menetapkan/menunjuk seseorang'. 親指・人差し指 → jenis-jenis jari.",
      onyomi_pattern:"シ: 指示(し)、指導(し)、指定(し)、指揮(し)。 Kunyomi ゆび untuk bagian tubuh.",
      quiz:[
        {type:"baca",question:"指導",answer:"しどう",hint:"bimbingan"},
        {type:"arti",question:"指紋",answer:"sidik jari",hint:"紋=pola/motif"},
        {type:"kanji",question:"しじ (instruksi)",answer:"指示",hint:"示=menunjukkan"},
        {type:"baca",question:"目指す",answer:"めざす",hint:"bertujuan/mengincar"},
        {type:"arti",question:"指摘",answer:"menunjukkan (masalah)",hint:"摘=memetik/menunjuk"},
      ]
    },
    { kanji:"認", meaning_core:["mengakui","mengenali","menyetujui"], onyomi:"ニン", kunyomi:"みと(める)、したた(める)",
      jukugo:[
        {word:"認める",reading:"みとめる",meaning:"mengakui, menyetujui",priority:"🔥"},
        {word:"認識",reading:"にんしき",meaning:"pengenalan, kesadaran, persepsi",priority:"🔥"},
        {word:"確認",reading:"かくにん",meaning:"konfirmasi, memastikan",priority:"🔥"},
        {word:"承認",reading:"しょうにん",meaning:"persetujuan, approval",priority:"🔥"},
        {word:"認定",reading:"にんてい",meaning:"sertifikasi, penetapan resmi",priority:"🔥"},
        {word:"認可",reading:"にんか",meaning:"otorisasi, izin resmi",priority:"🔥"},
        {word:"否認",reading:"ひにん",meaning:"penolakan, pengingkaran",priority:"🔥"},
        {word:"認証",reading:"にんしょう",meaning:"autentikasi, sertifikasi",priority:"🔥"},
        {word:"認知",reading:"にんち",meaning:"pengakuan, kesadaran kognitif",priority:"🔥"},
        {word:"自認",reading:"じにん",meaning:"pengakuan diri, menyadari sendiri",priority:"⭐"},
        {word:"公認",reading:"こうにん",meaning:"diakui secara resmi/publik",priority:"🔥"},
      ],
      family:"確認・承認・認可・認定・認証 → berbagai proses 'persetujuan/konfirmasi resmi'. 認識・認知 → proses mental 'mengenali'. 否認 → kebalikannya.",
      onyomi_pattern:"ニン: 認識(にん)、確認(にん)、承認(にん)。 ~100% sebagai ニン.",
      quiz:[
        {type:"baca",question:"確認",answer:"かくにん",hint:"konfirmasi"},
        {type:"arti",question:"承認",answer:"persetujuan, approval",hint:"承=menerima/meneruskan"},
        {type:"kanji",question:"にんしき (pengenalan/persepsi)",answer:"認識",hint:"識=pengetahuan/mengenali"},
        {type:"baca",question:"認証",answer:"にんしょう",hint:"autentikasi"},
        {type:"arti",question:"否認",answer:"penolakan, pengingkaran",hint:"否=tidak/menolak"},
      ]
    },
    { kanji:"操", meaning_core:["mengoperasikan","mengendalikan","moralitas"], onyomi:"ソウ", kunyomi:"あやつ(る)、みさお",
      jukugo:[
        {word:"操作",reading:"そうさ",meaning:"operasi, manipulasi (tindakan)",priority:"🔥"},
        {word:"操縦",reading:"そうじゅう",meaning:"menerbangkan, mengemudikan (kendaraan)",priority:"🔥"},
        {word:"体操",reading:"たいそう",meaning:"senam, gymnastics",priority:"🔥"},
        {word:"操業",reading:"そうぎょう",meaning:"operasi (pabrik/bisnis)",priority:"🔥"},
        {word:"節操",reading:"せっそう",meaning:"integritas, prinsip moral",priority:"🔥"},
        {word:"貞操",reading:"ていそう",meaning:"kesucian, kesetiaan (seksual)",priority:"⭐"},
        {word:"操り人形",reading:"あやつりにんぎょう",meaning:"boneka wayang, puppet",priority:"🔥"},
        {word:"遠隔操作",reading:"えんかくそうさ",meaning:"kontrol jarak jauh, remote control",priority:"🔥"},
      ],
      family:"操作・操縦・遠隔操作 → berbagai jenis 'kontrol/operasi'. 体操 → 'bergerak/senam'. 節操・貞操 → moralitas/prinsip hidup.",
      onyomi_pattern:"ソウ: 操作(そう)、操縦(そう)、体操(そう)。 ~100% sebagai ソウ.",
      quiz:[
        {type:"baca",question:"体操",answer:"たいそう",hint:"senam/gymnastics"},
        {type:"arti",question:"遠隔操作",answer:"kontrol jarak jauh",hint:"遠隔=jarak jauh"},
        {type:"kanji",question:"そうじゅう (menerbangkan)",answer:"操縦",hint:"縦=vertikal/mengendalikan"},
        {type:"baca",question:"節操",answer:"せっそう",hint:"integritas"},
        {type:"arti",question:"操り人形",answer:"boneka wayang, puppet",hint:"人形=boneka"},
      ]
    },
    { kanji:"聖", meaning_core:["suci","kudus","bijaksana (raja)"], onyomi:"セイ", kunyomi:"ひじり",
      jukugo:[
        {word:"神聖",reading:"しんせい",meaning:"sakral, kudus",priority:"🔥"},
        {word:"聖書",reading:"せいしょ",meaning:"Alkitab/Injil",priority:"🔥"},
        {word:"聖地",reading:"せいち",meaning:"tanah suci, tempat ziarah",priority:"🔥"},
        {word:"聖人",reading:"せいじん",meaning:"orang suci, santo",priority:"🔥"},
        {word:"聖火",reading:"せいか",meaning:"api olimpiade, api suci",priority:"🔥"},
        {word:"聖堂",reading:"せいどう",meaning:"katedral, gereja besar",priority:"🔥"},
        {word:"聖戦",reading:"せいせん",meaning:"perang suci, jihad",priority:"🔥"},
        {word:"聖域",reading:"せいいき",meaning:"tempat suci, sanctuary",priority:"🔥"},
        {word:"楽聖",reading:"がくせい",meaning:"maestro musik (gelar kehormatan)",priority:"○"},
        {word:"聖なる",reading:"せいなる",meaning:"yang kudus/suci (kata sifat)",priority:"🔥"},
      ],
      family:"神聖・聖地・聖域 → konsep 'kesucian tempat'. 聖書・聖人・聖堂 → konteks keagamaan.",
      onyomi_pattern:"セイ: 神聖(せい)、聖書(せい)、聖地(せい)。 ~100% sebagai セイ.",
      quiz:[
        {type:"baca",question:"神聖",answer:"しんせい",hint:"sakral/kudus"},
        {type:"arti",question:"聖地",answer:"tanah suci, tempat ziarah",hint:"地=tanah/tempat"},
        {type:"kanji",question:"せいしょ (Alkitab)",answer:"聖書",hint:"書=buku/tulisan"},
        {type:"baca",question:"聖域",answer:"せいいき",hint:"sanctuary, wilayah suci"},
        {type:"arti",question:"聖火",answer:"api olimpiade, api suci",hint:"火=api"},
      ]
    },
    { kanji:"君", meaning_core:["kamu (hormat/akrab)","raja muda","tuan"], onyomi:"クン、クン", kunyomi:"きみ、きん",
      jukugo:[
        {word:"君",reading:"きみ",meaning:"kamu (oleh atasan/pria ke pria)",priority:"🔥"},
        {word:"君主",reading:"くんしゅ",meaning:"raja, monarki",priority:"🔥"},
        {word:"諸君",reading:"しょくん",meaning:"saudara-saudara, hadirin (formal)",priority:"🔥"},
        {word:"昭君",reading:"しょうくん",meaning:"nama orang (historis)",priority:"○"},
        {word:"君子",reading:"くんし",meaning:"orang yang berkarakter mulia, gentleman",priority:"🔥"},
        {word:"主君",reading:"しゅくん",meaning:"tuan/majikan (feodalisme)",priority:"🔥"},
        {word:"君臨",reading:"くんりん",meaning:"memerintah, berkuasa/mendominasi",priority:"🔥"},
        {word:"幼君",reading:"ようくん",meaning:"raja muda, penguasa yang masih anak-anak",priority:"○"},
      ],
      family:"君主・君臨・主君 → berkaitan dengan kekuasaan/kepemimpinan. 君子 → karakter ideal Konfusianisme.",
      onyomi_pattern:"クン: 君主(くん)、君子(くん)、君臨(くん)。 Kunyomi きみ untuk konteks akrab/percakapan.",
      quiz:[
        {type:"baca",question:"君主",answer:"くんしゅ",hint:"raja/monarki"},
        {type:"arti",question:"君臨",answer:"memerintah, berkuasa/mendominasi",hint:"臨=menghadapi/hadir"},
        {type:"kanji",question:"くんし (orang berbudi luhur)",answer:"君子",hint:"子=orang/anak"},
        {type:"baca",question:"諸君",answer:"しょくん",hint:"saudara-saudara (formal)"},
        {type:"arti",question:"主君",answer:"tuan/majikan (feodalisme)",hint:"主=utama/tuan"},
      ]
    },
    { kanji:"困", meaning_core:["kesulitan","masalah","bingung","terjebak"], onyomi:"コン", kunyomi:"こま(る)",
      jukugo:[
        {word:"困る",reading:"こまる",meaning:"kesulitan, bingung, dalam masalah",priority:"🔥"},
        {word:"困難",reading:"こんなん",meaning:"kesulitan, hambatan",priority:"🔥"},
        {word:"困惑",reading:"こんわく",meaning:"kebingungan, disorientasi",priority:"🔥"},
        {word:"困窮",reading:"こんきゅう",meaning:"kemiskinan, kesengsaraan",priority:"🔥"},
        {word:"貧困",reading:"ひんこん",meaning:"kemiskinan",priority:"🔥"},
        {word:"困苦",reading:"こんく",meaning:"penderitaan, kesengsaraan",priority:"⭐"},
        {word:"困り果てる",reading:"こまりはてる",meaning:"sangat kebingungan/tidak tahu apa yang harus dilakukan",priority:"🔥"},
      ],
      family:"困難・困惑・困窮 → berbagai jenis 'kesulitan'. 貧困 → kemiskinan. 困る・困り果てる → ekspresi sehari-hari 'dalam kesulitan'.",
      onyomi_pattern:"コン: 困難(こん)、困惑(こん)、貧困(こん)。 ~100% sebagai コン.",
      quiz:[
        {type:"baca",question:"困難",answer:"こんなん",hint:"kesulitan"},
        {type:"arti",question:"貧困",answer:"kemiskinan",hint:"貧=miskin"},
        {type:"kanji",question:"こんわく (kebingungan)",answer:"困惑",hint:"惑=bingung/tersesat"},
        {type:"baca",question:"困窮",answer:"こんきゅう",hint:"kesengsaraan/kemiskinan"},
        {type:"arti",question:"困り果てる",answer:"sangat kebingungan/tidak tahu harus apa",hint:"果てる=habis/ekstrem"},
      ]
    },
    { kanji:"郷", meaning_core:["kampung halaman","daerah asal"], onyomi:"キョウ、ゴウ", kunyomi:"さと",
      jukugo:[
        {word:"故郷",reading:"こきょう",meaning:"kampung halaman",priority:"🔥"},
        {word:"郷土",reading:"きょうど",meaning:"tanah/daerah asal",priority:"🔥"},
        {word:"郷愁",reading:"きょうしゅう",meaning:"nostalgia, rindu kampung",priority:"🔥"},
        {word:"帰郷",reading:"ききょう",meaning:"pulang ke kampung halaman",priority:"🔥"},
        {word:"異郷",reading:"いきょう",meaning:"negeri orang, tanah asing",priority:"🔥"},
        {word:"郷里",reading:"きょうり",meaning:"kampung halaman, tanah kelahiran",priority:"🔥"},
        {word:"在郷",reading:"ざいごう",meaning:"tinggal di daerah/kampung",priority:"⭐"},
        {word:"郷土料理",reading:"きょうどりょうり",meaning:"masakan khas daerah",priority:"🔥"},
      ],
      family:"故郷・郷里・帰郷 → berkaitan dengan 'kampung halaman'. 郷愁 → perasaan 'merindukan kampung'. 異郷 → kampung orang (bukan milik sendiri).",
      onyomi_pattern:"キョウ: 故郷(きょう)、郷土(きょう)、郷愁(きょう)。 ゴウ: 在郷(ごう)。 Dominan キョウ.",
      quiz:[
        {type:"baca",question:"郷愁",answer:"きょうしゅう",hint:"nostalgia/rindu kampung"},
        {type:"arti",question:"帰郷",answer:"pulang ke kampung halaman",hint:"帰=kembali"},
        {type:"kanji",question:"こきょう (kampung halaman)",answer:"故郷",hint:"故=masa lalu"},
        {type:"baca",question:"異郷",answer:"いきょう",hint:"negeri orang, tanah asing"},
        {type:"arti",question:"郷土料理",answer:"masakan khas daerah",hint:"料理=masakan"},
      ]
    },
    { kanji:"黄", meaning_core:["kuning"], onyomi:"コウ、オウ", kunyomi:"き、こ",
      jukugo:[
        {word:"黄色",reading:"きいろ",meaning:"warna kuning",priority:"🔥"},
        {word:"黄金",reading:"おうごん",meaning:"emas; berharga/ideal",priority:"🔥"},
        {word:"黄土",reading:"おうど",meaning:"tanah kuning (loess)",priority:"⭐"},
        {word:"黄熱",reading:"こうねつ",meaning:"demam kuning",priority:"⭐"},
        {word:"黄昏",reading:"たそがれ",meaning:"senja, masa meredup",priority:"🔥"},
        {word:"黄身",reading:"きみ",meaning:"kuning telur",priority:"🔥"},
        {word:"硫黄",reading:"いおう",meaning:"belerang",priority:"🔥"},
        {word:"黄道",reading:"こうどう",meaning:"ekliptika (astronomi)",priority:"○"},
        {word:"黄泉",reading:"よみ",meaning:"dunia orang mati (mitos Jepang)",priority:"⭐"},
        {word:"卵黄",reading:"らんおう",meaning:"kuning telur (istilah ilmiah)",priority:"⭐"},
      ],
      family:"黄色・黄金・黄身 → objek berwarna kuning. 黄昏・黄泉 → idiom/konsep dengan nuansa 'senja/meredup'.",
      onyomi_pattern:"オウ: 黄金(おう)。 コウ: 黄道(こう)。 Kunyomi き/こ dominan dalam percakapan sehari-hari.",
      quiz:[
        {type:"baca",question:"黄金",answer:"おうごん",hint:"emas"},
        {type:"arti",question:"黄昏",answer:"senja, masa meredup",hint:"たそがれ = senja"},
        {type:"kanji",question:"いおう (belerang)",answer:"硫黄",hint:"硫=belerang/sulfur"},
        {type:"baca",question:"卵黄",answer:"らんおう",hint:"kuning telur (ilmiah)"},
        {type:"arti",question:"黄泉",answer:"dunia orang mati",hint:"泉=mata air"},
      ]
    },
    { kanji:"伝", meaning_core:["menyampaikan","mewariskan","tradisi","menular"], onyomi:"デン", kunyomi:"つた(える)、つた(わる)、つた(い)",
      jukugo:[
        {word:"伝える",reading:"つたえる",meaning:"menyampaikan, memberitahu",priority:"🔥"},
        {word:"伝統",reading:"でんとう",meaning:"tradisi",priority:"🔥"},
        {word:"伝説",reading:"でんせつ",meaning:"legenda",priority:"🔥"},
        {word:"伝染",reading:"でんせん",meaning:"penularan (penyakit)",priority:"🔥"},
        {word:"伝達",reading:"でんたつ",meaning:"penyampaian (pesan/informasi)",priority:"🔥"},
        {word:"伝言",reading:"でんごん",meaning:"pesan titipan",priority:"🔥"},
        {word:"伝記",reading:"でんき",meaning:"biografi",priority:"🔥"},
        {word:"宣伝",reading:"せんでん",meaning:"iklan, promosi, propaganda",priority:"🔥"},
        {word:"遺伝",reading:"いでん",meaning:"genetika, keturunan",priority:"🔥"},
        {word:"口伝",reading:"くでん",meaning:"tradisi lisan, disampaikan secara lisan",priority:"⭐"},
        {word:"伝授",reading:"でんじゅ",meaning:"mewariskan ilmu (dari master ke murid)",priority:"🔥"},
        {word:"熱伝導",reading:"ねつでんどう",meaning:"konduksi panas",priority:"⭐"},
      ],
      family:"伝統・伝説 → sesuatu yang diwariskan dari masa lalu. 伝染・遺伝 → sesuatu yang 'menular/diwariskan' secara biologis. 伝言・伝達・伝える → tindakan menyampaikan pesan.",
      onyomi_pattern:"デン: 伝統(でん)、伝染(でん)、宣伝(でん)。 Kunyomi つたえる/つたわる untuk kata kerja.",
      quiz:[
        {type:"baca",question:"伝統",answer:"でんとう",hint:"tradisi"},
        {type:"arti",question:"宣伝",answer:"iklan, promosi, propaganda",hint:"宣=mengumumkan"},
        {type:"kanji",question:"いでん (genetika)",answer:"遺伝",hint:"遺=warisan/meninggalkan"},
        {type:"baca",question:"伝染",answer:"でんせん",hint:"penularan penyakit"},
        {type:"arti",question:"伝授",answer:"mewariskan ilmu (master ke murid)",hint:"授=mengajarkan/memberikan"},
      ]
    },
    { kanji:"掌", meaning_core:["telapak tangan","menggenggam","mengendalikan"], onyomi:"ショウ", kunyomi:"てのひら",
      jukugo:[
        {word:"掌握",reading:"しょうあく",meaning:"menggenggam, menguasai sepenuhnya",priority:"🔥"},
        {word:"掌紋",reading:"しょうもん",meaning:"garis telapak tangan",priority:"⭐"},
        {word:"手掌",reading:"しゅしょう",meaning:"telapak tangan",priority:"⭐"},
        {word:"合掌",reading:"がっしょう",meaning:"menangkupkan kedua tangan (doa)",priority:"🔥"},
        {word:"掌する",reading:"しょうする",meaning:"mengelola, mengurus",priority:"⭐"},
        {word:"掌中",reading:"しょうちゅう",meaning:"dalam genggaman, di tangan sendiri",priority:"⭐"},
        {word:"鼓掌",reading:"こしょう",meaning:"bertepuk tangan",priority:"○"},
      ],
      family:"掌握・掌する → 'menggenggam/menguasai'. 合掌 → doa dengan kedua tangan tertangkup. 掌中 → 'dalam genggaman'.",
      onyomi_pattern:"ショウ: 掌握(しょう)、合掌(しょう)。 Kunyomi てのひら saat berdiri sendiri.",
      quiz:[
        {type:"baca",question:"掌握",answer:"しょうあく",hint:"menguasai sepenuhnya"},
        {type:"arti",question:"合掌",answer:"menangkupkan kedua tangan (doa)",hint:"合=menyatukan"},
        {type:"kanji",question:"しょうちゅう (dalam genggaman)",answer:"掌中",hint:"中=dalam/tengah"},
        {type:"baca",question:"鼓掌",answer:"こしょう",hint:"bertepuk tangan"},
        {type:"arti",question:"掌握",answer:"menggenggam, menguasai sepenuhnya",hint:"握=menggenggam"},
      ]
    },
    { kanji:"造", meaning_core:["membuat","membangun","menciptakan"], onyomi:"ゾウ", kunyomi:"つく(る)",
      jukugo:[
        {word:"造る",reading:"つくる",meaning:"membuat (benda besar/bangunan)",priority:"🔥"},
        {word:"製造",reading:"せいぞう",meaning:"manufaktur, pembuatan",priority:"🔥"},
        {word:"建造",reading:"けんぞう",meaning:"konstruksi, pembangunan",priority:"🔥"},
        {word:"造船",reading:"ぞうせん",meaning:"pembuatan kapal",priority:"🔥"},
        {word:"醸造",reading:"じょうぞう",meaning:"fermentasi, pembuatan bir/sake",priority:"🔥"},
        {word:"改造",reading:"かいぞう",meaning:"modifikasi, renovasi",priority:"🔥"},
        {word:"創造",reading:"そうぞう",meaning:"kreasi, penciptaan",priority:"🔥"},
        {word:"造形",reading:"ぞうけい",meaning:"pembentukan, pemodelan",priority:"🔥"},
        {word:"構造",reading:"こうぞう",meaning:"struktur, susunan",priority:"🔥"},
        {word:"偽造",reading:"ぎぞう",meaning:"pemalsuan, membuat palsu",priority:"🔥"},
        {word:"鋳造",reading:"ちゅうぞう",meaning:"pengecoran (logam)",priority:"⭐"},
        {word:"造花",reading:"ぞうか",meaning:"bunga buatan",priority:"⭐"},
      ],
      family:"製造・建造・造船・醸造 → berbagai jenis 'membuat'. 創造・造形 → 'kreasi/membentuk'. 偽造 → 'membuat yang palsu'. 構造 → hasil dari proses pembuatan.",
      onyomi_pattern:"ゾウ: 製造(ぞう)、創造(ぞう)、構造(ぞう)。 ~100% sebagai ゾウ.",
      quiz:[
        {type:"baca",question:"創造",answer:"そうぞう",hint:"kreasi/penciptaan"},
        {type:"arti",question:"偽造",answer:"pemalsuan",hint:"偽=palsu"},
        {type:"kanji",question:"こうぞう (struktur)",answer:"構造",hint:"構=membangun/membentuk"},
        {type:"baca",question:"醸造",answer:"じょうぞう",hint:"fermentasi/pembuatan sake"},
        {type:"arti",question:"改造",answer:"modifikasi, renovasi",hint:"改=mengubah"},
      ]
    },
    { kanji:"遺", meaning_core:["meninggalkan","warisan","peninggalan"], onyomi:"イ、ユイ", kunyomi:"のこ(す)",
      jukugo:[
        {word:"遺産",reading:"いさん",meaning:"warisan",priority:"🔥"},
        {word:"遺言",reading:"ゆいごん",meaning:"wasiat",priority:"🔥"},
        {word:"遺族",reading:"いぞく",meaning:"keluarga yang ditinggalkan (alm.)",priority:"🔥"},
        {word:"遺伝",reading:"いでん",meaning:"genetika, keturunan",priority:"🔥"},
        {word:"遺骨",reading:"いこつ",meaning:"abu jenazah",priority:"🔥"},
        {word:"遺体",reading:"いたい",meaning:"jenazah, jasad",priority:"🔥"},
        {word:"遺品",reading:"いひん",meaning:"barang peninggalan (almarhum)",priority:"🔥"},
        {word:"世界遺産",reading:"せかいいさん",meaning:"warisan dunia (UNESCO)",priority:"🔥"},
        {word:"遺憾",reading:"いかん",meaning:"penyesalan (formal)",priority:"🔥"},
        {word:"遺棄",reading:"いき",meaning:"penelantaran, pembuangan",priority:"⭐"},
        {word:"遺作",reading:"いさく",meaning:"karya terakhir/posthumous",priority:"⭐"},
      ],
      family:"遺産・遺品・遺作 → 'warisan/peninggalan'. 遺族・遺体・遺骨 → hal yang ditinggalkan oleh almarhum. 遺憾 → perasaan 'penyesalan' (formal).",
      onyomi_pattern:"イ: 遺産(い)、遺族(い)、遺伝(い)。 ユイ: 遺言(ゆい)。 Dominan イ (~90%).",
      quiz:[
        {type:"baca",question:"遺産",answer:"いさん",hint:"warisan"},
        {type:"arti",question:"遺言",answer:"wasiat",hint:"言=kata/pernyataan"},
        {type:"kanji",question:"いかん (penyesalan formal)",answer:"遺憾",hint:"憾=menyesal"},
        {type:"baca",question:"世界遺産",answer:"せかいいさん",hint:"warisan dunia UNESCO"},
        {type:"arti",question:"遺体",answer:"jenazah, jasad",hint:"体=tubuh"},
      ]
    },
    { kanji:"形", meaning_core:["bentuk","wujud","penampilan"], onyomi:"ケイ、ギョウ", kunyomi:"かたち、かた",
      jukugo:[
        {word:"形",reading:"かたち",meaning:"bentuk, wujud",priority:"🔥"},
        {word:"形成",reading:"けいせい",meaning:"pembentukan",priority:"🔥"},
        {word:"形式",reading:"けいしき",meaning:"format, formalitas",priority:"🔥"},
        {word:"形容詞",reading:"けいようし",meaning:"kata sifat",priority:"🔥"},
        {word:"人形",reading:"にんぎょう",meaning:"boneka",priority:"🔥"},
        {word:"変形",reading:"へんけい",meaning:"deformasi, transformasi",priority:"🔥"},
        {word:"地形",reading:"ちけい",meaning:"topografi, bentang alam",priority:"🔥"},
        {word:"形而上",reading:"けいじじょう",meaning:"metafisika (abstrak/di atas materi)",priority:"○"},
        {word:"原形",reading:"げんけい",meaning:"bentuk asli, prototipe",priority:"🔥"},
        {word:"図形",reading:"ずけい",meaning:"figur geometris, gambar",priority:"🔥"},
        {word:"象形",reading:"しょうけい",meaning:"piktogram (karakter bergambar)",priority:"🔥"},
        {word:"整形",reading:"せいけい",meaning:"bedah plastik; ortopedik",priority:"🔥"},
      ],
      family:"形成・変形・整形 → proses 'pembentukan/perubahan bentuk'. 形式・形容詞 → terminologi gramatikal. 地形・図形 → bentuk di alam/geometri.",
      onyomi_pattern:"ケイ: 形成(けい)、形式(けい)、地形(けい)。 ギョウ: 行形(jarang). Dominan ケイ.",
      quiz:[
        {type:"baca",question:"形成",answer:"けいせい",hint:"pembentukan"},
        {type:"arti",question:"象形",answer:"piktogram (karakter bergambar)",hint:"象=gambar/gajah"},
        {type:"kanji",question:"ちけい (topografi)",answer:"地形",hint:"地=tanah/bumi"},
        {type:"baca",question:"整形",answer:"せいけい",hint:"bedah plastik"},
        {type:"arti",question:"図形",answer:"figur geometris, gambar",hint:"図=diagram/gambar"},
      ]
    },
    { kanji:"根", meaning_core:["akar","dasar","kesabaran","sumber"], onyomi:"コン", kunyomi:"ね",
      jukugo:[
        {word:"根本",reading:"こんぽん",meaning:"dasar, fundamental",priority:"🔥"},
        {word:"根拠",reading:"こんきょ",meaning:"dasar/alasan, landasan argumen",priority:"🔥"},
        {word:"根性",reading:"こんじょう",meaning:"kekuatan tekad, semangat keras",priority:"🔥"},
        {word:"根絶",reading:"こんぜつ",meaning:"pemberantasan total, eradikasi",priority:"🔥"},
        {word:"大根",reading:"だいこん",meaning:"lobak putih (daikon)",priority:"🔥"},
        {word:"屋根",reading:"やね",meaning:"atap",priority:"🔥"},
        {word:"語根",reading:"ごこん",meaning:"akar kata (linguistik)",priority:"🔥"},
        {word:"根気",reading:"こんき",meaning:"ketekunan, kesabaran",priority:"🔥"},
        {word:"根底",reading:"こんてい",meaning:"fondasi, dasar paling dalam",priority:"🔥"},
        {word:"毛根",reading:"もうこん",meaning:"akar rambut",priority:"⭐"},
        {word:"山根",reading:"やまね",meaning:"pangkal hidung",priority:"○"},
      ],
      family:"根本・根底・根拠 → 'dasar/fondasi'. 根性・根気 → 'tekad/ketekunan'. 根絶・語根 → 'akar (yang perlu dihilangkan/asal mula)'.",
      onyomi_pattern:"コン: 根本(こん)、根拠(こん)、語根(こん)。 Kunyomi ね untuk kata yang berdiri sendiri.",
      quiz:[
        {type:"baca",question:"根拠",answer:"こんきょ",hint:"alasan/landasan"},
        {type:"arti",question:"根性",answer:"kekuatan tekad, semangat keras",hint:"性=sifat/karakter"},
        {type:"kanji",question:"こんき (ketekunan)",answer:"根気",hint:"気=semangat/energi"},
        {type:"baca",question:"根底",answer:"こんてい",hint:"fondasi terdalam"},
        {type:"arti",question:"根絶",answer:"pemberantasan total, eradikasi",hint:"絶=memutus/menghilangkan"},
      ]
    },
    { kanji:"完", meaning_core:["selesai","sempurna","lengkap"], onyomi:"カン", kunyomi:"-",
      jukugo:[
        {word:"完成",reading:"かんせい",meaning:"penyelesaian, selesai",priority:"🔥"},
        {word:"完全",reading:"かんぜん",meaning:"sempurna, komplit",priority:"🔥"},
        {word:"完了",reading:"かんりょう",meaning:"selesai, terselesaikan",priority:"🔥"},
        {word:"完璧",reading:"かんぺき",meaning:"sempurna tanpa cacat",priority:"🔥"},
        {word:"完結",reading:"かんけつ",meaning:"penyimpulan, selesai (serial dll)",priority:"🔥"},
        {word:"未完成",reading:"みかんせい",meaning:"belum selesai, inkomplit",priority:"🔥"},
        {word:"完治",reading:"かんち",meaning:"sembuh total",priority:"🔥"},
        {word:"完勝",reading:"かんしょう",meaning:"kemenangan mutlak",priority:"🔥"},
        {word:"完敗",reading:"かんぱい",meaning:"kekalahan total",priority:"🔥"},
        {word:"完封",reading:"かんぷう",meaning:"shutout (olahraga, tidak beri skor)",priority:"⭐"},
        {word:"補完",reading:"ほかん",meaning:"pelengkapan, supplementasi",priority:"⭐"},
      ],
      family:"完成・完了・完結 → 'proses berakhir/selesai'. 完全・完璧 → 'kesempurnaan'. 完治・完勝・完敗 → hasil yang mutlak.",
      onyomi_pattern:"カン: 完成(かん)、完全(かん)、完了(かん)。 ~100% sebagai カン.",
      quiz:[
        {type:"baca",question:"完璧",answer:"かんぺき",hint:"sempurna tanpa cacat"},
        {type:"arti",question:"完治",answer:"sembuh total",hint:"治=sembuh/mengobati"},
        {type:"kanji",question:"みかんせい (belum selesai)",answer:"未完成",hint:"未=belum"},
        {type:"baca",question:"完勝",answer:"かんしょう",hint:"kemenangan mutlak"},
        {type:"arti",question:"完結",answer:"penyimpulan, selesai (serial)",hint:"結=mengikat/menyimpulkan"},
      ]
    },
    { kanji:"雪", meaning_core:["salju"], onyomi:"セツ", kunyomi:"ゆき",
      jukugo:[
        {word:"雪",reading:"ゆき",meaning:"salju",priority:"🔥"},
        {word:"雪山",reading:"ゆきやま",meaning:"gunung bersalju",priority:"🔥"},
        {word:"大雪",reading:"おおゆき",meaning:"salju lebat",priority:"🔥"},
        {word:"初雪",reading:"はつゆき",meaning:"salju pertama musim dingin",priority:"🔥"},
        {word:"吹雪",reading:"ふぶき",meaning:"badai salju",priority:"🔥"},
        {word:"積雪",reading:"せきせつ",meaning:"akumulasi salju",priority:"🔥"},
        {word:"降雪",reading:"こうせつ",meaning:"turunnya salju",priority:"🔥"},
        {word:"除雪",reading:"じょせつ",meaning:"penyingkiran salju",priority:"🔥"},
        {word:"雪崩",reading:"なだれ",meaning:"longsor salju, avalanche",priority:"🔥"},
        {word:"雪合戦",reading:"ゆきがっせん",meaning:"perang bola salju",priority:"⭐"},
        {word:"解雪",reading:"かいせつ",meaning:"pencairan salju",priority:"⭐"},
      ],
      family:"積雪・降雪・除雪 → siklus salju (datang, menumpuk, dihilangkan). 大雪・吹雪 → intensitas salju yang kuat.",
      onyomi_pattern:"セツ: 積雪(せつ)、降雪(せつ)、除雪(せつ)。 Kunyomi ゆき dominan dalam percakapan.",
      quiz:[
        {type:"baca",question:"積雪",answer:"せきせつ",hint:"akumulasi salju"},
        {type:"arti",question:"吹雪",answer:"badai salju",hint:"吹=berhembus"},
        {type:"kanji",question:"こうせつ (turunnya salju)",answer:"降雪",hint:"降=turun"},
        {type:"baca",question:"除雪",answer:"じょせつ",hint:"penyingkiran salju"},
        {type:"arti",question:"初雪",answer:"salju pertama musim dingin",hint:"初=pertama"},
      ]
    },
    { kanji:"壊", meaning_core:["rusak","menghancurkan","roboh"], onyomi:"カイ", kunyomi:"こわ(す)、こわ(れる)",
      jukugo:[
        {word:"壊す",reading:"こわす",meaning:"merusak, menghancurkan",priority:"🔥"},
        {word:"壊れる",reading:"こわれる",meaning:"rusak, hancur (intransitif)",priority:"🔥"},
        {word:"破壊",reading:"はかい",meaning:"penghancuran, kerusakan",priority:"🔥"},
        {word:"崩壊",reading:"ほうかい",meaning:"keruntuhan, kehancuran total",priority:"🔥"},
        {word:"損壊",reading:"そんかい",meaning:"kerusakan, kerugian fisik",priority:"🔥"},
        {word:"倒壊",reading:"とうかい",meaning:"roboh, ambruk (bangunan)",priority:"🔥"},
        {word:"自壊",reading:"じかい",meaning:"menghancurkan diri sendiri",priority:"⭐"},
        {word:"壊滅",reading:"かいめつ",meaning:"kehancuran total, annihilasi",priority:"🔥"},
        {word:"老壊",reading:"ろうかい",meaning:"kerusakan karena tua/usang",priority:"○"},
      ],
      family:"破壊・崩壊・壊滅・倒壊 → berbagai tingkat penghancuran. 壊す・壊れる → tindakan sehari-hari 'merusak/rusak'.",
      onyomi_pattern:"カイ: 破壊(かい)、崩壊(かい)、壊滅(かい)。 ~100% sebagai カイ.",
      quiz:[
        {type:"baca",question:"崩壊",answer:"ほうかい",hint:"keruntuhan total"},
        {type:"arti",question:"壊滅",answer:"kehancuran total, annihilasi",hint:"滅=musnah"},
        {type:"kanji",question:"はかい (penghancuran)",answer:"破壊",hint:"破=pecah/rusak"},
        {type:"baca",question:"倒壊",answer:"とうかい",hint:"roboh (bangunan)"},
        {type:"arti",question:"損壊",answer:"kerusakan, kerugian fisik",hint:"損=kerugian/kerusakan"},
      ]
    },
  ]
};
