
// ========== PERTEMUAN 11 ==========
const pertemuan11 = {
  id: 11, title: "Pertemuan 11",
  kanji: [
    { kanji:"軒", meaning_core:["atap/teritisan","menghitung rumah/bangunan"], onyomi:"ケン", kunyomi:"のき",
      jukugo:[
        {word:"軒",reading:"のき",meaning:"teritisan atap, atap yang menjorok",priority:"🔥"},
        {word:"軒並み",reading:"のきなみ",meaning:"barisan rumah; hampir semua",priority:"🔥"},
        {word:"一軒",reading:"いっけん",meaning:"satu bangunan",priority:"🔥"},
        {word:"軒下",reading:"のきした",meaning:"di bawah teritisan",priority:"🔥"},
        {word:"軒先",reading:"のきさき",meaning:"ujung teritisan, pinggir atap",priority:"🔥"},
        {word:"数軒",reading:"すうけん",meaning:"beberapa bangunan/rumah",priority:"🔥"},
        {word:"軒を並べる",reading:"のきをならべる",meaning:"berjejer berdampingan",priority:"⭐"},
      ],
      family:"軒並み → 'berjajar'. 軒下・軒先 → bagian fisik atap. Dipakai sebagai penghitung bangunan: 一軒・数軒.",
      onyomi_pattern:"ケン: 一軒(けん)、数軒(けん)。 Kunyomi のき saat merujuk pada bagian fisik.",
      quiz:[
        {type:"baca",question:"軒並み",answer:"のきなみ",hint:"hampir semua/barisan rumah"},
        {type:"arti",question:"軒下",answer:"di bawah teritisan",hint:"下=bawah"},
        {type:"kanji",question:"いっけん (satu bangunan)",answer:"一軒",hint:"一=satu"},
        {type:"baca",question:"軒先",answer:"のきさき",hint:"ujung teritisan"},
        {type:"arti",question:"軒並み",answer:"barisan rumah; hampir semua",hint:"並み=berjajar"},
      ]
    },
    { kanji:"管", meaning_core:["pipa","tabung","mengatur","mengelola"], onyomi:"カン", kunyomi:"くだ",
      jukugo:[
        {word:"管理",reading:"かんり",meaning:"manajemen, pengelolaan",priority:"🔥"},
        {word:"管轄",reading:"かんかつ",meaning:"yurisdiksi, wilayah kewenangan",priority:"🔥"},
        {word:"血管",reading:"けっかん",meaning:"pembuluh darah",priority:"🔥"},
        {word:"気管",reading:"きかん",meaning:"trakea, saluran napas",priority:"🔥"},
        {word:"水道管",reading:"すいどうかん",meaning:"pipa air",priority:"🔥"},
        {word:"管楽器",reading:"かんがっき",meaning:"alat musik tiup",priority:"🔥"},
        {word:"主管",reading:"しゅかん",meaning:"yang bertanggung jawab, penanggung jawab",priority:"🔥"},
        {word:"所管",reading:"しょかん",meaning:"dalam yurisdiksi/kewenangan",priority:"⭐"},
        {word:"保管",reading:"ほかん",meaning:"penyimpanan, penitipan",priority:"🔥"},
        {word:"監管",reading:"かんかん",meaning:"pengawasan (jarang dipakai)",priority:"○"},
        {word:"管制",reading:"かんせい",meaning:"kontrol, pengendalian (lalu lintas udara)",priority:"🔥"},
      ],
      family:"管理・管轄・管制 → berbagai jenis 'manajemen/pengendalian'. 血管・気管・水道管 → jenis-jenis 'pipa/tabung'.",
      onyomi_pattern:"カン: 管理(かん)、血管(かん)、気管(かん)。 ~100% sebagai カン.",
      quiz:[
        {type:"baca",question:"管理",answer:"かんり",hint:"manajemen"},
        {type:"arti",question:"気管",answer:"trakea, saluran napas",hint:"気=udara/napas"},
        {type:"kanji",question:"けっかん (pembuluh darah)",answer:"血管",hint:"血=darah"},
        {type:"baca",question:"管楽器",answer:"かんがっき",hint:"alat musik tiup"},
        {type:"arti",question:"保管",answer:"penyimpanan, penitipan",hint:"保=menjaga"},
      ]
    },
    { kanji:"価", meaning_core:["harga","nilai"], onyomi:"カ、ケ", kunyomi:"ね",
      jukugo:[
        {word:"価格",reading:"かかく",meaning:"harga",priority:"🔥"},
        {word:"価値",reading:"かち",meaning:"nilai, kegunaan",priority:"🔥"},
        {word:"物価",reading:"ぶっか",meaning:"harga barang-barang",priority:"🔥"},
        {word:"評価",reading:"ひょうか",meaning:"evaluasi, penilaian",priority:"🔥"},
        {word:"単価",reading:"たんか",meaning:"harga satuan",priority:"🔥"},
        {word:"原価",reading:"げんか",meaning:"biaya pokok, harga produksi",priority:"🔥"},
        {word:"株価",reading:"かぶか",meaning:"harga saham",priority:"🔥"},
        {word:"定価",reading:"ていか",meaning:"harga tetap, harga resmi",priority:"🔥"},
        {word:"安価",reading:"あんか",meaning:"harga murah, murah",priority:"🔥"},
        {word:"高価",reading:"こうか",meaning:"mahal, berharga",priority:"🔥"},
        {word:"廉価",reading:"れんか",meaning:"harga terjangkau/murah",priority:"⭐"},
        {word:"価値観",reading:"かちかん",meaning:"sistem nilai, pandangan terhadap nilai",priority:"🔥"},
      ],
      family:"価格・物価・単価・原価・株価 → jenis-jenis 'harga'. 価値・価値観 → 'nilai/sistem nilai'. 評価 → proses menilai.",
      onyomi_pattern:"カ: 価格(か)、物価(か)、評価(か)。 ~100% sebagai カ.",
      quiz:[
        {type:"baca",question:"評価",answer:"ひょうか",hint:"evaluasi/penilaian"},
        {type:"arti",question:"価値観",answer:"sistem nilai, pandangan nilai",hint:"観=cara pandang"},
        {type:"kanji",question:"かかく (harga)",answer:"価格",hint:"格=kualitas/standar"},
        {type:"baca",question:"高価",answer:"こうか",hint:"mahal"},
        {type:"arti",question:"廉価",answer:"harga terjangkau/murah",hint:"廉=murah/bersih"},
      ]
    },
    { kanji:"値", meaning_core:["nilai","harga","angka"], onyomi:"チ", kunyomi:"ね、あたい",
      jukugo:[
        {word:"価値",reading:"かち",meaning:"nilai, kegunaan",priority:"🔥"},
        {word:"値段",reading:"ねだん",meaning:"harga (umum)",priority:"🔥"},
        {word:"値上がり",reading:"ねあがり",meaning:"kenaikan harga",priority:"🔥"},
        {word:"値下がり",reading:"ねさがり",meaning:"penurunan harga",priority:"🔥"},
        {word:"値引き",reading:"ねびき",meaning:"diskon, potongan harga",priority:"🔥"},
        {word:"数値",reading:"すうち",meaning:"nilai numerik, angka",priority:"🔥"},
        {word:"値する",reading:"あたいする",meaning:"sebanding dengan, layak",priority:"🔥"},
        {word:"偏差値",reading:"へんさち",meaning:"deviation score (skor ujian Jepang)",priority:"🔥"},
        {word:"基準値",reading:"きじゅんち",meaning:"nilai standar, nilai batas",priority:"🔥"},
        {word:"中間値",reading:"ちゅうかんち",meaning:"nilai tengah, median",priority:"⭐"},
      ],
      family:"価値・値段・値引き → 'harga dan nilainya'. 数値・偏差値・基準値 → 'angka/nilai terukur'. 値上がり・値下がり → perubahan harga.",
      onyomi_pattern:"チ: 価値(ち)、数値(ち)、偏差値(ち)。 Kunyomi ね untuk harga sehari-hari (値段).",
      quiz:[
        {type:"baca",question:"値段",answer:"ねだん",hint:"harga (umum)"},
        {type:"arti",question:"偏差値",answer:"deviation score (skor ujian Jepang)",hint:"偏差=penyimpangan"},
        {type:"kanji",question:"ねびき (diskon)",answer:"値引き",hint:"引き=menarik/memotong"},
        {type:"baca",question:"数値",answer:"すうち",hint:"nilai numerik"},
        {type:"arti",question:"値する",answer:"sebanding dengan, layak",hint:"形: 〜に値する"},
      ]
    },
    { kanji:"兆", meaning_core:["triliun","pertanda","tanda awal"], onyomi:"チョウ", kunyomi:"きざ(し)、きざ(す)",
      jukugo:[
        {word:"兆し",reading:"きざし",meaning:"pertanda, gejala awal",priority:"🔥"},
        {word:"一兆",reading:"いっちょう",meaning:"satu triliun",priority:"🔥"},
        {word:"兆候",reading:"ちょうこう",meaning:"gejala, tanda-tanda",priority:"🔥"},
        {word:"前兆",reading:"ぜんちょう",meaning:"pertanda, tanda-tanda awal (sebelum kejadian)",priority:"🔥"},
        {word:"吉兆",reading:"きっちょう",meaning:"pertanda baik",priority:"⭐"},
        {word:"凶兆",reading:"きょうちょう",meaning:"pertanda buruk",priority:"⭐"},
        {word:"億兆",reading:"おくちょう",meaning:"ratusan juta, sangat banyak (sastra)",priority:"○"},
      ],
      family:"兆し・兆候・前兆 → berbagai 'pertanda/gejala'. 吉兆・凶兆 → pertanda baik/buruk. 一兆 → satuan bilangan besar.",
      onyomi_pattern:"チョウ: 兆候(ちょう)、前兆(ちょう)。 Kunyomi きざし dalam percakapan umum.",
      quiz:[
        {type:"baca",question:"前兆",answer:"ぜんちょう",hint:"pertanda sebelum kejadian"},
        {type:"arti",question:"兆候",answer:"gejala, tanda-tanda",hint:"候=tanda/gejala"},
        {type:"kanji",question:"きざし (pertanda)",answer:"兆し",hint:"し adalah hiragana"},
        {type:"baca",question:"吉兆",answer:"きっちょう",hint:"pertanda baik"},
        {type:"arti",question:"凶兆",answer:"pertanda buruk",hint:"凶=sial/buruk"},
      ]
    },
    { kanji:"談", meaning_core:["berbicara","pembicaraan","diskusi"], onyomi:"ダン", kunyomi:"-",
      jukugo:[
        {word:"相談",reading:"そうだん",meaning:"konsultasi, berdiskusi",priority:"🔥"},
        {word:"会談",reading:"かいだん",meaning:"pertemuan, perundingan",priority:"🔥"},
        {word:"談話",reading:"だんわ",meaning:"percakapan, obrolan",priority:"🔥"},
        {word:"交渉談",reading:"こうしょうだん",meaning:"pembicaraan negosiasi",priority:"⭐"},
        {word:"冗談",reading:"じょうだん",meaning:"lelucon, candaan",priority:"🔥"},
        {word:"雑談",reading:"ざつだん",meaning:"obrolan ringan, smalltalk",priority:"🔥"},
        {word:"談合",reading:"だんごう",meaning:"kolusi, persetujuan rahasia (tender)",priority:"🔥"},
        {word:"対談",reading:"たいだん",meaning:"wawancara, dialog (dua orang)",priority:"🔥"},
        {word:"懇談",reading:"こんだん",meaning:"diskusi informal yang ramah",priority:"⭐"},
        {word:"美談",reading:"びだん",meaning:"cerita yang indah/menginspirasi",priority:"⭐"},
        {word:"相談室",reading:"そうだんしつ",meaning:"ruang konsultasi",priority:"🔥"},
        {word:"談判",reading:"だんぱん",meaning:"negosiasi (dalam konteks tuntutan)",priority:"⭐"},
      ],
      family:"相談・会談・対談・懇談 → berbagai jenis 'diskusi/pertemuan'. 冗談・雑談・談話 → obrolan ringan. 談合 → diskusi gelap/kolusi.",
      onyomi_pattern:"ダン: 相談(だん)、会談(だん)、冗談(だん)。 ~100% sebagai ダン.",
      quiz:[
        {type:"baca",question:"相談",answer:"そうだん",hint:"konsultasi"},
        {type:"arti",question:"冗談",answer:"lelucon, candaan",hint:"冗=berlebihan/tidak perlu"},
        {type:"kanji",question:"ざつだん (smalltalk)",answer:"雑談",hint:"雑=campur aduk/tidak teratur"},
        {type:"baca",question:"談合",answer:"だんごう",hint:"kolusi"},
        {type:"arti",question:"対談",answer:"wawancara, dialog dua orang",hint:"対=berhadapan"},
      ]
    },
    { kanji:"暮", meaning_core:["senja","sore hari","lewat waktu","mencari nafkah"], onyomi:"ボ", kunyomi:"く(れる)、く(らす)、くれ",
      jukugo:[
        {word:"暮らし",reading:"くらし",meaning:"kehidupan sehari-hari, nafkah",priority:"🔥"},
        {word:"暮らす",reading:"くらす",meaning:"hidup, tinggal",priority:"🔥"},
        {word:"日暮れ",reading:"ひぐれ",meaning:"senja, matahari terbenam",priority:"🔥"},
        {word:"年暮れ",reading:"ねんくれ",meaning:"akhir tahun",priority:"🔥"},
        {word:"暮れる",reading:"くれる",meaning:"hari mulai gelap; tahun berakhir",priority:"🔥"},
        {word:"夕暮れ",reading:"ゆうぐれ",meaning:"senja hari, petang",priority:"🔥"},
        {word:"師走",reading:"しわす",meaning:"bulan Desember (historis)",priority:"⭐"},
        {word:"暮景",reading:"ぼけい",meaning:"pemandangan senja",priority:"○"},
        {word:"歳暮",reading:"せいぼ",meaning:"hadiah akhir tahun",priority:"🔥"},
      ],
      family:"日暮れ・夕暮れ → waktu 'senja'. 暮らし・暮らす → 'kehidupan sehari-hari'. 歳暮 → tradisi akhir tahun.",
      onyomi_pattern:"ボ: 歳暮(ぼ)。 Kunyomi くれ/くら dominan dalam percakapan sehari-hari.",
      quiz:[
        {type:"baca",question:"夕暮れ",answer:"ゆうぐれ",hint:"senja hari"},
        {type:"arti",question:"歳暮",answer:"hadiah akhir tahun",hint:"歳=tahun/usia"},
        {type:"kanji",question:"くらし (kehidupan sehari-hari)",answer:"暮らし",hint:"dari kata kerja くらす"},
        {type:"baca",question:"日暮れ",answer:"ひぐれ",hint:"matahari terbenam"},
        {type:"arti",question:"暮らす",answer:"hidup, tinggal",hint:"verba dasar"},
      ]
    },
    { kanji:"司", meaning_core:["mengelola","memimpin","mengepalai"], onyomi:"シ", kunyomi:"-",
      jukugo:[
        {word:"司法",reading:"しほう",meaning:"peradilan, kehakiman",priority:"🔥"},
        {word:"司会",reading:"しかい",meaning:"moderator, MC acara",priority:"🔥"},
        {word:"上司",reading:"じょうし",meaning:"atasan, pimpinan",priority:"🔥"},
        {word:"司令",reading:"しれい",meaning:"komando, panglima",priority:"🔥"},
        {word:"司書",reading:"ししょ",meaning:"pustakawan",priority:"🔥"},
        {word:"総司令官",reading:"そうしれいかん",meaning:"panglima tertinggi",priority:"🔥"},
        {word:"司令部",reading:"しれいぶ",meaning:"markas komando",priority:"🔥"},
        {word:"行司",reading:"ぎょうじ",meaning:"wasit sumo",priority:"⭐"},
      ],
      family:"司法・司会・司書 → berbagai jenis 'pimpinan/pengurus'. 上司 → atasan kerja. 司令・司令部 → konteks militer.",
      onyomi_pattern:"シ: 司法(し)、司会(し)、上司(し)。 ~100% sebagai シ.",
      quiz:[
        {type:"baca",question:"上司",answer:"じょうし",hint:"atasan"},
        {type:"arti",question:"司書",answer:"pustakawan",hint:"書=buku"},
        {type:"kanji",question:"しかい (MC/moderator)",answer:"司会",hint:"会=pertemuan/acara"},
        {type:"baca",question:"司令部",answer:"しれいぶ",hint:"markas komando"},
        {type:"arti",question:"司法",answer:"peradilan, kehakiman",hint:"法=hukum"},
      ]
    },
    { kanji:"奥", meaning_core:["bagian dalam","jauh ke dalam","mendalam","istri (hormat)"], onyomi:"オウ", kunyomi:"おく",
      jukugo:[
        {word:"奥",reading:"おく",meaning:"bagian dalam, ujung terdalem",priority:"🔥"},
        {word:"奥さん",reading:"おくさん",meaning:"istri (orang lain, sopan)",priority:"🔥"},
        {word:"奥行き",reading:"おくゆき",meaning:"kedalaman (dimensi), jarak dari depan ke belakang",priority:"🔥"},
        {word:"奥深い",reading:"おくふかい",meaning:"sangat mendalam, kompleks",priority:"🔥"},
        {word:"奥地",reading:"おくち",meaning:"pedalaman, daerah terpencil",priority:"🔥"},
        {word:"奥の手",reading:"おくのて",meaning:"kartu as, taktik rahasia",priority:"🔥"},
        {word:"奥義",reading:"おうぎ/おくぎ",meaning:"ajaran rahasia terdalam, keahlian tertinggi",priority:"🔥"},
        {word:"山奥",reading:"やまおく",meaning:"pedalaman gunung",priority:"🔥"},
        {word:"奥底",reading:"おくそこ",meaning:"dasar paling dalam",priority:"⭐"},
      ],
      family:"奥行き・奥深い・奥底 → 'kedalaman/kompleksitas'. 奥地・山奥 → 'pedalaman/terpencil'. 奥の手・奥義 → sesuatu yang tersembunyi/rahasia.",
      onyomi_pattern:"オウ: 奥義(おう). Kunyomi おく dominan dalam percakapan.",
      quiz:[
        {type:"baca",question:"奥深い",answer:"おくふかい",hint:"sangat mendalam"},
        {type:"arti",question:"奥義",answer:"ajaran rahasia, keahlian tertinggi",hint:"義=makna/kebenaran"},
        {type:"kanji",question:"おくち (pedalaman)",answer:"奥地",hint:"地=daerah/tanah"},
        {type:"baca",question:"奥の手",answer:"おくのて",hint:"kartu as/taktik rahasia"},
        {type:"arti",question:"奥行き",answer:"kedalaman (dimensi)",hint:"行き=pergi ke"},
      ]
    },
    { kanji:"労", meaning_core:["kerja keras","usaha","menghargai jasa","kelelahan"], onyomi:"ロウ", kunyomi:"ねぎら(う)",
      jukugo:[
        {word:"労働",reading:"ろうどう",meaning:"pekerjaan, kerja",priority:"🔥"},
        {word:"労働者",reading:"ろうどうしゃ",meaning:"pekerja, buruh",priority:"🔥"},
        {word:"勤労",reading:"きんろう",meaning:"kerja keras, rajin bekerja",priority:"🔥"},
        {word:"苦労",reading:"くろう",meaning:"kesulitan, perjuangan",priority:"🔥"},
        {word:"疲労",reading:"ひろう",meaning:"kelelahan, keletihan",priority:"🔥"},
        {word:"労力",reading:"ろうりょく",meaning:"tenaga, usaha",priority:"🔥"},
        {word:"過労",reading:"かろう",meaning:"kerja berlebih, overwork",priority:"🔥"},
        {word:"功労",reading:"こうろう",meaning:"jasa dan kerja keras",priority:"🔥"},
        {word:"労使",reading:"ろうし",meaning:"pekerja dan pengusaha, serikat buruh vs manajemen",priority:"🔥"},
        {word:"労組",reading:"ろうそ/ろうくみ",meaning:"serikat buruh",priority:"🔥"},
        {word:"老婆心",reading:"ろうばしん",meaning:"perhatian berlebih (dari yang lebih tua)",priority:"○"},
      ],
      family:"労働・勤労・労力 → berbagai nuansa 'bekerja keras'. 苦労・疲労・過労 → 'akibat kerja keras'. 労使・労組 → hubungan industrial.",
      onyomi_pattern:"ロウ: 労働(ろう)、苦労(ろう)、疲労(ろう)。 ~100% sebagai ロウ.",
      quiz:[
        {type:"baca",question:"苦労",answer:"くろう",hint:"perjuangan/kesulitan"},
        {type:"arti",question:"過労",answer:"kerja berlebih, overwork",hint:"過=berlebihan"},
        {type:"kanji",question:"ひろう (kelelahan)",answer:"疲労",hint:"疲=lelah"},
        {type:"baca",question:"労働",answer:"ろうどう",hint:"pekerjaan/kerja"},
        {type:"arti",question:"労使",answer:"pekerja dan pengusaha",hint:"使=pengusaha/pemberi kerja"},
      ]
    },
    { kanji:"略", meaning_core:["singkatan","strategi","meringkas","menyederhanakan"], onyomi:"リャク", kunyomi:"-",
      jukugo:[
        {word:"省略",reading:"しょうりゃく",meaning:"pengurangan, penyederhanaan",priority:"🔥"},
        {word:"略語",reading:"りゃくご",meaning:"singkatan, akronim",priority:"🔥"},
        {word:"略称",reading:"りゃくしょう",meaning:"nama singkatan",priority:"🔥"},
        {word:"戦略",reading:"せんりゃく",meaning:"strategi (militer/bisnis)",priority:"🔥"},
        {word:"計略",reading:"けいりゃく",meaning:"taktik, rencana",priority:"🔥"},
        {word:"攻略",reading:"こうりゃく",meaning:"penaklukan, memenangkan (game/kastil)",priority:"🔥"},
        {word:"侵略",reading:"しんりゃく",meaning:"invasi, agresi",priority:"🔥"},
        {word:"略奪",reading:"りゃくだつ",meaning:"penjarahan, merampas",priority:"🔥"},
        {word:"大略",reading:"たいりゃく",meaning:"garis besar, ringkasan",priority:"⭐"},
        {word:"略図",reading:"りゃくず",meaning:"sketsa, gambar sederhana",priority:"⭐"},
      ],
      family:"省略・略語・略称 → 'menyingkat'. 戦略・計略・攻略 → 'strategi/rencana'. 侵略・略奪 → 'mengambil secara paksa'.",
      onyomi_pattern:"リャク: 省略(りゃく)、戦略(りゃく)、攻略(りゃく)。 ~100% sebagai リャク.",
      quiz:[
        {type:"baca",question:"戦略",answer:"せんりゃく",hint:"strategi"},
        {type:"arti",question:"侵略",answer:"invasi, agresi",hint:"侵=menyerang masuk"},
        {type:"kanji",question:"しょうりゃく (pengurangan)",answer:"省略",hint:"省=menghemat/mengurangi"},
        {type:"baca",question:"攻略",answer:"こうりゃく",hint:"memenangkan/menaklukkan"},
        {type:"arti",question:"略奪",answer:"penjarahan, merampas",hint:"奪=merampas"},
      ]
    },
    { kanji:"騒", meaning_core:["ribut","kacau","membuat keributan"], onyomi:"ソウ", kunyomi:"さわ(ぐ)、さわ(がしい)",
      jukugo:[
        {word:"騒ぐ",reading:"さわぐ",meaning:"membuat keributan, ribut",priority:"🔥"},
        {word:"騒音",reading:"そうおん",meaning:"kebisingan, keributan",priority:"🔥"},
        {word:"騒動",reading:"そうどう",meaning:"keributan, kekacauan",priority:"🔥"},
        {word:"騒々しい",reading:"そうぞうしい",meaning:"ribut sekali, gaduh",priority:"🔥"},
        {word:"物騒",reading:"ぶっそう",meaning:"berbahaya, tidak aman",priority:"🔥"},
        {word:"騒然",reading:"そうぜん",meaning:"dalam keributan, penuh kekacauan",priority:"🔥"},
        {word:"騒乱",reading:"そうらん",meaning:"kerusuhan, pemberontakan",priority:"🔥"},
        {word:"大騒ぎ",reading:"おおさわぎ",meaning:"keributan besar, kehebohan",priority:"🔥"},
        {word:"騒擾",reading:"そうじょう",meaning:"kerusuhan, pemberontakan (formal)",priority:"○"},
      ],
      family:"騒音・騒動・騒乱・騒々しい → berbagai aspek 'keributan/kekacauan'. 物騒 → situasi yang 'tidak aman'. 大騒ぎ → skala keributan yang besar.",
      onyomi_pattern:"ソウ: 騒音(そう)、騒動(そう)、騒乱(そう)。 Kunyomi さわ dominan.",
      quiz:[
        {type:"baca",question:"騒音",answer:"そうおん",hint:"kebisingan"},
        {type:"arti",question:"物騒",answer:"berbahaya, tidak aman",hint:"物=hal/sesuatu"},
        {type:"kanji",question:"おおさわぎ (kehebohan besar)",answer:"大騒ぎ",hint:"大=besar"},
        {type:"baca",question:"騒動",answer:"そうどう",hint:"kekacauan"},
        {type:"arti",question:"騒乱",answer:"kerusuhan, pemberontakan",hint:"乱=kacau"},
      ]
    },
    { kanji:"街", meaning_core:["kota","jalan kota","kawasan"], onyomi:"ガイ、カイ", kunyomi:"まち",
      jukugo:[
        {word:"街",reading:"まち",meaning:"kota, jalan di kota",priority:"🔥"},
        {word:"商店街",reading:"しょうてんがい",meaning:"deretan toko, shopping street",priority:"🔥"},
        {word:"繁華街",reading:"はんかがい",meaning:"kawasan ramai, pusat hiburan kota",priority:"🔥"},
        {word:"市街",reading:"しがい",meaning:"pusat kota, urban area",priority:"🔥"},
        {word:"街道",reading:"かいどう",meaning:"jalan raya utama, jalan pos historis",priority:"🔥"},
        {word:"街頭",reading:"がいとう",meaning:"pinggir jalan, di depan umum",priority:"🔥"},
        {word:"街角",reading:"まちかど",meaning:"sudut jalan, tikungan",priority:"🔥"},
        {word:"下町",reading:"したまち",meaning:"kota bawah (kawasan tradisional)",priority:"🔥"},
        {word:"街路樹",reading:"がいろじゅ",meaning:"pohon di pinggir jalan kota",priority:"🔥"},
        {word:"城下町",reading:"じょうかまち",meaning:"kota kastil",priority:"🔥"},
      ],
      family:"商店街・繁華街・市街 → kawasan kota tertentu. 街道・街頭・街角 → aspek 'jalan/lorong kota'. 下町・城下町 → jenis kota historis.",
      onyomi_pattern:"ガイ: 繁華街(がい)、街頭(がい)、街道(がい)。 カイ: 市街(がい). Kunyomi まち untuk percakapan sehari-hari.",
      quiz:[
        {type:"baca",question:"繁華街",answer:"はんかがい",hint:"pusat hiburan kota"},
        {type:"arti",question:"街道",answer:"jalan raya utama, jalan historis",hint:"道=jalan"},
        {type:"kanji",question:"しょうてんがい (deretan toko)",answer:"商店街",hint:"商店=toko"},
        {type:"baca",question:"街頭",answer:"がいとう",hint:"di pinggir jalan/depan umum"},
        {type:"arti",question:"街路樹",answer:"pohon di pinggir jalan kota",hint:"路=jalan、樹=pohon"},
      ]
    },
    { kanji:"受", meaning_core:["menerima","mengambil","menanggung"], onyomi:"ジュ", kunyomi:"う(ける)、う(かる)",
      jukugo:[
        {word:"受ける",reading:"うける",meaning:"menerima, menanggung",priority:"🔥"},
        {word:"受験",reading:"じゅけん",meaning:"mengikuti ujian",priority:"🔥"},
        {word:"受付",reading:"うけつけ",meaning:"resepsionis, meja pendaftaran",priority:"🔥"},
        {word:"受信",reading:"じゅしん",meaning:"menerima sinyal/pesan",priority:"🔥"},
        {word:"受講",reading:"じゅこう",meaning:"mengikuti kuliah/kursus",priority:"🔥"},
        {word:"受賞",reading:"じゅしょう",meaning:"menerima penghargaan",priority:"🔥"},
        {word:"受容",reading:"じゅよう",meaning:"penerimaan, menerima",priority:"🔥"},
        {word:"享受",reading:"きょうじゅ",meaning:"menikmati, merasakan manfaat",priority:"🔥"},
        {word:"受難",reading:"じゅなん",meaning:"penderitaan (religius/besar)",priority:"⭐"},
        {word:"受け入れる",reading:"うけいれる",meaning:"menerima, mengizinkan masuk",priority:"🔥"},
        {word:"受話器",reading:"じゅわき",meaning:"gagang telepon",priority:"🔥"},
        {word:"受取",reading:"うけとり",meaning:"tanda terima, kwitansi",priority:"🔥"},
      ],
      family:"受験・受講 → 'mengikuti (ujian/kuliah)'. 受信・受取・受話器 → 'menerima sesuatu'. 受賞・享受 → 'menerima sesuatu berharga'.",
      onyomi_pattern:"ジュ: 受験(じゅ)、受信(じゅ)、享受(じゅ)。 Kunyomi うける dominan.",
      quiz:[
        {type:"baca",question:"受験",answer:"じゅけん",hint:"mengikuti ujian"},
        {type:"arti",question:"享受",answer:"menikmati, merasakan manfaat",hint:"享=menikmati"},
        {type:"kanji",question:"じゅしょう (menerima penghargaan)",answer:"受賞",hint:"賞=penghargaan/hadiah"},
        {type:"baca",question:"受講",answer:"じゅこう",hint:"mengikuti kuliah"},
        {type:"arti",question:"受け入れる",answer:"menerima, mengizinkan masuk",hint:"入れる=memasukkan"},
      ]
    },
    { kanji:"踏", meaning_core:["menginjak","memijak","menjejak"], onyomi:"トウ", kunyomi:"ふ(む)、ふ(まえる)",
      jukugo:[
        {word:"踏む",reading:"ふむ",meaning:"menginjak, memijak",priority:"🔥"},
        {word:"踏切",reading:"ふみきり",meaning:"perlintasan kereta api",priority:"🔥"},
        {word:"踏み込む",reading:"ふみこむ",meaning:"melangkah masuk, menerjang",priority:"🔥"},
        {word:"踏まえる",reading:"ふまえる",meaning:"berdasarkan, dengan mengacu pada",priority:"🔥"},
        {word:"一歩踏み出す",reading:"いっぽふみだす",meaning:"mengambil langkah pertama",priority:"🔥"},
        {word:"踏襲",reading:"とうしゅう",meaning:"mengikuti, melanjutkan (tradisi/kebijakan)",priority:"🔥"},
        {word:"踏台",reading:"ふみだい",meaning:"bangku pijakan, stepping stone",priority:"⭐"},
        {word:"足踏み",reading:"あしぶみ",meaning:"berjalan di tempat; stagnan",priority:"🔥"},
      ],
      family:"踏む・踏み込む・足踏み → aksi fisik 'menginjak'. 踏まえる・踏襲 → 'mengikuti/berdasarkan' sesuatu. 踏切 → tempat 'melintas'.",
      onyomi_pattern:"トウ: 踏襲(とう)。 Kunyomi ふむ/ふまえる dominan.",
      quiz:[
        {type:"baca",question:"踏切",answer:"ふみきり",hint:"perlintasan kereta"},
        {type:"arti",question:"踏襲",answer:"mengikuti, melanjutkan tradisi/kebijakan",hint:"襲=menyerang/meneruskan"},
        {type:"kanji",question:"ふまえる (berdasarkan)",answer:"踏まえる",hint:"berdasarkan/mengacu pada"},
        {type:"baca",question:"足踏み",answer:"あしぶみ",hint:"berjalan di tempat"},
        {type:"arti",question:"踏み込む",answer:"melangkah masuk, menerjang",hint:"込む=masuk/terbenam"},
      ]
    },
    { kanji:"販", meaning_core:["menjual","perdagangan","penjualan"], onyomi:"ハン", kunyomi:"-",
      jukugo:[
        {word:"販売",reading:"はんばい",meaning:"penjualan",priority:"🔥"},
        {word:"市販",reading:"しはん",meaning:"dijual di pasaran, tersedia secara komersial",priority:"🔥"},
        {word:"販売店",reading:"はんばいてん",meaning:"toko pengecer",priority:"🔥"},
        {word:"通販",reading:"つうはん",meaning:"belanja online/mail order",priority:"🔥"},
        {word:"代理販売",reading:"だいりはんばい",meaning:"penjualan melalui agen",priority:"⭐"},
        {word:"自動販売機",reading:"じどうはんばいき",meaning:"mesin penjual otomatis, vending machine",priority:"🔥"},
        {word:"展示販売",reading:"てんじはんばい",meaning:"penjualan dengan pameran",priority:"⭐"},
        {word:"直販",reading:"ちょくはん",meaning:"penjualan langsung",priority:"⭐"},
      ],
      family:"販売・市販・通販・直販 → berbagai metode 'penjualan'. 自動販売機 → mesin penjual. 販売店 → tempat penjualan.",
      onyomi_pattern:"ハン: 販売(はん)、市販(はん)、通販(はん)。 ~100% sebagai ハン.",
      quiz:[
        {type:"baca",question:"販売",answer:"はんばい",hint:"penjualan"},
        {type:"arti",question:"自動販売機",answer:"vending machine",hint:"自動=otomatis、機=mesin"},
        {type:"kanji",question:"つうはん (belanja online)",answer:"通販",hint:"通=melalui/menembus"},
        {type:"baca",question:"市販",answer:"しはん",hint:"tersedia di pasaran"},
        {type:"arti",question:"直販",answer:"penjualan langsung",hint:"直=langsung"},
      ]
    },
    { kanji:"虫", meaning_core:["serangga","cacing","bug"], onyomi:"チュウ", kunyomi:"むし",
      jukugo:[
        {word:"虫",reading:"むし",meaning:"serangga, cacing",priority:"🔥"},
        {word:"害虫",reading:"がいちゅう",meaning:"serangga hama",priority:"🔥"},
        {word:"昆虫",reading:"こんちゅう",meaning:"serangga (insecta)",priority:"🔥"},
        {word:"虫歯",reading:"むしば",meaning:"gigi berlubang",priority:"🔥"},
        {word:"虫眼鏡",reading:"むしめがね",meaning:"kaca pembesar",priority:"🔥"},
        {word:"毛虫",reading:"けむし",meaning:"ulat berbulu",priority:"🔥"},
        {word:"蛍",reading:"ほたる",meaning:"kunang-kunang",priority:"🔥"},
        {word:"虫の知らせ",reading:"むしのしらせ",meaning:"firasat buruk",priority:"🔥"},
        {word:"虫けら",reading:"むしけら",meaning:"mahluk kecil tak berdaya (merendahkan)",priority:"⭐"},
        {word:"殺虫剤",reading:"さっちゅうざい",meaning:"insektisida, pembasmi serangga",priority:"🔥"},
        {word:"虫食い",reading:"むしくい",meaning:"dimakan ulat, berlubang",priority:"⭐"},
      ],
      family:"害虫・昆虫・毛虫 → jenis-jenis serangga. 虫歯・虫食い → kerusakan yang disebabkan 'cacing/ulat'. 殺虫剤 → produk melawan serangga. 虫の知らせ → idiom tentang firasat.",
      onyomi_pattern:"チュウ: 害虫(ちゅう)、昆虫(ちゅう)、殺虫剤(ちゅう)。 Kunyomi むし dominan.",
      quiz:[
        {type:"baca",question:"昆虫",answer:"こんちゅう",hint:"serangga (ilmiah)"},
        {type:"arti",question:"殺虫剤",answer:"insektisida",hint:"殺=membunuh、剤=zat kimia"},
        {type:"kanji",question:"むしば (gigi berlubang)",answer:"虫歯",hint:"歯=gigi"},
        {type:"baca",question:"害虫",answer:"がいちゅう",hint:"serangga hama"},
        {type:"arti",question:"虫の知らせ",answer:"firasat buruk",hint:"知らせ=kabar"},
      ]
    },
    { kanji:"窓", meaning_core:["jendela"], onyomi:"ソウ", kunyomi:"まど",
      jukugo:[
        {word:"窓",reading:"まど",meaning:"jendela",priority:"🔥"},
        {word:"窓口",reading:"まどぐち",meaning:"loket, jendela pelayanan",priority:"🔥"},
        {word:"車窓",reading:"しゃそう",meaning:"jendela kendaraan (kereta/bus)",priority:"🔥"},
        {word:"同窓",reading:"どうそう",meaning:"alumni, lulusan dari sekolah yang sama",priority:"🔥"},
        {word:"同窓会",reading:"どうそうかい",meaning:"reunian, pertemuan alumni",priority:"🔥"},
        {word:"天窓",reading:"てんまど",meaning:"skylight, jendela atap",priority:"⭐"},
        {word:"出窓",reading:"でまど",meaning:"bay window, jendela yang menjorok",priority:"⭐"},
      ],
      family:"窓口 → jendela pelayanan (metaforis jadi 'loket'). 車窓 → jendela kendaraan. 同窓・同窓会 → teman sekolah (melalui 'jendela yang sama' = ruang kelas yang sama).",
      onyomi_pattern:"ソウ: 同窓(そう)、車窓(そう)。 Kunyomi まど untuk percakapan sehari-hari.",
      quiz:[
        {type:"baca",question:"窓口",answer:"まどぐち",hint:"loket/jendela pelayanan"},
        {type:"arti",question:"同窓会",answer:"reunian, pertemuan alumni",hint:"会=pertemuan"},
        {type:"kanji",question:"しゃそう (jendela kendaraan)",answer:"車窓",hint:"車=kendaraan"},
        {type:"baca",question:"同窓",answer:"どうそう",hint:"alumni sekolah yang sama"},
        {type:"arti",question:"天窓",answer:"skylight, jendela atap",hint:"天=langit"},
      ]
    },
    { kanji:"加", meaning_core:["menambahkan","bergabung","ikut serta"], onyomi:"カ", kunyomi:"くわ(える)、くわ(わる)",
      jukugo:[
        {word:"加える",reading:"くわえる",meaning:"menambahkan",priority:"🔥"},
        {word:"加わる",reading:"くわわる",meaning:"bergabung, ikut",priority:"🔥"},
        {word:"参加",reading:"さんか",meaning:"partisipasi, ikut serta",priority:"🔥"},
        {word:"加速",reading:"かそく",meaning:"akselerasi, percepatan",priority:"🔥"},
        {word:"追加",reading:"ついか",meaning:"penambahan, tambahan",priority:"🔥"},
        {word:"加工",reading:"かこう",meaning:"pengolahan, pemrosesan",priority:"🔥"},
        {word:"加減",reading:"かげん",meaning:"penyesuaian; kondisi (kesehatan)",priority:"🔥"},
        {word:"増加",reading:"ぞうか",meaning:"peningkatan, pertumbuhan",priority:"🔥"},
        {word:"加入",reading:"かにゅう",meaning:"bergabung (anggota), berlangganan",priority:"🔥"},
        {word:"加害者",reading:"かがいしゃ",meaning:"pelaku kejahatan",priority:"🔥"},
        {word:"加速度",reading:"かそくど",meaning:"percepatan (fisika)",priority:"🔥"},
      ],
      family:"参加・加入・加わる → berbagai jenis 'bergabung'. 追加・増加 → 'menambah/bertambah'. 加速・加工・加減 → aksi 'mengubah/mengolah'.",
      onyomi_pattern:"カ: 参加(か)、加速(か)、追加(か)、増加(か)。 ~100% sebagai カ.",
      quiz:[
        {type:"baca",question:"参加",answer:"さんか",hint:"partisipasi"},
        {type:"arti",question:"加害者",answer:"pelaku kejahatan",hint:"害=bahaya、者=orang"},
        {type:"kanji",question:"ぞうか (peningkatan)",answer:"増加",hint:"増=bertambah"},
        {type:"baca",question:"加速",answer:"かそく",hint:"akselerasi"},
        {type:"arti",question:"追加",answer:"penambahan, tambahan",hint:"追=menambahkan/mengejar"},
      ]
    },
    { kanji:"鉄", meaning_core:["besi","baja","keras"], onyomi:"テツ", kunyomi:"-",
      jukugo:[
        {word:"鉄道",reading:"てつどう",meaning:"kereta api",priority:"🔥"},
        {word:"鉄橋",reading:"てっきょう",meaning:"jembatan besi/baja",priority:"🔥"},
        {word:"製鉄",reading:"せいてつ",meaning:"peleburan besi, industri baja",priority:"🔥"},
        {word:"地下鉄",reading:"ちかてつ",meaning:"kereta bawah tanah, metro",priority:"🔥"},
        {word:"鉄砲",reading:"てっぽう",meaning:"senapan",priority:"🔥"},
        {word:"鉄板",reading:"てっぱん",meaning:"lempeng besi; pasti/andalan",priority:"🔥"},
        {word:"鉄則",reading:"てっそく",meaning:"aturan besi, prinsip yang tidak boleh dilanggar",priority:"🔥"},
        {word:"鉄壁",reading:"てっぺき",meaning:"pertahanan baja, sangat kuat",priority:"🔥"},
        {word:"鉄人",reading:"てつじん",meaning:"orang sekuat besi, superhuman",priority:"⭐"},
        {word:"鋼鉄",reading:"こうてつ",meaning:"baja (steel)",priority:"🔥"},
      ],
      family:"鉄道・地下鉄 → transportasi kereta. 鉄橋・鉄板・鋼鉄 → bahan besi/baja. 鉄則・鉄壁 → idiom 'sekuat besi'.",
      onyomi_pattern:"テツ: 鉄道(てつ)、製鉄(てつ)、地下鉄(てつ)。 ~100% sebagai テツ.",
      quiz:[
        {type:"baca",question:"地下鉄",answer:"ちかてつ",hint:"metro/kereta bawah tanah"},
        {type:"arti",question:"鉄則",answer:"aturan besi, prinsip yang tidak boleh dilanggar",hint:"則=aturan/prinsip"},
        {type:"kanji",question:"てつどう (kereta api)",answer:"鉄道",hint:"道=jalan"},
        {type:"baca",question:"鋼鉄",answer:"こうてつ",hint:"baja (steel)"},
        {type:"arti",question:"鉄板",answer:"lempeng besi; pasti/andalan",hint:"板=papan/lempeng"},
      ]
    },
    { kanji:"配", meaning_core:["mendistribusikan","mengkhawatirkan","pasangan","komposisi"], onyomi:"ハイ", kunyomi:"くば(る)",
      jukugo:[
        {word:"心配",reading:"しんぱい",meaning:"khawatir",priority:"🔥"},
        {word:"配る",reading:"くばる",meaning:"membagi-bagikan, mendistribusikan",priority:"🔥"},
        {word:"配達",reading:"はいたつ",meaning:"pengiriman",priority:"🔥"},
        {word:"配布",reading:"はいふ",meaning:"distribusi, penyebaran",priority:"🔥"},
        {word:"配慮",reading:"はいりょ",meaning:"pertimbangan, kepedulian",priority:"🔥"},
        {word:"支配",reading:"しはい",meaning:"kontrol, dominasi",priority:"🔥"},
        {word:"配合",reading:"はいごう",meaning:"kombinasi, perpaduan",priority:"🔥"},
        {word:"配備",reading:"はいび",meaning:"penempatan (pasukan/sumber daya)",priority:"🔥"},
        {word:"配偶者",reading:"はいぐうしゃ",meaning:"pasangan (suami/istri)",priority:"🔥"},
        {word:"宅配",reading:"たくはい",meaning:"pengiriman ke rumah",priority:"🔥"},
        {word:"配電",reading:"はいでん",meaning:"distribusi listrik",priority:"🔥"},
      ],
      family:"配達・配布・宅配 → berbagai jenis 'pengiriman'. 心配・配慮 → perasaan 'peduli/khawatir'. 支配・配備 → 'pengendalian/penempatan'.",
      onyomi_pattern:"ハイ: 配達(はい)、配布(はい)、支配(はい)。 Kunyomi くばる untuk kata kerja.",
      quiz:[
        {type:"baca",question:"心配",answer:"しんぱい",hint:"khawatir"},
        {type:"arti",question:"支配",answer:"kontrol, dominasi",hint:"支=mendukung/menopang"},
        {type:"kanji",question:"はいりょ (kepedulian)",answer:"配慮",hint:"慮=mempertimbangkan"},
        {type:"baca",question:"宅配",answer:"たくはい",hint:"pengiriman ke rumah"},
        {type:"arti",question:"配偶者",answer:"pasangan (suami/istri)",hint:"偶=berpasangan"},
      ]
    },
    { kanji:"慮", meaning_core:["mempertimbangkan","merenung","kekhawatiran"], onyomi:"リョ", kunyomi:"-",
      jukugo:[
        {word:"配慮",reading:"はいりょ",meaning:"pertimbangan, kepedulian",priority:"🔥"},
        {word:"考慮",reading:"こうりょ",meaning:"pertimbangan, dipikirkan secara matang",priority:"🔥"},
        {word:"遠慮",reading:"えんりょ",meaning:"menahan diri, tidak ingin merepotkan",priority:"🔥"},
        {word:"憂慮",reading:"ゆうりょ",meaning:"kekhawatiran serius",priority:"🔥"},
        {word:"熟慮",reading:"じゅくりょ",meaning:"pertimbangan yang matang",priority:"🔥"},
        {word:"深慮",reading:"しんりょ",meaning:"pertimbangan mendalam",priority:"⭐"},
        {word:"先慮",reading:"せんりょ",meaning:"perencanaan/antisipasi ke depan",priority:"○"},
        {word:"無慮",reading:"むりょ",meaning:"sekitar, kira-kira (kuno)",priority:"○"},
      ],
      family:"配慮・考慮・熟慮・深慮 → berbagai derajat 'pertimbangan'. 遠慮 → menahan diri karena pertimbangan sosial. 憂慮 → khawatir dengan pertimbangan.",
      onyomi_pattern:"リョ: 配慮(りょ)、考慮(りょ)、遠慮(りょ)。 ~100% sebagai リョ.",
      quiz:[
        {type:"baca",question:"遠慮",answer:"えんりょ",hint:"menahan diri"},
        {type:"arti",question:"考慮",answer:"pertimbangan yang matang",hint:"考=memikir"},
        {type:"kanji",question:"ゆうりょ (kekhawatiran serius)",answer:"憂慮",hint:"憂=khawatir/sedih"},
        {type:"baca",question:"熟慮",answer:"じゅくりょ",hint:"pertimbangan matang"},
        {type:"arti",question:"配慮",answer:"pertimbangan, kepedulian",hint:"配=mendistribusikan/memperhatikan"},
      ]
    },
    { kanji:"含", meaning_core:["mengandung","termasuk","berisi"], onyomi:"ガン", kunyomi:"ふく(む)、ふく(める)",
      jukugo:[
        {word:"含む",reading:"ふくむ",meaning:"mengandung, termasuk",priority:"🔥"},
        {word:"含める",reading:"ふくめる",meaning:"memasukkan, menyertakan",priority:"🔥"},
        {word:"含有",reading:"がんゆう",meaning:"kandungan (zat/unsur)",priority:"🔥"},
        {word:"包含",reading:"ほうがん",meaning:"mengandung/mencakup secara keseluruhan",priority:"🔥"},
        {word:"含蓄",reading:"がんちく",meaning:"kedalaman makna, makna tersirat",priority:"🔥"},
        {word:"含む意味",reading:"ふくむいみ",meaning:"makna yang terkandung, konotasi",priority:"⭐"},
        {word:"内含",reading:"ないがん",meaning:"yang terkandung di dalam",priority:"○"},
        {word:"含意",reading:"がんい",meaning:"implikasi, makna tersirat",priority:"🔥"},
      ],
      family:"含む・含有・包含 → berbagai nuansa 'mengandung/mencakup'. 含蓄・含意 → 'makna yang dalam/tersembunyi'.",
      onyomi_pattern:"ガン: 含有(がん)、包含(がん)、含蓄(がん)。 Kunyomi ふくむ untuk kata kerja sehari-hari.",
      quiz:[
        {type:"baca",question:"含有",answer:"がんゆう",hint:"kandungan (zat)"},
        {type:"arti",question:"含蓄",answer:"kedalaman makna, makna tersirat",hint:"蓄=menimbun/mendalam"},
        {type:"kanji",question:"ふくめる (menyertakan)",answer:"含める",hint:"versi transitif dari 含む"},
        {type:"baca",question:"包含",answer:"ほうがん",hint:"mencakup sepenuhnya"},
        {type:"arti",question:"含意",answer:"implikasi, makna tersirat",hint:"意=makna/niat"},
      ]
    },
  ]
};
