
// ========== PERTEMUAN 6 ==========
const pertemuan6 = {
  id: 6,
  title: "Pertemuan 6",
  kanji: [
    {
      kanji: "句",
      meaning_core: ["klausa", "frasa", "baris puisi", "ungkapan"],
      onyomi: "ク",
      kunyomi: "-",
      jukugo: [
        { word: "句読点", reading: "くとうてん", meaning: "tanda baca", priority: "🔥" },
        { word: "文句", reading: "もんく", meaning: "keluhan, ungkapan", priority: "🔥" },
        { word: "句", reading: "く", meaning: "klausa, frasa puisi", priority: "🔥" },
        { word: "俳句", reading: "はいく", meaning: "haiku (puisi)", priority: "🔥" },
        { word: "節句", reading: "せっく", meaning: "hari festival musiman", priority: "⭐" },
        { word: "句集", reading: "くしゅう", meaning: "kumpulan puisi", priority: "⭐" },
        { word: "成句", reading: "せいく", meaning: "idiom, ungkapan tetap", priority: "⭐" },
        { word: "慣用句", reading: "かんようく", meaning: "idiom, ungkapan lazim", priority: "🔥" },
        { word: "句点", reading: "くてん", meaning: "tanda titik (。)", priority: "⭐" },
        { word: "読点", reading: "とうてん", meaning: "tanda koma (、)", priority: "⭐" },
        { word: "字句", reading: "じく", meaning: "kata-kata, susunan kalimat", priority: "⭐" },
        { word: "語句", reading: "ごく", meaning: "kata dan frasa", priority: "🔥" },
        { word: "詩句", reading: "しく", meaning: "baris puisi", priority: "○" },
        { word: "句法", reading: "くほう", meaning: "tata cara frasa, gaya bahasa", priority: "○" },
        { word: "禁句", reading: "きんく", meaning: "kata/frasa yang dilarang/tabu", priority: "⭐" },
      ],
      family: "文句・語句・句読点 — semua berkaitan dengan satuan bahasa: 'kata, klausa, frasa, ungkapan'.",
      onyomi_pattern: "ク dominan: 句読点(く)、文句(く dalam もん＋く)、俳句(く)、語句(く)。 Hampir 100% jukugo membaca 句 sebagai ク.",
      quiz: [
        { type: "baca", question: "文句", answer: "もんく", hint: "keluhan" },
        { type: "arti", question: "俳句", answer: "haiku, puisi 5-7-5", hint: "bentuk puisi" },
        { type: "kanji", question: "かんようく (idiom)", answer: "慣用句", hint: "ungkapan lazim" },
        { type: "baca", question: "句読点", answer: "くとうてん", hint: "tanda baca" },
        { type: "arti", question: "語句", answer: "kata dan frasa", hint: "satuan bahasa" },
      ]
    },
    {
      kanji: "等",
      meaning_core: ["sama rata", "kelas/tingkatan", "dan lain-lain", "dsb"],
      onyomi: "トウ",
      kunyomi: "ひと(しい)、など",
      jukugo: [
        { word: "等しい", reading: "ひとしい", meaning: "sama, setara", priority: "🔥" },
        { word: "等級", reading: "とうきゅう", meaning: "kelas, tingkat", priority: "🔥" },
        { word: "平等", reading: "びょうどう", meaning: "kesetaraan, persamaan", priority: "🔥" },
        { word: "等分", reading: "とうぶん", meaning: "pembagian rata", priority: "🔥" },
        { word: "等号", reading: "とうごう", meaning: "tanda sama dengan (=)", priority: "⭐" },
        { word: "高等", reading: "こうとう", meaning: "tinggi, tingkat lanjut", priority: "🔥" },
        { word: "上等", reading: "じょうとう", meaning: "berkualitas tinggi", priority: "🔥" },
        { word: "中等", reading: "ちゅうとう", meaning: "tingkat menengah", priority: "⭐" },
        { word: "一等", reading: "いっとう", meaning: "peringkat pertama", priority: "🔥" },
        { word: "等価", reading: "とうか", meaning: "nilai yang sama, ekuivalen", priority: "⭐" },
        { word: "等身大", reading: "とうしんだい", meaning: "ukuran sebenarnya/nyata", priority: "⭐" },
        { word: "等差", reading: "とうさ", meaning: "selisih yang sama (aritmetika)", priority: "○" },
        { word: "優等", reading: "ゆうとう", meaning: "unggul, berprestasi", priority: "⭐" },
        { word: "劣等", reading: "れっとう", meaning: "rendah diri, inferior", priority: "⭐" },
        { word: "対等", reading: "たいとう", meaning: "setara, sejajar", priority: "🔥" },
        { word: "不平等", reading: "ふびょうどう", meaning: "ketidaksetaraan", priority: "🔥" },
      ],
      family: "平等・対等・優等・劣等 → semua bermakna 'perbandingan dan kesetaraan'. 等級・高等・中等 → berkaitan dengan 'tingkatan/kelas'.",
      onyomi_pattern: "トウ: 等級(とうきゅう)、平等(びょうどう→ dō dari 等)、高等(こうとう)。 Dominan ~90% sebagai トウ/ドウ.",
      quiz: [
        { type: "baca", question: "平等", answer: "びょうどう", hint: "persamaan hak" },
        { type: "arti", question: "高等", answer: "tinggi/tingkat lanjut", hint: "高=tinggi, 等=tingkat" },
        { type: "kanji", question: "たいとう (setara)", answer: "対等", hint: "sejajar, tidak ada yang lebih" },
        { type: "baca", question: "優等", answer: "ゆうとう", hint: "unggul" },
        { type: "arti", question: "劣等", answer: "rendah diri, inferior", hint: "劣=inferior" },
      ]
    },
    {
      kanji: "難",
      meaning_core: ["sulit", "susah", "bencana", "kesulitan"],
      onyomi: "ナン",
      kunyomi: "むずか(しい)、かた(い)",
      jukugo: [
        { word: "難しい", reading: "むずかしい", meaning: "sulit, susah", priority: "🔥" },
        { word: "困難", reading: "こんなん", meaning: "kesulitan, susah payah", priority: "🔥" },
        { word: "難問", reading: "なんもん", meaning: "soal yang sulit", priority: "🔥" },
        { word: "難関", reading: "なんかん", meaning: "hambatan sulit, seleksi ketat", priority: "🔥" },
        { word: "難点", reading: "なんてん", meaning: "kelemahan, titik kesulitan", priority: "🔥" },
        { word: "難易度", reading: "なんいど", meaning: "tingkat kesulitan", priority: "🔥" },
        { word: "難民", reading: "なんみん", meaning: "pengungsi", priority: "🔥" },
        { word: "避難", reading: "ひなん", meaning: "evakuasi, mengungsi", priority: "🔥" },
        { word: "難題", reading: "なんだい", meaning: "masalah sulit", priority: "⭐" },
        { word: "苦難", reading: "くなん", meaning: "penderitaan, kesukaran", priority: "⭐" },
        { word: "難航", reading: "なんこう", meaning: "berlayar/berjalan susah payah", priority: "⭐" },
        { word: "難読", reading: "なんどく", meaning: "sulit dibaca", priority: "⭐" },
        { word: "難病", reading: "なんびょう", meaning: "penyakit yang sulit disembuhkan", priority: "⭐" },
        { word: "非難", reading: "ひなん", meaning: "kritik, kecaman", priority: "🔥" },
        { word: "無難", reading: "ぶなん", meaning: "aman, tidak ada masalah", priority: "🔥" },
        { word: "受難", reading: "じゅなん", meaning: "penderitaan (religius/besar)", priority: "○" },
      ],
      family: "困難・苦難・受難 → penderitaan/kesulitan besar. 難問・難関・難題 → sesuatu yang sulit dihadapi. 避難・非難 → keduanya berbunyi ひなん tetapi beda makna!",
      onyomi_pattern: "ナン: 困難(なん)、難問(なん)、避難(なん)。 Hampir 100% sebagai ナン dalam jukugo.",
      quiz: [
        { type: "baca", question: "困難", answer: "こんなん", hint: "kesulitan besar" },
        { type: "arti", question: "避難", answer: "evakuasi, mengungsi", hint: "menghindari bencana" },
        { type: "kanji", question: "なんみん (pengungsi)", answer: "難民", hint: "民=rakyat, warga" },
        { type: "baca", question: "非難", answer: "ひなん", hint: "kritik keras" },
        { type: "arti", question: "無難", answer: "aman, tidak bermasalah", hint: "無=tidak ada" },
      ]
    },
    {
      kanji: "将",
      meaning_core: ["akan (masa depan)", "pemimpin militer", "jenderal"],
      onyomi: "ショウ",
      kunyomi: "まさ(に)、ひき(いる)",
      jukugo: [
        { word: "将来", reading: "しょうらい", meaning: "masa depan, kelak", priority: "🔥" },
        { word: "将軍", reading: "しょうぐん", meaning: "jenderal, shogun", priority: "🔥" },
        { word: "将棋", reading: "しょうぎ", meaning: "catur Jepang (shogi)", priority: "🔥" },
        { word: "主将", reading: "しゅしょう", meaning: "kapten tim, komandan", priority: "🔥" },
        { word: "大将", reading: "たいしょう", meaning: "panglima, jenderal besar", priority: "🔥" },
        { word: "将校", reading: "しょうこう", meaning: "perwira militer", priority: "⭐" },
        { word: "将帥", reading: "しょうすい", meaning: "komandan tertinggi", priority: "○" },
        { word: "副将", reading: "ふくしょう", meaning: "wakil kapten", priority: "⭐" },
        { word: "将士", reading: "しょうし", meaning: "perwira dan prajurit", priority: "○" },
        { word: "猛将", reading: "もうしょう", meaning: "jenderal yang gagah berani", priority: "○" },
        { word: "老将", reading: "ろうしょう", meaning: "jenderal tua berpengalaman", priority: "○" },
        { word: "将又", reading: "はたまた", meaning: "atau lagi, lebih-lebih lagi", priority: "○" },
        { word: "将来性", reading: "しょうらいせい", meaning: "potensi masa depan", priority: "🔥" },
      ],
      family: "将来・将来性 → orientasi masa depan. 将軍・大将・主将・副将 → hierarki kepemimpinan militer.",
      onyomi_pattern: "ショウ: 将来(しょう)、将軍(しょう)、主将(しょう)。 100% dibaca ショウ dalam jukugo.",
      quiz: [
        { type: "baca", question: "将来", answer: "しょうらい", hint: "masa depan" },
        { type: "arti", question: "将棋", answer: "shogi (catur Jepang)", hint: "permainan papan" },
        { type: "kanji", question: "たいしょう (panglima)", answer: "大将", hint: "pemimpin besar" },
        { type: "baca", question: "主将", answer: "しゅしょう", hint: "kapten tim" },
        { type: "arti", question: "将来性", answer: "potensi masa depan", hint: "性=sifat/karakter" },
      ]
    },
    {
      kanji: "記",
      meaning_core: ["mencatat", "ingatan", "catatan", "rekaman"],
      onyomi: "キ",
      kunyomi: "しる(す)",
      jukugo: [
        { word: "記録", reading: "きろく", meaning: "catatan, rekaman, rekor", priority: "🔥" },
        { word: "記事", reading: "きじ", meaning: "artikel berita", priority: "🔥" },
        { word: "記念", reading: "きねん", meaning: "peringatan, kenang-kenangan", priority: "🔥" },
        { word: "記憶", reading: "きおく", meaning: "ingatan, memori", priority: "🔥" },
        { word: "日記", reading: "にっき", meaning: "buku harian, diary", priority: "🔥" },
        { word: "記者", reading: "きしゃ", meaning: "jurnalis, wartawan", priority: "🔥" },
        { word: "記号", reading: "きごう", meaning: "simbol, tanda", priority: "🔥" },
        { word: "記述", reading: "きじゅつ", meaning: "deskripsi, uraian tertulis", priority: "🔥" },
        { word: "日記帳", reading: "にっきちょう", meaning: "buku harian", priority: "⭐" },
        { word: "伝記", reading: "でんき", meaning: "biografi", priority: "🔥" },
        { word: "速記", reading: "そっき", meaning: "steno, tulisan cepat", priority: "⭐" },
        { word: "記入", reading: "きにゅう", meaning: "mengisi (formulir)", priority: "🔥" },
        { word: "記載", reading: "きさい", meaning: "pencatatan, registrasi tertulis", priority: "⭐" },
        { word: "手記", reading: "しゅき", meaning: "catatan tangan, memoar", priority: "⭐" },
        { word: "暗記", reading: "あんき", meaning: "menghafal", priority: "🔥" },
        { word: "記章", reading: "きしょう", meaning: "lencana, emblem", priority: "○" },
      ],
      family: "記録・記事・記述 → aktivitas menulis/mendokumentasikan. 記憶・暗記 → aktivitas mengingat. 日記・伝記・手記 → jenis-jenis catatan/tulisan.",
      onyomi_pattern: "キ: 記録(き)、記事(き)、記念(き)、日記(き)。 ~100% sebagai キ.",
      quiz: [
        { type: "baca", question: "記憶", answer: "きおく", hint: "ingatan/memori" },
        { type: "arti", question: "暗記", answer: "menghafal", hint: "暗=gelap/hafalan" },
        { type: "kanji", question: "きしゃ (wartawan)", answer: "記者", hint: "者=orang" },
        { type: "baca", question: "伝記", answer: "でんき", hint: "biografi" },
        { type: "arti", question: "記入", answer: "mengisi/mencatat di formulir", hint: "入=masuk" },
      ]
    },
    {
      kanji: "功",
      meaning_core: ["jasa", "prestasi", "keberhasilan", "pencapaian"],
      onyomi: "コウ、ク",
      kunyomi: "-",
      jukugo: [
        { word: "成功", reading: "せいこう", meaning: "kesuksesan, keberhasilan", priority: "🔥" },
        { word: "功績", reading: "こうせき", meaning: "jasa, prestasi besar", priority: "🔥" },
        { word: "功労", reading: "こうろう", meaning: "jasa dan kerja keras", priority: "🔥" },
        { word: "功名", reading: "こうみょう", meaning: "reputasi/nama dari jasa besar", priority: "⭐" },
        { word: "武功", reading: "ぶこう", meaning: "jasa militer, prestasi perang", priority: "⭐" },
        { word: "功利", reading: "こうり", meaning: "utilitas, pragmatisme", priority: "⭐" },
        { word: "功罪", reading: "こうざい", meaning: "jasa dan dosa, pro dan kontra", priority: "⭐" },
        { word: "論功", reading: "ろんこう", meaning: "penilain jasa seseorang", priority: "○" },
        { word: "功徳", reading: "くどく", meaning: "kebajikan, pahala (Buddha)", priority: "⭐" },
        { word: "大功", reading: "たいこう", meaning: "jasa besar", priority: "○" },
        { word: "年功序列", reading: "ねんこうじょれつ", meaning: "sistem senioritas berdasarkan usia", priority: "🔥" },
        { word: "功過", reading: "こうか", meaning: "kebaikan dan kesalahan", priority: "○" },
        { word: "成功者", reading: "せいこうしゃ", meaning: "orang yang sukses", priority: "🔥" },
      ],
      family: "成功・功績・功労 → semua berkaitan dengan pencapaian positif/keberhasilan. 功罪・功過 → sisi ganda dari suatu tindakan.",
      onyomi_pattern: "コウ: 成功(こう)、功績(こう)、功労(こう). ク: 功徳(く). Dominan コウ (~90%).",
      quiz: [
        { type: "baca", question: "成功", answer: "せいこう", hint: "berhasil" },
        { type: "arti", question: "功績", answer: "jasa, prestasi besar", hint: "prestasi yang besar" },
        { type: "kanji", question: "こうろう (jasa/kerja keras)", answer: "功労", hint: "労=kerja keras" },
        { type: "baca", question: "年功序列", answer: "ねんこうじょれつ", hint: "sistem karir Jepang" },
        { type: "arti", question: "功徳", answer: "pahala, kebajikan (Buddha)", hint: "徳=kebajikan" },
      ]
    },
    {
      kanji: "誌",
      meaning_core: ["majalah", "jurnal", "catatan tertulis"],
      onyomi: "シ",
      kunyomi: "-",
      jukugo: [
        { word: "雑誌", reading: "ざっし", meaning: "majalah", priority: "🔥" },
        { word: "週刊誌", reading: "しゅうかんし", meaning: "majalah mingguan", priority: "🔥" },
        { word: "月刊誌", reading: "げっかんし", meaning: "majalah bulanan", priority: "🔥" },
        { word: "日誌", reading: "にっし", meaning: "jurnal harian, log harian", priority: "🔥" },
        { word: "社誌", reading: "しゃし", meaning: "majalah/jurnal perusahaan", priority: "⭐" },
        { word: "誌上", reading: "しじょう", meaning: "di atas halaman majalah/jurnal", priority: "⭐" },
        { word: "機関誌", reading: "きかんし", meaning: "jurnal lembaga/organisasi", priority: "⭐" },
        { word: "学誌", reading: "がくし", meaning: "jurnal akademis", priority: "⭐" },
        { word: "誌面", reading: "しめん", meaning: "halaman majalah/jurnal", priority: "⭐" },
        { word: "航海日誌", reading: "こうかいにっし", meaning: "log/catatan perjalanan laut", priority: "○" },
        { word: "地誌", reading: "ちし", meaning: "geografi daerah, chorography", priority: "○" },
        { word: "誌友", reading: "しゆう", meaning: "teman sesama pembaca majalah", priority: "○" },
      ],
      family: "雑誌・週刊誌・月刊誌 → jenis-jenis penerbitan berkala. 日誌・誌面・誌上 → aspek-aspek dalam sebuah jurnal/majalah.",
      onyomi_pattern: "シ: 雑誌(し)、日誌(し)、週刊誌(し)。 100% sebagai シ.",
      quiz: [
        { type: "baca", question: "雑誌", answer: "ざっし", hint: "majalah" },
        { type: "arti", question: "日誌", answer: "jurnal harian, log harian", hint: "日=hari" },
        { type: "kanji", question: "しゅうかんし (majalah mingguan)", answer: "週刊誌", hint: "週=minggu、刊=penerbitan" },
        { type: "baca", question: "月刊誌", answer: "げっかんし", hint: "terbit setiap bulan" },
        { type: "arti", question: "機関誌", answer: "jurnal lembaga/organisasi", hint: "機関=lembaga/mesin" },
      ]
    },
    {
      kanji: "夢",
      meaning_core: ["mimpi", "impian", "harapan"],
      onyomi: "ム",
      kunyomi: "ゆめ",
      jukugo: [
        { word: "夢", reading: "ゆめ", meaning: "mimpi, impian", priority: "🔥" },
        { word: "夢中", reading: "むちゅう", meaning: "tergila-gila, sangat asyik", priority: "🔥" },
        { word: "夢想", reading: "むそう", meaning: "melamun, angan-angan", priority: "🔥" },
        { word: "悪夢", reading: "あくむ", meaning: "mimpi buruk, mimpi mengerikan", priority: "🔥" },
        { word: "白昼夢", reading: "はくちゅうむ", meaning: "melamun di siang hari, angan-angan", priority: "⭐" },
        { word: "夢見る", reading: "ゆめみる", meaning: "bermimpi", priority: "🔥" },
        { word: "正夢", reading: "まさゆめ", meaning: "mimpi yang menjadi kenyataan", priority: "⭐" },
        { word: "逆夢", reading: "さかゆめ", meaning: "mimpi yang berlawanan dengan kenyataan", priority: "○" },
        { word: "夢物語", reading: "ゆめものがたり", meaning: "cerita mimpi, dongeng", priority: "⭐" },
        { word: "夢幻", reading: "むげん", meaning: "ilusi, angan-angan", priority: "⭐" },
        { word: "初夢", reading: "はつゆめ", meaning: "mimpi pertama tahun baru", priority: "⭐" },
        { word: "夢路", reading: "ゆめじ", meaning: "jalan mimpi, dunia mimpi", priority: "○" },
      ],
      family: "夢中・夢想・夢幻・白昼夢 → semua berkaitan dengan keadaan tidak sadar/angan-angan. 悪夢・正夢・逆夢・初夢 → jenis-jenis mimpi.",
      onyomi_pattern: "ム: 夢中(む)、夢想(む)、悪夢(む)、夢幻(む). Kunyomi ゆめ berdiri sendiri atau sebagai awalan.",
      quiz: [
        { type: "baca", question: "夢中", answer: "むちゅう", hint: "tergila-gila" },
        { type: "arti", question: "悪夢", answer: "mimpi buruk", hint: "悪=buruk/jahat" },
        { type: "kanji", question: "あくむ (mimpi buruk)", answer: "悪夢", hint: "悪=buruk" },
        { type: "baca", question: "正夢", answer: "まさゆめ", hint: "mimpi yang jadi kenyataan" },
        { type: "arti", question: "夢想", answer: "melamun, angan-angan", hint: "想=pikiran/bayangan" },
      ]
    },
    {
      kanji: "静",
      meaning_core: ["tenang", "diam", "sunyi", "hening"],
      onyomi: "セイ、ジョウ",
      kunyomi: "しず(か)、しず(まる)",
      jukugo: [
        { word: "静か", reading: "しずか", meaning: "tenang, sunyi", priority: "🔥" },
        { word: "静止", reading: "せいし", meaning: "berhenti total, statis", priority: "🔥" },
        { word: "平静", reading: "へいせい", meaning: "tenang, kalem, tidak panik", priority: "🔥" },
        { word: "静寂", reading: "せいじゃく", meaning: "keheningan, kesunyian", priority: "🔥" },
        { word: "沈静", reading: "ちんせい", meaning: "tenang, mereda (setelah gejolak)", priority: "🔥" },
        { word: "静脈", reading: "じょうみゃく", meaning: "vena (pembuluh darah balik)", priority: "🔥" },
        { word: "静電気", reading: "せいでんき", meaning: "listrik statis", priority: "🔥" },
        { word: "安静", reading: "あんせい", meaning: "istirahat (medis)", priority: "🔥" },
        { word: "冷静", reading: "れいせい", meaning: "tenang, tidak emosional", priority: "🔥" },
        { word: "静養", reading: "せいよう", meaning: "beristirahat untuk pemulihan", priority: "⭐" },
        { word: "閑静", reading: "かんせい", meaning: "tenang dan sepi (lingkungan)", priority: "⭐" },
        { word: "静観", reading: "せいかん", meaning: "mengamati dengan tenang, tidak ikut campur", priority: "⭐" },
        { word: "動静", reading: "どうせい", meaning: "gerak-gerik, tanda-tanda pergerakan", priority: "⭐" },
        { word: "鎮静", reading: "ちんせい", meaning: "menenangkan, meredakan", priority: "⭐" },
      ],
      family: "冷静・平静・安静 → keadaan jiwa/tubuh yang tenang. 静寂・静止・閑静 → keadaan fisik yang sunyi/diam.",
      onyomi_pattern: "セイ: 静止(せい)、静寂(せい)、冷静(せい)。 ジョウ: 静脈(じょう)。 Dominan セイ (~85%).",
      quiz: [
        { type: "baca", question: "冷静", answer: "れいせい", hint: "tenang, tidak emosional" },
        { type: "arti", question: "静脈", answer: "vena, pembuluh darah balik", hint: "脈=nadi/pembuluh" },
        { type: "kanji", question: "あんせい (istirahat medis)", answer: "安静", hint: "安=aman/nyaman" },
        { type: "baca", question: "沈静", answer: "ちんせい", hint: "mereda" },
        { type: "arti", question: "静電気", answer: "listrik statis", hint: "電気=listrik" },
      ]
    },
    {
      kanji: "閉",
      meaning_core: ["tutup", "menutup", "tertutup"],
      onyomi: "ヘイ",
      kunyomi: "し(まる)、と(じる)、と(ざす)、し(める)",
      jukugo: [
        { word: "閉める", reading: "しめる", meaning: "menutup (pintu, jendela)", priority: "🔥" },
        { word: "閉まる", reading: "しまる", meaning: "tertutup (intransitif)", priority: "🔥" },
        { word: "閉店", reading: "へいてん", meaning: "tutup toko/restoran", priority: "🔥" },
        { word: "閉館", reading: "へいかん", meaning: "tutup (gedung, museum)", priority: "🔥" },
        { word: "閉会", reading: "へいかい", meaning: "penutupan acara/sidang", priority: "🔥" },
        { word: "閉幕", reading: "へいまく", meaning: "turunnya tirai, penutupan acara", priority: "⭐" },
        { word: "閉口", reading: "へいこう", meaning: "tidak bisa berkata-kata, kewalahan", priority: "⭐" },
        { word: "閉鎖", reading: "へいさ", meaning: "penutupan permanen, shutdown", priority: "🔥" },
        { word: "閉塞", reading: "へいそく", meaning: "tersumbat, kebuntuan", priority: "⭐" },
        { word: "閉じ込める", reading: "とじこめる", meaning: "mengurung, mengunci di dalam", priority: "🔥" },
        { word: "密閉", reading: "みっぺい", meaning: "penyegelan rapat, kedap udara", priority: "🔥" },
        { word: "開閉", reading: "かいへい", meaning: "buka-tutup", priority: "🔥" },
        { word: "閉幕式", reading: "へいまくしき", meaning: "upacara penutupan", priority: "⭐" },
        { word: "閉場", reading: "へいじょう", meaning: "penutupan (tempat/venue)", priority: "⭐" },
      ],
      family: "閉店・閉館・閉幕・閉会 → penutupan berbagai tempat/acara. 閉鎖・閉塞・密閉 → penutupan yang total/rapat.",
      onyomi_pattern: "ヘイ: 閉店(へい)、閉館(へい)、閉会(へい)、閉鎖(へい)。 ~90% sebagai ヘイ.",
      quiz: [
        { type: "baca", question: "閉店", answer: "へいてん", hint: "toko sudah tutup" },
        { type: "arti", question: "閉鎖", answer: "penutupan permanen, shutdown", hint: "鎖=rantai/kunci" },
        { type: "kanji", question: "みっぺい (kedap udara)", answer: "密閉", hint: "密=rapat/rahasia" },
        { type: "baca", question: "開閉", answer: "かいへい", hint: "buka-tutup" },
        { type: "arti", question: "閉塞", answer: "tersumbat, kebuntuan", hint: "塞=sumbat" },
      ]
    },
    {
      kanji: "想",
      meaning_core: ["pikir", "bayangkan", "ide", "gagasan", "nostalgia"],
      onyomi: "ソウ、ソ",
      kunyomi: "おも(う)",
      jukugo: [
        { word: "思想", reading: "しそう", meaning: "pemikiran, ideologi", priority: "🔥" },
        { word: "想像", reading: "そうぞう", meaning: "imajinasi, membayangkan", priority: "🔥" },
        { word: "感想", reading: "かんそう", meaning: "kesan, perasaan, tanggapan", priority: "🔥" },
        { word: "予想", reading: "よそう", meaning: "perkiraan, prediksi", priority: "🔥" },
        { word: "回想", reading: "かいそう", meaning: "mengenang, kilas balik", priority: "🔥" },
        { word: "空想", reading: "くうそう", meaning: "khayalan, fantasi", priority: "🔥" },
        { word: "発想", reading: "はっそう", meaning: "ide, gagasan", priority: "🔥" },
        { word: "連想", reading: "れんそう", meaning: "asosiasi (pikiran)", priority: "🔥" },
        { word: "夢想", reading: "むそう", meaning: "melamun, angan-angan", priority: "⭐" },
        { word: "想定", reading: "そうてい", meaning: "asumsi, skenario yang diasumsikan", priority: "🔥" },
        { word: "理想", reading: "りそう", meaning: "ideal, cita-cita", priority: "🔥" },
        { word: "瞑想", reading: "めいそう", meaning: "meditasi", priority: "⭐" },
        { word: "想起", reading: "そうき", meaning: "mengingat kembali", priority: "⭐" },
        { word: "妄想", reading: "もうそう", meaning: "delusi, khayalan gila", priority: "⭐" },
        { word: "幻想", reading: "げんそう", meaning: "ilusi, fantasi", priority: "🔥" },
        { word: "構想", reading: "こうそう", meaning: "konsep, rencana besar", priority: "🔥" },
      ],
      family: "想像・空想・夢想・幻想・妄想 → berbagai bentuk 'pikiran imajinatif'. 感想・回想・想起 → pikiran tentang masa lalu. 思想・理想・構想 → pemikiran terstruktur/abstrak.",
      onyomi_pattern: "ソウ: 思想(そう)、想像(そう)、感想(そう)、予想(そう)。 ソ: 想い(おも) [kunyomi]. ~100% ソウ dalam jukugo.",
      quiz: [
        { type: "baca", question: "想像", answer: "そうぞう", hint: "imajinasi" },
        { type: "arti", question: "発想", answer: "ide, gagasan", hint: "発=keluar/muncul" },
        { type: "kanji", question: "よそう (prediksi)", answer: "予想", hint: "予=sebelumnya/prakiraan" },
        { type: "baca", question: "妄想", answer: "もうそう", hint: "delusi" },
        { type: "arti", question: "構想", answer: "konsep, rencana besar", hint: "構=membangun/membentuk" },
      ]
    },
    {
      kanji: "現",
      meaning_core: ["saat ini", "nyata", "muncul", "hadir"],
      onyomi: "ゲン",
      kunyomi: "あらわ(れる)、あらわ(す)",
      jukugo: [
        { word: "現在", reading: "げんざい", meaning: "saat ini, sekarang", priority: "🔥" },
        { word: "現実", reading: "げんじつ", meaning: "kenyataan, realita", priority: "🔥" },
        { word: "現代", reading: "げんだい", meaning: "zaman modern, era kini", priority: "🔥" },
        { word: "表現", reading: "ひょうげん", meaning: "ekspresi, ungkapan", priority: "🔥" },
        { word: "実現", reading: "じつげん", meaning: "terwujud, terlaksana", priority: "🔥" },
        { word: "現象", reading: "げんしょう", meaning: "fenomena, gejala", priority: "🔥" },
        { word: "現場", reading: "げんば", meaning: "TKP, lokasi kejadian, lapangan kerja", priority: "🔥" },
        { word: "現状", reading: "げんじょう", meaning: "kondisi saat ini, status quo", priority: "🔥" },
        { word: "現金", reading: "げんきん", meaning: "uang tunai", priority: "🔥" },
        { word: "出現", reading: "しゅつげん", meaning: "kemunculan, tampil", priority: "🔥" },
        { word: "再現", reading: "さいげん", meaning: "reproduksi, pemutaran ulang", priority: "🔥" },
        { word: "現行", reading: "げんこう", meaning: "berlaku saat ini, yang sedang berjalan", priority: "⭐" },
        { word: "現時点", reading: "げんじてん", meaning: "pada titik waktu ini", priority: "⭐" },
        { word: "発現", reading: "はつげん", meaning: "manifestasi, ekspresi (gen dll)", priority: "○" },
        { word: "体現", reading: "たいげん", meaning: "mewujudkan, menggambarkan", priority: "⭐" },
        { word: "現役", reading: "げんえき", meaning: "aktif (masih berdinas/bertugas)", priority: "🔥" },
      ],
      family: "現在・現代・現役 → menunjukkan waktu 'sekarang'. 現実・現象・現場 → sesuatu yang nyata/terjadi. 表現・実現・出現・再現 → proses 'kemunculan/perwujudan'.",
      onyomi_pattern: "ゲン: 現在(げん)、現実(げん)、表現(げん)。 ~100% sebagai ゲン.",
      quiz: [
        { type: "baca", question: "表現", answer: "ひょうげん", hint: "ekspresi" },
        { type: "arti", question: "現場", answer: "TKP, lokasi kejadian, lapangan", priority: "🔥", hint: "場=tempat" },
        { type: "kanji", question: "じつげん (terwujud)", answer: "実現", hint: "実=kenyataan" },
        { type: "baca", question: "現役", answer: "げんえき", hint: "masih aktif bertugas" },
        { type: "arti", question: "現状", answer: "kondisi saat ini, status quo", hint: "状=kondisi" },
      ]
    },
    {
      kanji: "在",
      meaning_core: ["ada", "berada", "keberadaan", "kehadiran"],
      onyomi: "ザイ",
      kunyomi: "あ(る)",
      jukugo: [
        { word: "存在", reading: "そんざい", meaning: "keberadaan, eksistensi", priority: "🔥" },
        { word: "在学", reading: "ざいがく", meaning: "masih bersekolah/kuliah", priority: "🔥" },
        { word: "在日", reading: "ざいにち", meaning: "berada di/tinggal di Jepang", priority: "🔥" },
        { word: "現在", reading: "げんざい", meaning: "saat ini, sekarang", priority: "🔥" },
        { word: "在宅", reading: "ざいたく", meaning: "berada di rumah, WFH", priority: "🔥" },
        { word: "在庫", reading: "ざいこ", meaning: "stok, persediaan barang", priority: "🔥" },
        { word: "不在", reading: "ふざい", meaning: "tidak hadir, absen", priority: "🔥" },
        { word: "在職", reading: "ざいしょく", meaning: "masih aktif bekerja", priority: "🔥" },
        { word: "在住", reading: "ざいじゅう", meaning: "berdomisili, tinggal di", priority: "🔥" },
        { word: "潜在", reading: "せんざい", meaning: "laten, terpendam", priority: "🔥" },
        { word: "実在", reading: "じつざい", meaning: "ada secara nyata, eksis sungguhan", priority: "⭐" },
        { word: "在籍", reading: "ざいせき", meaning: "terdaftar (sebagai anggota)", priority: "⭐" },
        { word: "偏在", reading: "へんざい", meaning: "ada di mana-mana secara tidak merata", priority: "○" },
        { word: "遍在", reading: "へんざい", meaning: "ada di mana-mana (merata)", priority: "○" },
        { word: "在来", reading: "ざいらい", meaning: "yang sudah ada sejak dulu, konvensional", priority: "⭐" },
      ],
      family: "存在・実在・潜在 → berbagai bentuk 'keberadaan'. 在学・在職・在住・在籍 → 'berada/terdaftar' di suatu tempat/institusi. 在庫・在宅 → 'keberadaan' barang/orang di suatu lokasi.",
      onyomi_pattern: "ザイ: 存在(ざい)、在庫(ざい)、不在(ざい)、在宅(ざい)。 ~100% sebagai ザイ.",
      quiz: [
        { type: "baca", question: "存在", answer: "そんざい", hint: "eksistensi" },
        { type: "arti", question: "在庫", answer: "stok, persediaan barang", hint: "庫=gudang" },
        { type: "kanji", question: "ふざい (tidak hadir)", answer: "不在", hint: "不=tidak" },
        { type: "baca", question: "潜在", answer: "せんざい", hint: "terpendam, laten" },
        { type: "arti", question: "在宅", answer: "berada di rumah, WFH", hint: "宅=rumah" },
      ]
    },
    {
      kanji: "解",
      meaning_core: ["memecahkan", "memahami", "melepaskan", "menyelesaikan"],
      onyomi: "カイ、ゲ",
      kunyomi: "と(く)、と(ける)、ほど(く)",
      jukugo: [
        { word: "解決", reading: "かいけつ", meaning: "penyelesaian, pemecahan masalah", priority: "🔥" },
        { word: "理解", reading: "りかい", meaning: "pemahaman, mengerti", priority: "🔥" },
        { word: "解説", reading: "かいせつ", meaning: "penjelasan, komentar", priority: "🔥" },
        { word: "解答", reading: "かいとう", meaning: "jawaban (untuk soal)", priority: "🔥" },
        { word: "解放", reading: "かいほう", meaning: "pembebasan, membebaskan", priority: "🔥" },
        { word: "分解", reading: "ぶんかい", meaning: "dekomposisi, penguraian", priority: "🔥" },
        { word: "解消", reading: "かいしょう", meaning: "penyelesaian, penghapusan", priority: "🔥" },
        { word: "解釈", reading: "かいしゃく", meaning: "penafsiran, interpretasi", priority: "🔥" },
        { word: "解散", reading: "かいさん", meaning: "pembubaran (grup/parlemen)", priority: "🔥" },
        { word: "解雇", reading: "かいこ", meaning: "pemecatan, PHK", priority: "🔥" },
        { word: "解析", reading: "かいせき", meaning: "analisis mendalam", priority: "⭐" },
        { word: "誤解", reading: "ごかい", meaning: "kesalahpahaman", priority: "🔥" },
        { word: "了解", reading: "りょうかい", meaning: "mengerti, siap (militer/formal)", priority: "🔥" },
        { word: "解剖", reading: "かいぼう", meaning: "autopsi, pembedahan", priority: "⭐" },
        { word: "解約", reading: "かいやく", meaning: "pembatalan kontrak", priority: "🔥" },
        { word: "瓦解", reading: "がかい", meaning: "runtuh, hancur total", priority: "○" },
      ],
      family: "理解・了解・誤解 → tentang 'pemahaman'. 解決・解消 → tentang 'penyelesaian'. 解放・解散・解雇・解約 → tentang 'pelepasan/pembubaran'.",
      onyomi_pattern: "カイ: 解決(かい)、理解(かい)、解放(かい)。 ゲ: 解毒(げ)。 Dominan カイ (~90%).",
      quiz: [
        { type: "baca", question: "理解", answer: "りかい", hint: "memahami" },
        { type: "arti", question: "誤解", answer: "kesalahpahaman", hint: "誤=salah/keliru" },
        { type: "kanji", question: "かいほう (membebaskan)", answer: "解放", hint: "放=melepaskan" },
        { type: "baca", question: "解雇", answer: "かいこ", hint: "pemecatan" },
        { type: "arti", question: "了解", answer: "mengerti, siap (formal)", hint: "了=selesai/menyelesaikan" },
      ]
    },
    {
      kanji: "決",
      meaning_core: ["memutuskan", "menentukan", "tetap"],
      onyomi: "ケツ",
      kunyomi: "き(める)、き(まる)",
      jukugo: [
        { word: "決める", reading: "きめる", meaning: "memutuskan, menentukan", priority: "🔥" },
        { word: "決まる", reading: "きまる", meaning: "diputuskan, sudah pasti", priority: "🔥" },
        { word: "解決", reading: "かいけつ", meaning: "penyelesaian masalah", priority: "🔥" },
        { word: "決定", reading: "けってい", meaning: "keputusan, penetapan", priority: "🔥" },
        { word: "決断", reading: "けつだん", meaning: "pengambilan keputusan tegas", priority: "🔥" },
        { word: "決心", reading: "けっしん", meaning: "tekad, keputusan bulat", priority: "🔥" },
        { word: "決勝", reading: "けっしょう", meaning: "babak final", priority: "🔥" },
        { word: "可決", reading: "かけつ", meaning: "disetujui (voting)", priority: "🔥" },
        { word: "否決", reading: "ひけつ", meaning: "ditolak (voting)", priority: "🔥" },
        { word: "決算", reading: "けっさん", meaning: "penutupan buku, rekening tahunan", priority: "⭐" },
        { word: "決議", reading: "けつぎ", meaning: "resolusi, keputusan rapat", priority: "⭐" },
        { word: "一決", reading: "いっけつ", meaning: "diputuskan bulat-bulat", priority: "○" },
        { word: "決意", reading: "けつい", meaning: "tekad, niat kuat", priority: "🔥" },
        { word: "判決", reading: "はんけつ", meaning: "vonis, putusan pengadilan", priority: "🔥" },
        { word: "自決", reading: "じけつ", meaning: "penentuan nasib sendiri", priority: "⭐" },
        { word: "多数決", reading: "たすうけつ", meaning: "keputusan mayoritas, suara terbanyak", priority: "🔥" },
      ],
      family: "決定・決断・決心・決意・決議 → berbagai nuansa 'membuat keputusan'. 可決・否決・多数決 → proses voting/pemungutan suara. 解決・判決 → penyelesaian melalui proses formal.",
      onyomi_pattern: "ケツ: 解決(けつ)、決定(けつ)、判決(けつ)。 ~100% sebagai ケツ.",
      quiz: [
        { type: "baca", question: "決断", answer: "けつだん", hint: "keputusan tegas" },
        { type: "arti", question: "判決", answer: "vonis, putusan pengadilan", hint: "判=hakim/penilaian" },
        { type: "kanji", question: "たすうけつ (suara terbanyak)", answer: "多数決", hint: "多=banyak、数=jumlah" },
        { type: "baca", question: "可決", answer: "かけつ", hint: "disetujui" },
        { type: "arti", question: "決意", answer: "tekad, niat kuat", hint: "意=pikiran/niat" },
      ]
    },
    {
      kanji: "怖",
      meaning_core: ["takut", "menakutkan", "ngeri"],
      onyomi: "フ",
      kunyomi: "こわ(い)、こわ(がる)",
      jukugo: [
        { word: "怖い", reading: "こわい", meaning: "menakutkan, seram", priority: "🔥" },
        { word: "恐怖", reading: "きょうふ", meaning: "ketakutan, rasa ngeri", priority: "🔥" },
        { word: "怖がる", reading: "こわがる", meaning: "merasa takut, ketakutan", priority: "🔥" },
        { word: "怖がり", reading: "こわがり", meaning: "penakut", priority: "⭐" },
        { word: "怖気", reading: "おじけ", meaning: "rasa takut, kecut hati", priority: "⭐" },
        { word: "怖れ", reading: "おそれ", meaning: "ketakutan, kekuatiran", priority: "⭐" },
        { word: "恐怖症", reading: "きょうふしょう", meaning: "fobia", priority: "🔥" },
        { word: "怖面", reading: "こわもて", meaning: "tampang seram, wajah menakutkan", priority: "○" },
        { word: "強面", reading: "こわもて", meaning: "tampang sangar", priority: "○" },
        { word: "怖じ気づく", reading: "おじけづく", meaning: "menjadi ciut/gentar", priority: "⭐" },
      ],
      family: "恐怖・怖れ・怖気 → ekspresi ketakutan dari ringan ke dalam. 恐怖症 → ketakutan klinis (fobia).",
      onyomi_pattern: "フ: 恐怖(ふ)。 Kebanyakan sebagai kunyomi こわい/こわがる dalam percakapan sehari-hari.",
      quiz: [
        { type: "baca", question: "恐怖", answer: "きょうふ", hint: "rasa ngeri" },
        { type: "arti", question: "恐怖症", answer: "fobia", hint: "症=penyakit/gejala" },
        { type: "kanji", question: "きょうふ (ketakutan)", answer: "恐怖", hint: "恐=mengerikan" },
        { type: "baca", question: "怖がり", answer: "こわがり", hint: "penakut" },
        { type: "arti", question: "怖気", answer: "rasa takut, kecut hati", hint: "気=perasaan/semangat" },
      ]
    },
    {
      kanji: "雷",
      meaning_core: ["petir", "guntur", "halilintar"],
      onyomi: "ライ",
      kunyomi: "かみなり",
      jukugo: [
        { word: "雷", reading: "かみなり", meaning: "petir, guntur", priority: "🔥" },
        { word: "雷雨", reading: "らいう", meaning: "hujan lebat disertai petir", priority: "🔥" },
        { word: "雷鳴", reading: "らいめい", meaning: "suara guntur/petir", priority: "🔥" },
        { word: "落雷", reading: "らくらい", meaning: "sambaran petir", priority: "🔥" },
        { word: "雷電", reading: "らいでん", meaning: "petir dan kilat", priority: "⭐" },
        { word: "地雷", reading: "じらい", meaning: "ranjau darat", priority: "🔥" },
        { word: "魚雷", reading: "ぎょらい", meaning: "torpedo", priority: "⭐" },
        { word: "機雷", reading: "きらい", meaning: "ranjau laut", priority: "⭐" },
        { word: "避雷針", reading: "ひらいしん", meaning: "penangkal petir", priority: "🔥" },
        { word: "雷同", reading: "らいどう", meaning: "ikut-ikutan (tanpa pertimbangan)", priority: "⭐" },
        { word: "雷名", reading: "らいめい", meaning: "reputasi/nama besar yang menggelegar", priority: "○" },
      ],
      family: "雷雨・雷鳴・落雷 → fenomena petir. 地雷・魚雷・機雷 → benda berbahaya yang 'meledak seperti petir'.",
      onyomi_pattern: "ライ: 雷雨(らい)、落雷(らい)、地雷(らい)。 Kunyomi かみなり digunakan saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "落雷", answer: "らくらい", hint: "sambaran petir" },
        { type: "arti", question: "地雷", answer: "ranjau darat", hint: "地=tanah" },
        { type: "kanji", question: "ひらいしん (penangkal petir)", answer: "避雷針", hint: "避=menghindari、針=jarum" },
        { type: "baca", question: "雷雨", answer: "らいう", hint: "hujan disertai petir" },
        { type: "arti", question: "雷同", answer: "ikut-ikutan tanpa pertimbangan", hint: "同=sama/setuju" },
      ]
    },
    {
      kanji: "笑",
      meaning_core: ["senyum", "tawa", "tertawa"],
      onyomi: "ショウ",
      kunyomi: "わら(う)、え(む)",
      jukugo: [
        { word: "笑う", reading: "わらう", meaning: "tertawa, tersenyum", priority: "🔥" },
        { word: "微笑む", reading: "ほほえむ", meaning: "tersenyum lembut", priority: "🔥" },
        { word: "笑顔", reading: "えがお", meaning: "wajah senyum, wajah gembira", priority: "🔥" },
        { word: "笑い", reading: "わらい", meaning: "tawa, candaan", priority: "🔥" },
        { word: "爆笑", reading: "ばくしょう", meaning: "tawa ngakak, tawa meledak-ledak", priority: "🔥" },
        { word: "苦笑", reading: "くしょう", meaning: "senyum pahit, senyum kecut", priority: "🔥" },
        { word: "失笑", reading: "しっしょう", meaning: "tawa yang tidak tertahan", priority: "⭐" },
        { word: "冷笑", reading: "れいしょう", meaning: "ejekan, senyum sinis", priority: "⭐" },
        { word: "嘲笑", reading: "ちょうしょう", meaning: "ejekan, tertawa mengolok", priority: "⭐" },
        { word: "談笑", reading: "だんしょう", meaning: "berbincang sambil tertawa", priority: "🔥" },
        { word: "微笑", reading: "びしょう", meaning: "senyuman lembut", priority: "🔥" },
        { word: "笑劇", reading: "しょうげき", meaning: "komedi, drama lucu", priority: "○" },
        { word: "笑い話", reading: "わらいばなし", meaning: "cerita lucu, lelucon", priority: "⭐" },
      ],
      family: "爆笑・苦笑・冷笑・嘲笑・失笑 → berbagai jenis tawa yang berbeda nuansanya. 微笑・笑顔・談笑 → tawa/senyum yang menyenangkan.",
      onyomi_pattern: "ショウ: 爆笑(しょう)、苦笑(しょう)、冷笑(しょう)、微笑(しょう)。 Kunyomi わら・え saat berdiri sendiri atau sebagai kata kerja.",
      quiz: [
        { type: "baca", question: "爆笑", answer: "ばくしょう", hint: "tawa meledak" },
        { type: "arti", question: "苦笑", answer: "senyum pahit/kecut", hint: "苦=pahit/susah" },
        { type: "kanji", question: "えがお (wajah senyum)", answer: "笑顔", hint: "顔=wajah" },
        { type: "baca", question: "談笑", answer: "だんしょう", hint: "ngobrol sambil tertawa" },
        { type: "arti", question: "冷笑", answer: "ejekan, senyum sinis", hint: "冷=dingin" },
      ]
    },
    {
      kanji: "甘",
      meaning_core: ["manis", "memanjakan", "lunak", "tidak ketat"],
      onyomi: "カン",
      kunyomi: "あま(い)、あま(える)、あま(やかす)",
      jukugo: [
        { word: "甘い", reading: "あまい", meaning: "manis; lemah/permisif", priority: "🔥" },
        { word: "甘える", reading: "あまえる", meaning: "manja, bergantung (secara emosional)", priority: "🔥" },
        { word: "甘やかす", reading: "あまやかす", meaning: "memanjakan", priority: "🔥" },
        { word: "甘味", reading: "かんみ / あまみ", meaning: "rasa manis; makanan manis", priority: "🔥" },
        { word: "甘党", reading: "あまとう", meaning: "penggemar makanan manis", priority: "⭐" },
        { word: "甘口", reading: "あまくち", meaning: "rasa manis (sake/kari); tidak pedas", priority: "🔥" },
        { word: "甘酸っぱい", reading: "あまずっぱい", meaning: "asam manis, rasa nostalgia", priority: "⭐" },
        { word: "甘えん坊", reading: "あまえんぼう", meaning: "anak manja", priority: "⭐" },
        { word: "甘言", reading: "かんげん", meaning: "kata-kata manis (menipu)", priority: "⭐" },
        { word: "甘受", reading: "かんじゅ", meaning: "menerima dengan pasrah", priority: "⭐" },
        { word: "甘美", reading: "かんび", meaning: "indah dan menyenangkan", priority: "○" },
        { word: "甘栗", reading: "あまぐり", meaning: "kacang manis yang dipanggang", priority: "○" },
      ],
      family: "甘える・甘やかす・甘えん坊 → berkaitan dengan 'ketergantungan/memanjakan'. 甘口・甘味・甘い → rasa dan kesukaan akan sesuatu yang manis.",
      onyomi_pattern: "カン: 甘味(かん)、甘言(かん)、甘受(かん)。 Kebanyakan digunakan sebagai kunyomi あまい/あまえる dalam percakapan.",
      quiz: [
        { type: "baca", question: "甘える", answer: "あまえる", hint: "manja secara emosional" },
        { type: "arti", question: "甘口", answer: "rasa manis; tidak pedas", hint: "口=mulut/rasa" },
        { type: "kanji", question: "かんみ (rasa manis)", answer: "甘味", hint: "味=rasa" },
        { type: "baca", question: "甘言", answer: "かんげん", hint: "kata-kata manis yang menipu" },
        { type: "arti", question: "甘受", answer: "menerima dengan pasrah", hint: "受=menerima" },
      ]
    },
    {
      kanji: "丸",
      meaning_core: ["bulat", "lingkaran", "peluru", "utuh"],
      onyomi: "ガン",
      kunyomi: "まる(い)、まる",
      jukugo: [
        { word: "丸い", reading: "まるい", meaning: "bulat, bundar", priority: "🔥" },
        { word: "丸ごと", reading: "まるごと", meaning: "seluruhnya, utuh-utuh", priority: "🔥" },
        { word: "弾丸", reading: "だんがん", meaning: "peluru", priority: "🔥" },
        { word: "丸薬", reading: "がんやく", meaning: "pil, obat bulat", priority: "🔥" },
        { word: "丸暗記", reading: "まるあんき", meaning: "hafalan bulat (tanpa pemahaman)", priority: "🔥" },
        { word: "丸ノコ", reading: "まるのこ", meaning: "gergaji bundar", priority: "○" },
        { word: "丸顔", reading: "まるがお", meaning: "wajah bulat", priority: "⭐" },
        { word: "丸投げ", reading: "まるなげ", meaning: "melempar tanggung jawab sepenuhnya", priority: "🔥" },
        { word: "日の丸", reading: "ひのまる", meaning: "bendera Jepang (lingkaran matahari)", priority: "🔥" },
        { word: "丸め込む", reading: "まるめこむ", meaning: "merayu, membujuk", priority: "⭐" },
        { word: "手裏剣丸", reading: "-", meaning: "(nama kapal Jepang termasuk 丸)", priority: "○" },
        { word: "砲丸", reading: "ほうがん", meaning: "peluru meriam; tolak peluru (olahraga)", priority: "⭐" },
      ],
      family: "弾丸・丸薬・砲丸 → benda berbentuk bulat. 丸ごと・丸暗記・丸投げ → nuansa 'keseluruhan/sepenuhnya'.",
      onyomi_pattern: "ガン: 弾丸(がん)、丸薬(がん)、砲丸(がん)。 Kunyomi まる/まるい dominan dalam percakapan sehari-hari.",
      quiz: [
        { type: "baca", question: "弾丸", answer: "だんがん", hint: "peluru" },
        { type: "arti", question: "丸暗記", answer: "hafalan bulat tanpa pemahaman", hint: "暗記=menghafal" },
        { type: "kanji", question: "まるごと (seluruhnya/utuh)", answer: "丸ごと", hint: "ごと=semuanya" },
        { type: "baca", question: "日の丸", answer: "ひのまる", hint: "bendera Jepang" },
        { type: "arti", question: "丸投げ", answer: "melempar tanggung jawab sepenuhnya", hint: "投げ=melempar" },
      ]
    },
    {
      kanji: "当",
      meaning_core: ["mengenai", "tepat", "bertanggung jawab", "gilirannya"],
      onyomi: "トウ",
      kunyomi: "あ(たる)、あ(てる)、まさ(に)",
      jukugo: [
        { word: "当然", reading: "とうぜん", meaning: "tentu saja, sudah semestinya", priority: "🔥" },
        { word: "当日", reading: "とうじつ", meaning: "hari itu sendiri, pada hari H", priority: "🔥" },
        { word: "当時", reading: "とうじ", meaning: "pada waktu itu, kala itu", priority: "🔥" },
        { word: "担当", reading: "たんとう", meaning: "bertanggung jawab, yang bertugas", priority: "🔥" },
        { word: "適当", reading: "てきとう", meaning: "cocok, layak; seadanya (negatif)", priority: "🔥" },
        { word: "当選", reading: "とうせん", meaning: "terpilih, menang (lottery/pemilu)", priority: "🔥" },
        { word: "本当", reading: "ほんとう", meaning: "sungguh, benar-benar", priority: "🔥" },
        { word: "相当", reading: "そうとう", meaning: "setara, cukup besar, lumayan", priority: "🔥" },
        { word: "当番", reading: "とうばん", meaning: "giliran bertugas, piket", priority: "🔥" },
        { word: "当初", reading: "とうしょ", meaning: "pada awalnya, pada mulanya", priority: "🔥" },
        { word: "当局", reading: "とうきょく", meaning: "pihak berwenang/otoritas", priority: "🔥" },
        { word: "妥当", reading: "だとう", meaning: "wajar, masuk akal, valid", priority: "🔥" },
        { word: "正当", reading: "せいとう", meaning: "sah, legitimate, benar", priority: "🔥" },
        { word: "不当", reading: "ふとう", meaning: "tidak wajar, tidak sah", priority: "🔥" },
        { word: "当たり前", reading: "あたりまえ", meaning: "sudah sewajarnya, hal biasa", priority: "🔥" },
        { word: "見当", reading: "けんとう", meaning: "perkiraan, taksiran", priority: "🔥" },
      ],
      family: "当然・当たり前・妥当・正当 → menilai sesuatu sebagai 'pantas/semestinya'. 担当・当番 → tanggung jawab dan giliran. 当日・当時・当初 → menunjukkan waktu tertentu.",
      onyomi_pattern: "トウ: 当然(とう)、担当(とう)、適当(とう)、本当(とう)。 ~100% sebagai トウ.",
      quiz: [
        { type: "baca", question: "担当", answer: "たんとう", hint: "orang yang bertanggung jawab" },
        { type: "arti", question: "当然", answer: "tentu saja, sudah semestinya", hint: "然=begitu/memang" },
        { type: "kanji", question: "てきとう (cocok/seadanya)", answer: "適当", hint: "適=sesuai" },
        { type: "baca", question: "妥当", answer: "だとう", hint: "wajar, valid" },
        { type: "arti", question: "当局", answer: "pihak berwenang/otoritas", hint: "局=kantor/otoritas" },
      ]
    },
    {
      kanji: "信",
      meaning_core: ["percaya", "kepercayaan", "mengirimkan pesan"],
      onyomi: "シン",
      kunyomi: "-",
      jukugo: [
        { word: "信じる", reading: "しんじる", meaning: "mempercayai", priority: "🔥" },
        { word: "信頼", reading: "しんらい", meaning: "kepercayaan, andalan", priority: "🔥" },
        { word: "信用", reading: "しんよう", meaning: "kepercayaan, kredit", priority: "🔥" },
        { word: "自信", reading: "じしん", meaning: "kepercayaan diri", priority: "🔥" },
        { word: "確信", reading: "かくしん", meaning: "keyakinan, kepastian", priority: "🔥" },
        { word: "信念", reading: "しんねん", meaning: "keyakinan, prinsip", priority: "🔥" },
        { word: "迷信", reading: "めいしん", meaning: "takhayul", priority: "🔥" },
        { word: "不信", reading: "ふしん", meaning: "ketidakpercayaan, curiga", priority: "🔥" },
        { word: "信号", reading: "しんごう", meaning: "lampu lalu lintas, sinyal", priority: "🔥" },
        { word: "通信", reading: "つうしん", meaning: "komunikasi, telekomunikasi", priority: "🔥" },
        { word: "発信", reading: "はっしん", meaning: "mengirim pesan, transmisi", priority: "🔥" },
        { word: "受信", reading: "じゅしん", meaning: "menerima pesan/sinyal", priority: "🔥" },
        { word: "信仰", reading: "しんこう", meaning: "keyakinan agama, iman", priority: "🔥" },
        { word: "信条", reading: "しんじょう", meaning: "prinsip, doktrin", priority: "⭐" },
        { word: "音信", reading: "おとずれ/おんしん", meaning: "kabar, berita dari seseorang", priority: "⭐" },
        { word: "返信", reading: "へんしん", meaning: "membalas pesan/surat", priority: "🔥" },
      ],
      family: "信頼・信用・確信・自信 → berbagai bentuk 'kepercayaan'. 通信・発信・受信・返信 → aktivitas 'komunikasi/pesan'. 信仰・信念・信条 → kepercayaan yang lebih dalam (spiritual/prinsip).",
      onyomi_pattern: "シン: 信頼(しん)、自信(しん)、通信(しん)。 ~100% sebagai シン.",
      quiz: [
        { type: "baca", question: "確信", answer: "かくしん", hint: "keyakinan" },
        { type: "arti", question: "迷信", answer: "takhayul", hint: "迷=tersesat/bingung" },
        { type: "kanji", question: "じしん (percaya diri)", answer: "自信", hint: "自=diri sendiri" },
        { type: "baca", question: "通信", answer: "つうしん", hint: "telekomunikasi" },
        { type: "arti", question: "発信", answer: "mengirim pesan, transmisi", hint: "発=mengeluarkan" },
      ]
    },
    {
      kanji: "震",
      meaning_core: ["gemetar", "gempa", "bergetar"],
      onyomi: "シン",
      kunyomi: "ふる(える)、ふる(う)",
      jukugo: [
        { word: "地震", reading: "じしん", meaning: "gempa bumi", priority: "🔥" },
        { word: "震える", reading: "ふるえる", meaning: "gemetar, bergetar", priority: "🔥" },
        { word: "震度", reading: "しんど", meaning: "skala intensitas gempa (Jepang)", priority: "🔥" },
        { word: "震源", reading: "しんげん", meaning: "pusat gempa, hiposenter", priority: "🔥" },
        { word: "余震", reading: "よしん", meaning: "gempa susulan", priority: "🔥" },
        { word: "震災", reading: "しんさい", meaning: "bencana gempa bumi", priority: "🔥" },
        { word: "微震", reading: "びしん", meaning: "gempa kecil/lemah", priority: "⭐" },
        { word: "大震災", reading: "だいしんさい", meaning: "bencana gempa besar", priority: "🔥" },
        { word: "震脚", reading: "しんきゃく", meaning: "hentakan kaki dalam bela diri", priority: "○" },
        { word: "激震", reading: "げきしん", meaning: "gempa dahsyat; guncangan besar", priority: "⭐" },
        { word: "震撼", reading: "しんかん", meaning: "mengguncang, mengejutkan (figuratif)", priority: "⭐" },
        { word: "身震い", reading: "みぶるい", meaning: "badan menggigil, merinding", priority: "🔥" },
      ],
      family: "地震・震災・大震災・余震 → berbagai aspek bencana gempa. 震度・震源・激震 → pengukuran dan intensitas gempa. 震える・身震い → perasaan 'gemetar'.",
      onyomi_pattern: "シン: 地震(しん)、震度(しん)、余震(しん)。 Kunyomi ふるえる untuk kata kerja.",
      quiz: [
        { type: "baca", question: "地震", answer: "じしん", hint: "gempa bumi" },
        { type: "arti", question: "余震", answer: "gempa susulan", hint: "余=sisa/tambahan" },
        { type: "kanji", question: "しんど (skala gempa)", answer: "震度", hint: "度=derajat/tingkat" },
        { type: "baca", question: "震災", answer: "しんさい", hint: "bencana gempa" },
        { type: "arti", question: "身震い", answer: "badan menggigil, merinding", hint: "身=tubuh" },
      ]
    },
  ]
};
