
// ========== PERTEMUAN 7 ==========
const pertemuan7 = {
  id: 7,
  title: "Pertemuan 7",
  kanji: [
    {
      kanji: "助",
      meaning_core: ["tolong", "bantuan", "menyelamatkan"],
      onyomi: "ジョ",
      kunyomi: "たす(ける)、たす(かる)、すけ",
      jukugo: [
        { word: "助ける", reading: "たすける", meaning: "menolong, menyelamatkan", priority: "🔥" },
        { word: "助かる", reading: "たすかる", meaning: "tertolong, diselamatkan", priority: "🔥" },
        { word: "助言", reading: "じょげん", meaning: "saran, masukan", priority: "🔥" },
        { word: "助力", reading: "じょりょく", meaning: "bantuan, pertolongan", priority: "⭐" },
        { word: "援助", reading: "えんじょ", meaning: "bantuan, dukungan", priority: "🔥" },
        { word: "補助", reading: "ほじょ", meaning: "subsidi, bantuan pelengkap", priority: "🔥" },
        { word: "救助", reading: "きゅうじょ", meaning: "penyelamatan", priority: "🔥" },
        { word: "助手", reading: "じょしゅ", meaning: "asisten", priority: "🔥" },
        { word: "助詞", reading: "じょし", meaning: "partikel (tata bahasa)", priority: "🔥" },
        { word: "助動詞", reading: "じょどうし", meaning: "kata kerja bantu", priority: "🔥" },
        { word: "自助", reading: "じじょ", meaning: "menolong diri sendiri, swadaya", priority: "⭐" },
        { word: "相互扶助", reading: "そうごふじょ", meaning: "saling bantu, gotong royong", priority: "⭐" },
        { word: "助成", reading: "じょせい", meaning: "subsidi, hibah", priority: "⭐" },
      ],
      family: "援助・補助・救助・自助 → berbagai bentuk 'bantuan/pertolongan'. 助詞・助動詞・助手 → fungsi 'pembantu/pendukung' dalam bahasa/pekerjaan.",
      onyomi_pattern: "ジョ: 援助(じょ)、補助(じょ)、助手(じょ)。 ~100% sebagai ジョ.",
      quiz: [
        { type: "baca", question: "援助", answer: "えんじょ", hint: "bantuan" },
        { type: "arti", question: "助詞", answer: "partikel (tata bahasa)", hint: "詞=kata" },
        { type: "kanji", question: "きゅうじょ (penyelamatan)", answer: "救助", hint: "救=menyelamatkan" },
        { type: "baca", question: "補助", answer: "ほじょ", hint: "subsidi" },
        { type: "arti", question: "助手", answer: "asisten", hint: "手=tangan/orang yang membantu" },
      ]
    },
    {
      kanji: "次",
      meaning_core: ["berikutnya", "urutan", "selanjutnya"],
      onyomi: "ジ、シ",
      kunyomi: "つ(ぐ)、つぎ",
      jukugo: [
        { word: "次", reading: "つぎ", meaning: "berikutnya, selanjutnya", priority: "🔥" },
        { word: "次第", reading: "しだい", meaning: "tergantung pada; segera setelah", priority: "🔥" },
        { word: "目次", reading: "もくじ", meaning: "daftar isi", priority: "🔥" },
        { word: "次元", reading: "じげん", meaning: "dimensi", priority: "🔥" },
        { word: "次回", reading: "じかい", meaning: "sesi/kali berikutnya", priority: "🔥" },
        { word: "次世代", reading: "じせだい", meaning: "generasi berikutnya", priority: "🔥" },
        { word: "順次", reading: "じゅんじ", meaning: "secara berurutan", priority: "🔥" },
        { word: "次第に", reading: "しだいに", meaning: "secara bertahap, perlahan-lahan", priority: "🔥" },
        { word: "次男", reading: "じなん", meaning: "anak laki-laki kedua", priority: "⭐" },
        { word: "次女", reading: "じじょ", meaning: "anak perempuan kedua", priority: "⭐" },
        { word: "年次", reading: "ねんじ", meaning: "tahunan, per tahun", priority: "⭐" },
        { word: "次点", reading: "じてん", meaning: "runner-up, peringkat kedua", priority: "⭐" },
        { word: "逐次", reading: "ちくじ", meaning: "satu per satu, berurutan", priority: "○" },
      ],
      family: "次回・次世代・次男・次女 → 'yang berikutnya' dalam urutan. 目次・順次・逐次 → urutan dan pengaturan. 次第・次第に → 'bergantung pada' dan 'secara bertahap'.",
      onyomi_pattern: "ジ: 次元(じ)、次回(じ)、目次(じ)。 シ: 次第(し)。 Dominan ジ (~80%).",
      quiz: [
        { type: "baca", question: "目次", answer: "もくじ", hint: "daftar isi buku" },
        { type: "arti", question: "次第に", answer: "secara bertahap, perlahan-lahan", hint: "徐々に的な" },
        { type: "kanji", question: "じせだい (generasi berikutnya)", answer: "次世代", hint: "世代=generasi" },
        { type: "baca", question: "順次", answer: "じゅんじ", hint: "secara berurutan" },
        { type: "arti", question: "次元", answer: "dimensi", hint: "元=asal/dasar" },
      ]
    },
    {
      kanji: "消",
      meaning_core: ["hilang", "padam", "menghapus", "habis"],
      onyomi: "ショウ",
      kunyomi: "き(える)、け(す)",
      jukugo: [
        { word: "消える", reading: "きえる", meaning: "hilang, padam", priority: "🔥" },
        { word: "消す", reading: "けす", meaning: "memadamkan, menghapus", priority: "🔥" },
        { word: "消費", reading: "しょうひ", meaning: "konsumsi, pengeluaran", priority: "🔥" },
        { word: "消防", reading: "しょうぼう", meaning: "pemadam kebakaran", priority: "🔥" },
        { word: "消化", reading: "しょうか", meaning: "pencernaan; pemrosesan", priority: "🔥" },
        { word: "解消", reading: "かいしょう", meaning: "penyelesaian, penghapusan", priority: "🔥" },
        { word: "消滅", reading: "しょうめつ", meaning: "pemusnahan, lenyap sepenuhnya", priority: "🔥" },
        { word: "消極的", reading: "しょうきょくてき", meaning: "pasif, negatif (sikap)", priority: "🔥" },
        { word: "取り消す", reading: "とりけす", meaning: "membatalkan, menarik kembali", priority: "🔥" },
        { word: "消灯", reading: "しょうとう", meaning: "mematikan lampu", priority: "⭐" },
        { word: "消耗", reading: "しょうもう", meaning: "kelelahan, pengurasan energi", priority: "🔥" },
        { word: "消去", reading: "しょうきょ", meaning: "penghapusan, eliminasi", priority: "🔥" },
        { word: "消息", reading: "しょうそく", meaning: "berita/kabar tentang seseorang", priority: "🔥" },
        { word: "消臭", reading: "しょうしゅう", meaning: "penghilang bau", priority: "⭐" },
        { word: "撃墜消滅", reading: "-", meaning: "-- (gaya hidup minimalis terkait)", priority: "○" },
      ],
      family: "消費・消耗 → 'penggunaan/habisnya sesuatu'. 消滅・消去・解消 → 'menghilangkan/menghapus'. 消防・消化・消毒 → 'menetralisir sesuatu berbahaya'.",
      onyomi_pattern: "ショウ: 消費(しょう)、消防(しょう)、消滅(しょう)。 ~100% sebagai ショウ.",
      quiz: [
        { type: "baca", question: "消費", answer: "しょうひ", hint: "konsumsi" },
        { type: "arti", question: "消息", answer: "berita/kabar tentang seseorang", hint: "息=napas/berita" },
        { type: "kanji", question: "しょうぼう (pemadam kebakaran)", answer: "消防", hint: "防=mencegah/bertahan" },
        { type: "baca", question: "消耗", answer: "しょうもう", hint: "kelelahan, terkuras" },
        { type: "arti", question: "消極的", answer: "pasif, negatif (sikap)", hint: "極=ekstrem、的=sifat" },
      ]
    },
    {
      kanji: "濃",
      meaning_core: ["pekat", "kental", "gelap (warna)", "padat"],
      onyomi: "ノウ",
      kunyomi: "こ(い)",
      jukugo: [
        { word: "濃い", reading: "こい", meaning: "pekat, kental, gelap (warna)", priority: "🔥" },
        { word: "濃度", reading: "のうど", meaning: "konsentrasi, kepekatan", priority: "🔥" },
        { word: "濃縮", reading: "のうしゅく", meaning: "pemekatan, konsentrasi (proses)", priority: "🔥" },
        { word: "濃厚", reading: "のうこう", meaning: "kaya rasa/pekat; sangat kuat (nuansa)", priority: "🔥" },
        { word: "濃淡", reading: "のうたん", meaning: "gelap-terang, pekat-tipis", priority: "⭐" },
        { word: "希薄/濃薄", reading: "きはく", meaning: "encer, tipis (lawan dari 濃)", priority: "⭐" },
        { word: "色濃い", reading: "いろこい", meaning: "warna pekat; terasa kuat", priority: "⭐" },
        { word: "濃霧", reading: "のうむ", meaning: "kabut tebal", priority: "🔥" },
        { word: "濃緑", reading: "こみどり", meaning: "hijau tua/pekat", priority: "⭐" },
        { word: "血が濃い", reading: "ちがこい", meaning: "darah kental (hubungan dekat)", priority: "⭐" },
      ],
      family: "濃度・濃縮・濃厚 → berkaitan dengan 'kepekatan/kekentalan'. 濃霧・濃緑・色濃い → 'pekat' dalam konteks visual/alam.",
      onyomi_pattern: "ノウ: 濃度(のう)、濃縮(のう)、濃厚(のう)。 Kunyomi こい saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "濃度", answer: "のうど", hint: "konsentrasi" },
        { type: "arti", question: "濃霧", answer: "kabut tebal", hint: "霧=kabut" },
        { type: "kanji", question: "のうこう (pekat, kaya rasa)", answer: "濃厚", hint: "厚=tebal" },
        { type: "baca", question: "濃縮", answer: "のうしゅく", hint: "pemekatan" },
        { type: "arti", question: "濃淡", answer: "gelap-terang, pekat-tipis", hint: "淡=tipis/pudar" },
      ]
    },
    {
      kanji: "際",
      meaning_core: ["saat", "pada waktu", "tepi", "batas"],
      onyomi: "サイ",
      kunyomi: "きわ",
      jukugo: [
        { word: "際", reading: "きわ", meaning: "tepi, tepian, batas", priority: "🔥" },
        { word: "際に", reading: "さいに", meaning: "pada saat, pada waktu (formal)", priority: "🔥" },
        { word: "国際", reading: "こくさい", meaning: "internasional", priority: "🔥" },
        { word: "実際", reading: "じっさい", meaning: "pada kenyataannya, sebenarnya", priority: "🔥" },
        { word: "交際", reading: "こうさい", meaning: "hubungan sosial; berpacaran", priority: "🔥" },
        { word: "際立つ", reading: "きわだつ", meaning: "menonjol, mencolok", priority: "🔥" },
        { word: "際限", reading: "さいげん", meaning: "batas, limitasi", priority: "⭐" },
        { word: "瀬戸際", reading: "せとぎわ", meaning: "di ujung tanduk, kritis", priority: "⭐" },
        { word: "崖っぷち", reading: "がけっぷち", meaning: "tepian jurang, situasi kritis", priority: "⭐" },
        { word: "局際", reading: "きょくさい", meaning: "(jarang dipakai)", priority: "○" },
        { word: "国際化", reading: "こくさいか", meaning: "internasionalisasi", priority: "🔥" },
        { word: "国際的", reading: "こくさいてき", meaning: "internasional (sifat)", priority: "🔥" },
        { word: "際物", reading: "きわもの", meaning: "barang/produk musiman (laku sementara)", priority: "○" },
      ],
      family: "国際・国際化・国際的 → berkaitan dengan 'internasional'. 実際・際に → penggunaan temporal/kontekstual. 際立つ・瀬戸際 → 'tepi/ujung' secara figuratif.",
      onyomi_pattern: "サイ: 国際(さい)、実際(さい)、交際(さい)。 Kunyomi きわ saat berdiri sendiri atau dalam komposisi tertentu.",
      quiz: [
        { type: "baca", question: "実際", answer: "じっさい", hint: "pada kenyataannya" },
        { type: "arti", question: "国際化", answer: "internasionalisasi", hint: "化=menjadi/-isasi" },
        { type: "kanji", question: "こうさい (berpacaran/hubungan sosial)", answer: "交際", hint: "交=bergaul/bersilangan" },
        { type: "baca", question: "際立つ", answer: "きわだつ", hint: "mencolok, menonjol" },
        { type: "arti", question: "際限", answer: "batas, limitasi", hint: "限=batas" },
      ]
    },
    {
      kanji: "紹",
      meaning_core: ["memperkenalkan", "menghubungkan"],
      onyomi: "ショウ",
      kunyomi: "-",
      jukugo: [
        { word: "紹介", reading: "しょうかい", meaning: "perkenalan, pengenalan", priority: "🔥" },
        { word: "紹介状", reading: "しょうかいじょう", meaning: "surat pengantar/referensi", priority: "🔥" },
        { word: "自己紹介", reading: "じこしょうかい", meaning: "perkenalan diri", priority: "🔥" },
        { word: "紹介者", reading: "しょうかいしゃ", meaning: "orang yang memperkenalkan, referer", priority: "⭐" },
        { word: "ご紹介", reading: "ごしょうかい", meaning: "perkenalan (honorifik)", priority: "🔥" },
      ],
      family: "紹介 adalah jukugo utama. Varian seperti 自己紹介・紹介状 semuanya turunan dari konsep inti 'memperkenalkan'.",
      onyomi_pattern: "ショウ: 紹介(しょう). 100% sebagai ショウ. Hampir selalu muncul bersama 介.",
      quiz: [
        { type: "baca", question: "紹介", answer: "しょうかい", hint: "perkenalan" },
        { type: "arti", question: "自己紹介", answer: "perkenalan diri", hint: "自己=diri sendiri" },
        { type: "kanji", question: "しょうかいじょう (surat pengantar)", answer: "紹介状", hint: "状=surat/kondisi" },
        { type: "baca", question: "紹介者", answer: "しょうかいしゃ", hint: "orang yang memperkenalkan" },
        { type: "arti", question: "ご紹介", answer: "perkenalan (hormat)", hint: "ご=prefiks hormat" },
      ]
    },
    {
      kanji: "輝",
      meaning_core: ["bersinar", "berkilau", "cemerlang"],
      onyomi: "キ",
      kunyomi: "かがや(く)",
      jukugo: [
        { word: "輝く", reading: "かがやく", meaning: "bersinar, berkilau, bercahaya", priority: "🔥" },
        { word: "輝き", reading: "かがやき", meaning: "sinar, kilau, kecemerlangan", priority: "🔥" },
        { word: "光輝", reading: "こうき", meaning: "cahaya gemilang, kemilau", priority: "🔥" },
        { word: "輝石", reading: "きせき", meaning: "piroksin (mineral berkilap)", priority: "○" },
        { word: "輝線", reading: "きせん", meaning: "garis cahaya (spektrum)", priority: "○" },
        { word: "燦輝", reading: "さんき", meaning: "bersinar terang", priority: "○" },
        { word: "輝かしい", reading: "かがやかしい", meaning: "cemerlang, gilang-gemilang", priority: "🔥" },
        { word: "目輝く", reading: "めかがやく", meaning: "mata bersinar (semangat/bahagia)", priority: "⭐" },
      ],
      family: "輝く・輝き・輝かしい → satu keluarga dari kata kerja 'bersinar/cemerlang'. 光輝 → 'cahaya + bersinar' = kemilau.",
      onyomi_pattern: "キ: 光輝(き)。 Dominan sebagai kunyomi かがやく dalam penggunaan sehari-hari.",
      quiz: [
        { type: "baca", question: "光輝", answer: "こうき", hint: "cahaya gemilang" },
        { type: "arti", question: "輝かしい", answer: "cemerlang, gilang-gemilang", hint: "かしい = sifat tinggi" },
        { type: "kanji", question: "かがやき (kilau/sinar)", answer: "輝き", hint: "bentuk kata benda" },
        { type: "baca", question: "輝く", answer: "かがやく", hint: "bersinar" },
        { type: "arti", question: "目輝く", answer: "mata bersinar (semangat/bahagia)", hint: "目=mata" },
      ]
    },
    {
      kanji: "浮",
      meaning_core: ["mengapung", "terapung", "muncul ke permukaan", "tidak stabil"],
      onyomi: "フ",
      kunyomi: "う(く)、う(かぶ)、う(かべる)",
      jukugo: [
        { word: "浮く", reading: "うく", meaning: "mengapung, melayang", priority: "🔥" },
        { word: "浮かぶ", reading: "うかぶ", meaning: "terapung; muncul ke pikiran", priority: "🔥" },
        { word: "浮かべる", reading: "うかべる", meaning: "memunculkan (dalam pikiran); mengapungkan", priority: "🔥" },
        { word: "浮力", reading: "ふりょく", meaning: "gaya apung", priority: "🔥" },
        { word: "浮上", reading: "ふじょう", meaning: "muncul ke permukaan; naik pangkat", priority: "🔥" },
        { word: "浮動", reading: "ふどう", meaning: "mengambang, tidak stabil, mengapung", priority: "⭐" },
        { word: "浮気", reading: "うわき", meaning: "selingkuh; mudah berubah pikiran", priority: "🔥" },
        { word: "浮世", reading: "うきよ", meaning: "dunia yang sementara/fana (konsep Budha)", priority: "⭐" },
        { word: "浮世絵", reading: "うきよえ", meaning: "lukisan kayu tradisional Jepang", priority: "🔥" },
        { word: "浮遊", reading: "ふゆう", meaning: "melayang, mengembara", priority: "⭐" },
        { word: "浮き沈み", reading: "うきしずみ", meaning: "pasang surut (kehidupan)", priority: "🔥" },
        { word: "幽浮体", reading: "ゆうふたい", meaning: "(sastra) tubuh roh", priority: "○" },
      ],
      family: "浮力・浮上・浮動・浮遊 → berkaitan dengan 'terapung/melayang' secara fisik. 浮気・浮世 → nuansa 'tidak stabil/sementara'. 浮かぶ・浮かべる → muncul ke pikiran.",
      onyomi_pattern: "フ: 浮力(ふ)、浮上(ふ)、浮動(ふ)。 Kunyomi うく/うかぶ saat digunakan sebagai kata kerja.",
      quiz: [
        { type: "baca", question: "浮力", answer: "ふりょく", hint: "gaya apung" },
        { type: "arti", question: "浮世絵", answer: "lukisan kayu tradisional Jepang", hint: "絵=lukisan" },
        { type: "kanji", question: "うわき (selingkuh)", answer: "浮気", hint: "気=perasaan/pikiran" },
        { type: "baca", question: "浮上", answer: "ふじょう", hint: "muncul ke permukaan" },
        { type: "arti", question: "浮き沈み", answer: "pasang surut kehidupan", hint: "沈み=tenggelam/turun" },
      ]
    },
    {
      kanji: "並",
      meaning_core: ["berjajar", "sejajar", "biasa", "rata-rata"],
      onyomi: "ヘイ",
      kunyomi: "なら(ぶ)、なら(べる)、なみ",
      jukugo: [
        { word: "並ぶ", reading: "ならぶ", meaning: "berjajar, antre", priority: "🔥" },
        { word: "並べる", reading: "ならべる", meaning: "menyusun, menaruh berjajar", priority: "🔥" },
        { word: "並行", reading: "へいこう", meaning: "paralel, bersamaan", priority: "🔥" },
        { word: "並列", reading: "へいれつ", meaning: "susunan paralel, sejajar", priority: "🔥" },
        { word: "並大抵", reading: "なみたいてい", meaning: "biasa, rata-rata (sering digunakan negatif)", priority: "🔥" },
        { word: "並木", reading: "なみき", meaning: "pohon yang berjejer di pinggir jalan", priority: "🔥" },
        { word: "人並み", reading: "ひとなみ", meaning: "rata-rata kebanyakan orang", priority: "⭐" },
        { word: "世並み", reading: "よなみ", meaning: "kondisi umum masyarakat", priority: "○" },
        { word: "並み居る", reading: "なみいる", meaning: "semua yang hadir (formal)", priority: "○" },
        { word: "並行輸入", reading: "へいこうゆにゅう", meaning: "impor paralel (barang resmi tapi di luar distribusi)", priority: "⭐" },
      ],
      family: "並行・並列 → 'sejajar/paralel' secara struktural. 並ぶ・並べる → aksi 'berjajar'. 並木・人並み・並大抵 → 'rata-rata/biasa' sebagai standar.",
      onyomi_pattern: "ヘイ: 並行(へい)、並列(へい)。 Kunyomi なら/なみ lebih dominan dalam percakapan sehari-hari.",
      quiz: [
        { type: "baca", question: "並行", answer: "へいこう", hint: "paralel, bersamaan" },
        { type: "arti", question: "並木", answer: "pohon berjejer di pinggir jalan", hint: "木=pohon" },
        { type: "kanji", question: "なみたいてい (biasa/rata-rata)", answer: "並大抵", hint: "sering dipakai dalam bentuk negatif" },
        { type: "baca", question: "並列", answer: "へいれつ", hint: "susunan paralel" },
        { type: "arti", question: "人並み", answer: "rata-rata kebanyakan orang", hint: "人=orang" },
      ]
    },
    {
      kanji: "雲",
      meaning_core: ["awan", "kabut", "sesuatu yang mengapung di atas"],
      onyomi: "ウン",
      kunyomi: "くも",
      jukugo: [
        { word: "雲", reading: "くも", meaning: "awan", priority: "🔥" },
        { word: "雲海", reading: "うんかい", meaning: "lautan awan", priority: "🔥" },
        { word: "積乱雲", reading: "せきらんうん", meaning: "awan kumulonimbus", priority: "⭐" },
        { word: "雲泥の差", reading: "うんでいのさ", meaning: "perbedaan yang sangat besar (langit-bumi)", priority: "🔥" },
        { word: "風雲", reading: "ふううん", meaning: "angin dan awan; situasi yang tidak menentu", priority: "⭐" },
        { word: "暗雲", reading: "あんうん", meaning: "awan gelap; pertanda buruk", priority: "🔥" },
        { word: "白雲", reading: "はくうん", meaning: "awan putih", priority: "⭐" },
        { word: "雲散霧消", reading: "うんさんむしょう", meaning: "lenyap tanpa bekas", priority: "🔥" },
        { word: "青雲", reading: "せいうん", meaning: "awan biru; ambisi tinggi", priority: "○" },
        { word: "星雲", reading: "せいうん", meaning: "nebula", priority: "⭐" },
        { word: "九雲", reading: "くうん", meaning: "langit tinggi (figuratif)", priority: "○" },
      ],
      family: "雲海・積乱雲・暗雲 → jenis/kondisi awan. 雲泥の差・雲散霧消 → idiom menggunakan awan untuk menggambarkan perbedaan/lenyap.",
      onyomi_pattern: "ウン: 雲海(うん)、暗雲(うん)、星雲(うん)。 Kunyomi くも saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "暗雲", answer: "あんうん", hint: "pertanda buruk" },
        { type: "arti", question: "雲泥の差", answer: "perbedaan sangat besar (langit-bumi)", hint: "泥=lumpur/tanah" },
        { type: "kanji", question: "うんかい (lautan awan)", answer: "雲海", hint: "海=laut" },
        { type: "baca", question: "雲散霧消", answer: "うんさんむしょう", hint: "lenyap tanpa bekas" },
        { type: "arti", question: "星雲", answer: "nebula", hint: "星=bintang" },
      ]
    },
    {
      kanji: "与",
      meaning_core: ["memberi", "menganugerahkan", "berkaitan dengan"],
      onyomi: "ヨ",
      kunyomi: "あた(える)、くみ(する)",
      jukugo: [
        { word: "与える", reading: "あたえる", meaning: "memberi, menganugerahkan", priority: "🔥" },
        { word: "与党", reading: "よとう", meaning: "partai yang berkuasa, koalisi pemerintah", priority: "🔥" },
        { word: "給与", reading: "きゅうよ", meaning: "gaji, upah", priority: "🔥" },
        { word: "参与", reading: "さんよ", meaning: "partisipasi, keterlibatan", priority: "🔥" },
        { word: "賦与", reading: "ふよ", meaning: "anugerah, pemberian (dari alam/Tuhan)", priority: "⭐" },
        { word: "授与", reading: "じゅよ", meaning: "pemberian penghargaan/gelar", priority: "🔥" },
        { word: "関与", reading: "かんよ", meaning: "keterlibatan, berkaitan", priority: "🔥" },
        { word: "貸与", reading: "たいよ", meaning: "peminjaman (dari yang lebih tinggi)", priority: "⭐" },
        { word: "与件", reading: "よけん", meaning: "kondisi yang sudah ada, data yang diberikan", priority: "○" },
        { word: "供与", reading: "きょうよ", meaning: "penyediaan, pemberian", priority: "⭐" },
      ],
      family: "給与・授与・賦与・貸与・供与 → berbagai jenis 'pemberian'. 参与・関与 → 'keterlibatan/partisipasi'. 与党 → khusus konteks politik.",
      onyomi_pattern: "ヨ: 与党(よ)、給与(よ)、参与(よ)、授与(よ)。 ~100% sebagai ヨ.",
      quiz: [
        { type: "baca", question: "給与", answer: "きゅうよ", hint: "gaji" },
        { type: "arti", question: "与党", answer: "partai yang berkuasa/koalisi", hint: "党=partai" },
        { type: "kanji", question: "かんよ (keterlibatan)", answer: "関与", hint: "関=berkaitan" },
        { type: "baca", question: "授与", answer: "じゅよ", hint: "pemberian penghargaan" },
        { type: "arti", question: "参与", answer: "partisipasi, keterlibatan", hint: "参=ikut serta" },
      ]
    },
    {
      kanji: "髪",
      meaning_core: ["rambut"],
      onyomi: "ハツ",
      kunyomi: "かみ",
      jukugo: [
        { word: "髪", reading: "かみ", meaning: "rambut", priority: "🔥" },
        { word: "髪の毛", reading: "かみのけ", meaning: "helai rambut", priority: "🔥" },
        { word: "金髪", reading: "きんぱつ", meaning: "rambut pirang/emas", priority: "🔥" },
        { word: "黒髪", reading: "くろかみ", meaning: "rambut hitam", priority: "🔥" },
        { word: "白髪", reading: "しらが/はくはつ", meaning: "rambut putih/uban", priority: "🔥" },
        { word: "長髪", reading: "ちょうはつ", meaning: "rambut panjang", priority: "🔥" },
        { word: "短髪", reading: "たんぱつ", meaning: "rambut pendek", priority: "⭐" },
        { word: "頭髪", reading: "とうはつ", meaning: "rambut kepala", priority: "⭐" },
        { word: "散髪", reading: "さんぱつ", meaning: "potong rambut", priority: "🔥" },
        { word: "理髪", reading: "りはつ", meaning: "memangkas rambut, tata rambut", priority: "🔥" },
        { word: "理髪店", reading: "りはつてん", meaning: "salon rambut, barber shop", priority: "🔥" },
        { word: "整髪", reading: "せいはつ", meaning: "menata rambut", priority: "⭐" },
        { word: "乱髪", reading: "らんぱつ", meaning: "rambut awut-awutan", priority: "○" },
      ],
      family: "金髪・黒髪・白髪 → warna rambut. 長髪・短髪 → panjang rambut. 散髪・理髪・整髪 → aktivitas perawatan rambut.",
      onyomi_pattern: "ハツ: 金髪(ぱつ)、白髪(はつ)、散髪(ぱつ)、理髪(はつ)。 Kunyomi かみ saat berdiri sendiri atau sebagai 黒髪・白髪.",
      quiz: [
        { type: "baca", question: "散髪", answer: "さんぱつ", hint: "potong rambut" },
        { type: "arti", question: "白髪", answer: "rambut putih/uban", hint: "白=putih" },
        { type: "kanji", question: "きんぱつ (rambut pirang)", answer: "金髪", hint: "金=emas" },
        { type: "baca", question: "理髪店", answer: "りはつてん", hint: "barber shop" },
        { type: "arti", question: "長髪", answer: "rambut panjang", hint: "長=panjang" },
      ]
    },
    {
      kanji: "伸",
      meaning_core: ["memanjang", "tumbuh", "meregangkan", "berkembang"],
      onyomi: "シン",
      kunyomi: "の(ばす)、の(びる)、の(べる)",
      jukugo: [
        { word: "伸びる", reading: "のびる", meaning: "memanjang, tumbuh, berkembang", priority: "🔥" },
        { word: "伸ばす", reading: "のばす", meaning: "memanjangkan, mengembangkan", priority: "🔥" },
        { word: "伸長", reading: "しんちょう", meaning: "pertumbuhan, perpanjangan", priority: "🔥" },
        { word: "伸縮", reading: "しんしゅく", meaning: "elastisitas, daya mulur", priority: "🔥" },
        { word: "追伸", reading: "ついしん", meaning: "P.S. (tambahan dalam surat)", priority: "🔥" },
        { word: "伸展", reading: "しんてん", meaning: "pengembangan, perluasan", priority: "⭐" },
        { word: "背伸び", reading: "せのび", meaning: "berjinjit; berusaha melebihi kemampuan", priority: "🔥" },
        { word: "手伸ばし", reading: "てのばし", meaning: "meraih sesuatu, memperluas jangkauan", priority: "⭐" },
        { word: "伸び悩む", reading: "のびなやむ", meaning: "stagnan, tidak berkembang", priority: "🔥" },
      ],
      family: "伸びる・伸ばす・伸長・伸展 → pertumbuhan/pemanjangan fisik atau figuratif. 伸縮 → elastisitas (bisa memanjang dan memendek).",
      onyomi_pattern: "シン: 伸長(しん)、伸縮(しん)、追伸(しん)。 Kunyomi の dominan dalam percakapan.",
      quiz: [
        { type: "baca", question: "伸縮", answer: "しんしゅく", hint: "elastisitas" },
        { type: "arti", question: "追伸", answer: "P.S. (tambahan dalam surat)", hint: "追=menambahkan/mengejar" },
        { type: "kanji", question: "のびなやむ (stagnan)", answer: "伸び悩む", hint: "悩む=bingung/menderita" },
        { type: "baca", question: "背伸び", answer: "せのび", hint: "berjinjit" },
        { type: "arti", question: "伸長", answer: "pertumbuhan, perpanjangan", hint: "長=panjang/besar" },
      ]
    },
    {
      kanji: "共",
      meaning_core: ["bersama", "bersama-sama", "berbagi", "berdua"],
      onyomi: "キョウ",
      kunyomi: "とも",
      jukugo: [
        { word: "共に", reading: "ともに", meaning: "bersama, seiring dengan", priority: "🔥" },
        { word: "共同", reading: "きょうどう", meaning: "bersama, kolaborasi, kooperasi", priority: "🔥" },
        { word: "共有", reading: "きょうゆう", meaning: "berbagi, penggunaan bersama", priority: "🔥" },
        { word: "共感", reading: "きょうかん", meaning: "empati, simpati", priority: "🔥" },
        { word: "共通", reading: "きょうつう", meaning: "umum, yang dimiliki bersama", priority: "🔥" },
        { word: "共存", reading: "きょうぞん", meaning: "koeksistensi, hidup berdampingan", priority: "🔥" },
        { word: "共和国", reading: "きょうわこく", meaning: "republik", priority: "🔥" },
        { word: "公共", reading: "こうきょう", meaning: "publik, untuk umum", priority: "🔥" },
        { word: "共産", reading: "きょうさん", meaning: "komunis (ideology)", priority: "🔥" },
        { word: "共鳴", reading: "きょうめい", meaning: "resonansi; kesetujuan/simpati", priority: "🔥" },
        { word: "共著", reading: "きょうちょ", meaning: "karya bersama/kolaborasi", priority: "⭐" },
        { word: "共謀", reading: "きょうぼう", meaning: "konspirasi, bersekongkol", priority: "⭐" },
        { word: "共犯", reading: "きょうはん", meaning: "keterlibatan bersama (kejahatan), rekan kriminal", priority: "⭐" },
        { word: "共演", reading: "きょうえん", meaning: "tampil bersama, co-starring", priority: "🔥" },
      ],
      family: "共同・共有・共存・共通 → tentang 'kebersamaan'. 共感・共鳴 → tentang perasaan/pikiran bersama. 共産・共和国 → ideologi/sistem politik bersama.",
      onyomi_pattern: "キョウ: 共同(きょう)、共有(きょう)、共通(きょう)。 Kunyomi とも saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "共感", answer: "きょうかん", hint: "empati" },
        { type: "arti", question: "公共", answer: "publik, untuk umum", hint: "公=umum/publik" },
        { type: "kanji", question: "きょうつう (umum/bersama)", answer: "共通", hint: "通=tembus/umum" },
        { type: "baca", question: "共演", answer: "きょうえん", hint: "tampil bersama" },
        { type: "arti", question: "共鳴", answer: "resonansi; simpati/kesetujuan", hint: "鳴=berbunyi/berdengung" },
      ]
    },
    {
      kanji: "済",
      meaning_core: ["selesai", "menyelesaikan", "membantu", "menyelamatkan (ekonomi)"],
      onyomi: "サイ",
      kunyomi: "す(む)、す(ます)、すく(う)",
      jukugo: [
        { word: "済む", reading: "すむ", meaning: "selesai, beres", priority: "🔥" },
        { word: "済ます", reading: "すます", meaning: "menyelesaikan", priority: "🔥" },
        { word: "経済", reading: "けいざい", meaning: "ekonomi", priority: "🔥" },
        { word: "返済", reading: "へんさい", meaning: "pelunasan hutang, pembayaran kembali", priority: "🔥" },
        { word: "救済", reading: "きゅうさい", meaning: "bantuan, penyelamatan (bencana/ekonomi)", priority: "🔥" },
        { word: "弁済", reading: "べんさい", meaning: "pembayaran (hukum)", priority: "⭐" },
        { word: "決済", reading: "けっさい", meaning: "pembayaran, penyelesaian (transaksi)", priority: "🔥" },
        { word: "共済", reading: "きょうさい", meaning: "asuransi/koperasi bersama", priority: "⭐" },
        { word: "未済", reading: "みさい", meaning: "belum selesai, belum diselesaikan", priority: "⭐" },
        { word: "既済", reading: "きさい", meaning: "sudah diselesaikan", priority: "○" },
      ],
      family: "経済・救済・返済・決済 → berbagai konteks 'penyelesaian/pembayaran'. 済む・済ます → versi sederhana sehari-hari ('sudah beres').",
      onyomi_pattern: "サイ: 経済(ざい)、返済(さい)、救済(さい)、決済(さい)。 Kunyomi す(む) untuk penggunaan sederhana.",
      quiz: [
        { type: "baca", question: "経済", answer: "けいざい", hint: "ekonomi" },
        { type: "arti", question: "返済", answer: "pelunasan hutang", hint: "返=kembali" },
        { type: "kanji", question: "きゅうさい (penyelamatan)", answer: "救済", hint: "救=menyelamatkan" },
        { type: "baca", question: "決済", answer: "けっさい", hint: "pembayaran transaksi" },
        { type: "arti", question: "共済", answer: "asuransi/koperasi bersama", hint: "共=bersama" },
      ]
    },
    {
      kanji: "技",
      meaning_core: ["teknik", "keterampilan", "keahlian"],
      onyomi: "ギ",
      kunyomi: "わざ",
      jukugo: [
        { word: "技術", reading: "ぎじゅつ", meaning: "teknologi, teknik, keterampilan", priority: "🔥" },
        { word: "技術者", reading: "ぎじゅつしゃ", meaning: "teknisi, insinyur", priority: "🔥" },
        { word: "技能", reading: "ぎのう", meaning: "kemampuan teknis, keahlian", priority: "🔥" },
        { word: "技巧", reading: "ぎこう", meaning: "teknik/seni yang canggih", priority: "🔥" },
        { word: "競技", reading: "きょうぎ", meaning: "kompetisi, perlombaan", priority: "🔥" },
        { word: "演技", reading: "えんぎ", meaning: "akting, penampilan", priority: "🔥" },
        { word: "特技", reading: "とくぎ", meaning: "keahlian khusus", priority: "🔥" },
        { word: "妙技", reading: "みょうぎ", meaning: "keahlian yang luar biasa", priority: "⭐" },
        { word: "武技", reading: "ぶぎ", meaning: "ilmu bela diri", priority: "⭐" },
        { word: "技師", reading: "ぎし", meaning: "insinyur, ahli teknik", priority: "🔥" },
        { word: "技量", reading: "ぎりょう", meaning: "kemampuan, kapabilitas", priority: "⭐" },
        { word: "球技", reading: "きゅうぎ", meaning: "olahraga bola", priority: "⭐" },
      ],
      family: "技術・技能・技巧・技量 → berbagai aspek 'kemampuan/keterampilan'. 競技・演技・球技 → jenis-jenis 'penampilan/kompetisi'.",
      onyomi_pattern: "ギ: 技術(ぎ)、技能(ぎ)、競技(ぎ)、演技(ぎ)。 ~100% sebagai ギ.",
      quiz: [
        { type: "baca", question: "技術", answer: "ぎじゅつ", hint: "teknologi/teknik" },
        { type: "arti", question: "演技", answer: "akting, penampilan", hint: "演=tampil/memainkan" },
        { type: "kanji", question: "とくぎ (keahlian khusus)", answer: "特技", hint: "特=khusus/istimewa" },
        { type: "baca", question: "競技", answer: "きょうぎ", hint: "kompetisi" },
        { type: "arti", question: "技巧", answer: "teknik/seni yang canggih", hint: "巧=terampil/canggih" },
      ]
    },
    {
      kanji: "術",
      meaning_core: ["teknik", "seni", "metode", "tipu daya"],
      onyomi: "ジュツ",
      kunyomi: "-",
      jukugo: [
        { word: "技術", reading: "ぎじゅつ", meaning: "teknologi, teknik", priority: "🔥" },
        { word: "手術", reading: "しゅじゅつ", meaning: "operasi, pembedahan", priority: "🔥" },
        { word: "美術", reading: "びじゅつ", meaning: "seni rupa, fine art", priority: "🔥" },
        { word: "学術", reading: "がくじゅつ", meaning: "akademis, ilmiah", priority: "🔥" },
        { word: "芸術", reading: "げいじゅつ", meaning: "seni, kesenian", priority: "🔥" },
        { word: "武術", reading: "ぶじゅつ", meaning: "ilmu bela diri, seni bertarung", priority: "🔥" },
        { word: "術語", reading: "じゅつご", meaning: "istilah teknis, terminologi", priority: "⭐" },
        { word: "戦術", reading: "せんじゅつ", meaning: "taktik, strategi perang", priority: "🔥" },
        { word: "魔術", reading: "まじゅつ", meaning: "sihir, sulap", priority: "🔥" },
        { word: "話術", reading: "わじゅつ", meaning: "kemampuan berbicara, retorika", priority: "⭐" },
        { word: "術策", reading: "じゅっさく", meaning: "tipu muslihat, trik", priority: "⭐" },
        { word: "忍術", reading: "にんじゅつ", meaning: "ilmu ninja", priority: "⭐" },
        { word: "呪術", reading: "じゅじゅつ", meaning: "ilmu gaib, mantra", priority: "⭐" },
        { word: "医術", reading: "いじゅつ", meaning: "ilmu kedokteran", priority: "⭐" },
      ],
      family: "技術・美術・芸術・学術 → berbagai bidang 'seni/ilmu'. 手術・医術 → medis. 戦術・武術・忍術 → militer/bela diri.",
      onyomi_pattern: "ジュツ: 技術(じゅつ)、手術(じゅつ)、美術(じゅつ)。 ~100% sebagai ジュツ.",
      quiz: [
        { type: "baca", question: "手術", answer: "しゅじゅつ", hint: "operasi" },
        { type: "arti", question: "芸術", answer: "seni, kesenian", hint: "芸=seni pertunjukan" },
        { type: "kanji", question: "せんじゅつ (taktik)", answer: "戦術", hint: "戦=perang" },
        { type: "baca", question: "美術", answer: "びじゅつ", hint: "seni rupa" },
        { type: "arti", question: "話術", answer: "kemampuan berbicara, retorika", hint: "話=berbicara" },
      ]
    },
    {
      kanji: "展",
      meaning_core: ["pameran", "mengembangkan", "membentangkan"],
      onyomi: "テン",
      kunyomi: "-",
      jukugo: [
        { word: "展覧会", reading: "てんらんかい", meaning: "pameran (seni dll)", priority: "🔥" },
        { word: "展示", reading: "てんじ", meaning: "pameran, displai", priority: "🔥" },
        { word: "発展", reading: "はってん", meaning: "perkembangan, kemajuan", priority: "🔥" },
        { word: "展開", reading: "てんかい", meaning: "pengembangan, pembukaan (alur cerita)", priority: "🔥" },
        { word: "進展", reading: "しんてん", meaning: "kemajuan, perkembangan", priority: "🔥" },
        { word: "展望", reading: "てんぼう", meaning: "pandangan ke depan, prospek; pemandangan", priority: "🔥" },
        { word: "発展途上国", reading: "はってんとじょうこく", meaning: "negara berkembang", priority: "🔥" },
        { word: "展示会", reading: "てんじかい", meaning: "pameran dagang/seni", priority: "🔥" },
        { word: "伸展", reading: "しんてん", meaning: "perluasan, pengembangan", priority: "⭐" },
        { word: "展地", reading: "てんち", meaning: "area pameran", priority: "○" },
        { word: "外展", reading: "がいてん", meaning: "rotasi ke luar (anatomi)", priority: "○" },
      ],
      family: "展示・展覧会・展示会 → 'pameran/displai'. 発展・展開・進展・伸展 → 'perkembangan/perluasan'. 展望 → 'memandang ke depan'.",
      onyomi_pattern: "テン: 展示(てん)、発展(てん)、展望(てん)。 ~100% sebagai テン.",
      quiz: [
        { type: "baca", question: "発展", answer: "はってん", hint: "perkembangan" },
        { type: "arti", question: "展望", answer: "pandangan ke depan/prospek; pemandangan", hint: "望=berharap/memandang jauh" },
        { type: "kanji", question: "てんかい (pengembangan)", answer: "展開", hint: "開=membuka" },
        { type: "baca", question: "展覧会", answer: "てんらんかい", hint: "pameran seni" },
        { type: "arti", question: "進展", answer: "kemajuan, perkembangan", hint: "進=maju" },
      ]
    },
    {
      kanji: "関",
      meaning_core: ["hubungan", "keterkaitan", "gerbang", "hambatan"],
      onyomi: "カン",
      kunyomi: "せき、かか(わる)",
      jukugo: [
        { word: "関係", reading: "かんけい", meaning: "hubungan, kaitan", priority: "🔥" },
        { word: "関心", reading: "かんしん", meaning: "ketertarikan, perhatian", priority: "🔥" },
        { word: "関連", reading: "かんれん", meaning: "berkaitan, berhuungan", priority: "🔥" },
        { word: "機関", reading: "きかん", meaning: "lembaga, mesin", priority: "🔥" },
        { word: "関東", reading: "かんとう", meaning: "wilayah Kanto (Tokyo dll)", priority: "🔥" },
        { word: "関西", reading: "かんさい", meaning: "wilayah Kansai (Osaka dll)", priority: "🔥" },
        { word: "難関", reading: "なんかん", meaning: "hambatan sulit, seleksi ketat", priority: "🔥" },
        { word: "玄関", reading: "げんかん", meaning: "pintu masuk, foyer", priority: "🔥" },
        { word: "税関", reading: "ぜいかん", meaning: "bea cukai", priority: "🔥" },
        { word: "関税", reading: "かんぜい", meaning: "tarif bea cukai", priority: "🔥" },
        { word: "関与", reading: "かんよ", meaning: "keterlibatan, partisipasi", priority: "🔥" },
        { word: "無関係", reading: "むかんけい", meaning: "tidak ada hubungan sama sekali", priority: "🔥" },
        { word: "利害関係", reading: "りがいかんけい", meaning: "kepentingan, hubungan untung-rugi", priority: "⭐" },
        { word: "関節", reading: "かんせつ", meaning: "sendi (tulang)", priority: "🔥" },
        { word: "関わる", reading: "かかわる", meaning: "berkaitan, terlibat", priority: "🔥" },
        { word: "無関心", reading: "むかんしん", meaning: "acuh tak acuh, tidak peduli", priority: "🔥" },
      ],
      family: "関係・関連・関与・関わる → berkaitan/terhubung. 関心・無関心 → ketertarikan atau ketidakpedulian. 関東・関西・玄関・税関 → fisik 'gerbang/wilayah'.",
      onyomi_pattern: "カン: 関係(かん)、機関(かん)、難関(かん)。 ~100% sebagai カン.",
      quiz: [
        { type: "baca", question: "関係", answer: "かんけい", hint: "hubungan" },
        { type: "arti", question: "玄関", answer: "pintu masuk, foyer", hint: "玄=misterius/hitam" },
        { type: "kanji", question: "むかんしん (tidak peduli)", answer: "無関心", hint: "無=tidak ada" },
        { type: "baca", question: "税関", answer: "ぜいかん", hint: "bea cukai" },
        { type: "arti", question: "関節", answer: "sendi (tulang)", hint: "節=ruas/sendi" },
      ]
    },
    {
      kanji: "様",
      meaning_core: ["cara", "penampilan", "keadaan", "Tuan/Nyonya (gelar hormat)"],
      onyomi: "ヨウ",
      kunyomi: "さま",
      jukugo: [
        { word: "様子", reading: "ようす", meaning: "keadaan, kondisi, situasi", priority: "🔥" },
        { word: "様式", reading: "ようしき", meaning: "gaya, format, tipe", priority: "🔥" },
        { word: "様々", reading: "さまざま", meaning: "berbagai macam, beraneka ragam", priority: "🔥" },
        { word: "様相", reading: "ようそう", meaning: "aspek, penampilan, gambaran", priority: "⭐" },
        { word: "同様", reading: "どうよう", meaning: "sama, serupa", priority: "🔥" },
        { word: "異様", reading: "いよう", meaning: "aneh, tidak biasa", priority: "🔥" },
        { word: "正様", reading: "せいよう", meaning: "(jarang) kondisi normal", priority: "○" },
        { word: "どのように", reading: "どのように", meaning: "dengan cara apa, bagaimana", priority: "🔥" },
        { word: "模様", reading: "もよう", meaning: "pola, corak; kondisi (cuaca)", priority: "🔥" },
        { word: "有様", reading: "ありさま", meaning: "keadaan, kondisi (sering negatif)", priority: "🔥" },
        { word: "神様", reading: "かみさま", meaning: "Tuhan, dewa (bahasa hormat)", priority: "🔥" },
        { word: "王様", reading: "おうさま", meaning: "raja (bahasa hormat)", priority: "🔥" },
        { word: "皆様", reading: "みなさま", meaning: "hadirin sekalian, semua orang (hormat)", priority: "🔥" },
        { word: "各様", reading: "かくよう", meaning: "masing-masing jenisnya", priority: "○" },
      ],
      family: "様子・様式・様相・模様 → keadaan/penampilan sesuatu. 様々・各様 → 'berbagai macam'. 神様・王様・皆様 → penggunaan sebagai gelar hormat.",
      onyomi_pattern: "ヨウ: 様子(よう)、様式(よう)、同様(よう)。 Kunyomi さま saat digunakan sebagai gelar hormat (神様・皆様).",
      quiz: [
        { type: "baca", question: "様子", answer: "ようす", hint: "keadaan/situasi" },
        { type: "arti", question: "模様", answer: "pola, corak; kondisi (cuaca)", hint: "模=model/pola" },
        { type: "kanji", question: "どうよう (sama/serupa)", answer: "同様", hint: "同=sama" },
        { type: "baca", question: "皆様", answer: "みなさま", hint: "hadirin sekalian" },
        { type: "arti", question: "異様", answer: "aneh, tidak biasa", hint: "異=berbeda/aneh" },
      ]
    },
    {
      kanji: "影",
      meaning_core: ["bayangan", "pengaruh", "efek", "cerminan"],
      onyomi: "エイ",
      kunyomi: "かげ",
      jukugo: [
        { word: "影響", reading: "えいきょう", meaning: "pengaruh, dampak", priority: "🔥" },
        { word: "影", reading: "かげ", meaning: "bayangan, siluet", priority: "🔥" },
        { word: "人影", reading: "ひとかげ", meaning: "bayangan orang, sesosok orang", priority: "🔥" },
        { word: "陰影", reading: "いんえい", meaning: "bayangan dan terang; nuansa", priority: "⭐" },
        { word: "撮影", reading: "さつえい", meaning: "pengambilan gambar/foto, syuting", priority: "🔥" },
        { word: "投影", reading: "とうえい", meaning: "proyeksi, pemetaan", priority: "🔥" },
        { word: "映影", reading: "えいえい", meaning: "(jarang) bayangan di air", priority: "○" },
        { word: "幻影", reading: "げんえい", meaning: "bayangan semu, ilusi", priority: "⭐" },
        { word: "影武者", reading: "かげむしゃ", meaning: "penyamar, pengganti rahasia (sejarah)", priority: "⭐" },
        { word: "月影", reading: "つきかげ", meaning: "cahaya bulan, bayangan bulan", priority: "○" },
        { word: "影分身", reading: "かげぶんしん", meaning: "klon bayangan (Naruto dll)", priority: "○" },
      ],
      family: "影響・投影・撮影 → 'pengaruh/proyeksi' secara aktif. 影・人影・幻影・陰影 → jenis-jenis bayangan.",
      onyomi_pattern: "エイ: 影響(えい)、撮影(えい)、投影(えい)。 Kunyomi かげ saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "影響", answer: "えいきょう", hint: "pengaruh/dampak" },
        { type: "arti", question: "撮影", answer: "pengambilan gambar, syuting", hint: "撮=mengambil gambar" },
        { type: "kanji", question: "とうえい (proyeksi)", answer: "投影", hint: "投=melempar/memproyeksikan" },
        { type: "baca", question: "幻影", answer: "げんえい", hint: "ilusi, bayangan semu" },
        { type: "arti", question: "陰影", answer: "bayangan dan terang; nuansa", hint: "陰=gelap/bayang" },
      ]
    },
    {
      kanji: "響",
      meaning_core: ["bergaung", "bergema", "pengaruh suara"],
      onyomi: "キョウ",
      kunyomi: "ひびく",
      jukugo: [
        { word: "響く", reading: "ひびく", meaning: "bergema, bergaung; berpengaruh", priority: "🔥" },
        { word: "影響", reading: "えいきょう", meaning: "pengaruh, dampak", priority: "🔥" },
        { word: "反響", reading: "はんきょう", meaning: "gema, efek samping, reaksi", priority: "🔥" },
        { word: "音響", reading: "おんきょう", meaning: "akustik, efek suara", priority: "🔥" },
        { word: "響宴", reading: "きょうえん", meaning: "perjamuan mewah (sastra)", priority: "○" },
        { word: "交響曲", reading: "こうきょうきょく", meaning: "simfoni", priority: "🔥" },
        { word: "交響楽団", reading: "こうきょうがくだん", meaning: "orkestra simfoni", priority: "🔥" },
        { word: "余響", reading: "よきょう", meaning: "gaung yang tersisa, afterglow suara", priority: "○" },
        { word: "響き", reading: "ひびき", meaning: "bunyi gema, efek/kesan", priority: "🔥" },
      ],
      family: "音響・交響曲・反響 → berkaitan dengan suara dan gaung. 影響・反響 → pengaruh/dampak secara lebih luas.",
      onyomi_pattern: "キョウ: 影響(きょう)、反響(きょう)、音響(きょう)、交響曲(きょう)。 ~100% sebagai キョウ.",
      quiz: [
        { type: "baca", question: "反響", answer: "はんきょう", hint: "gaung, reaksi" },
        { type: "arti", question: "音響", answer: "akustik, efek suara", hint: "音=suara" },
        { type: "kanji", question: "こうきょうきょく (simfoni)", answer: "交響曲", hint: "交=bersilang/saling" },
        { type: "baca", question: "響き", answer: "ひびき", hint: "bunyi gema, kesan" },
        { type: "arti", question: "影響", answer: "pengaruh, dampak", hint: "影=bayangan" },
      ]
    },
    {
      kanji: "演",
      meaning_core: ["pertunjukan", "memainkan", "latihan", "menjalankan"],
      onyomi: "エン",
      kunyomi: "-",
      jukugo: [
        { word: "演じる", reading: "えんじる", meaning: "memainkan peran, berakting", priority: "🔥" },
        { word: "演技", reading: "えんぎ", meaning: "akting, penampilan", priority: "🔥" },
        { word: "演奏", reading: "えんそう", meaning: "pertunjukan musik, memainkan alat musik", priority: "🔥" },
        { word: "演説", reading: "えんぜつ", meaning: "pidato, orasi", priority: "🔥" },
        { word: "演出", reading: "えんしゅつ", meaning: "penyutradaraan, produksi pertunjukan", priority: "🔥" },
        { word: "出演", reading: "しゅつえん", meaning: "tampil, muncul di (acara/film)", priority: "🔥" },
        { word: "主演", reading: "しゅえん", meaning: "peran utama, bintang utama", priority: "🔥" },
        { word: "公演", reading: "こうえん", meaning: "pertunjukan terbuka/publik", priority: "🔥" },
        { word: "演習", reading: "えんしゅう", meaning: "latihan, praktik, drill", priority: "🔥" },
        { word: "講演", reading: "こうえん", meaning: "kuliah umum, ceramah", priority: "🔥" },
        { word: "演劇", reading: "えんげき", meaning: "drama, teater", priority: "🔥" },
        { word: "共演", reading: "きょうえん", meaning: "tampil bersama, co-star", priority: "🔥" },
        { word: "演算", reading: "えんざん", meaning: "operasi matematika/komputer", priority: "⭐" },
      ],
      family: "演技・演奏・演劇・出演・主演 → pertunjukan seni. 演説・講演 → pidato/ceramah. 演習・演算 → latihan/operasi.",
      onyomi_pattern: "エン: 演技(えん)、演奏(えん)、公演(えん)、講演(えん)。 ~100% sebagai エン.",
      quiz: [
        { type: "baca", question: "演奏", answer: "えんそう", hint: "pertunjukan musik" },
        { type: "arti", question: "主演", answer: "peran utama, bintang utama", hint: "主=utama" },
        { type: "kanji", question: "こうえん (ceramah/kuliah umum)", answer: "講演", hint: "講=mengajar/ceramah" },
        { type: "baca", question: "出演", answer: "しゅつえん", hint: "tampil di acara/film" },
        { type: "arti", question: "演習", answer: "latihan, praktik, drill", hint: "習=berlatih" },
      ]
    },
  ]
};
