
// ========== PERTEMUAN 8 ==========
const pertemuan8 = {
  id: 8,
  title: "Pertemuan 8",
  kanji: [
    { kanji: "奏", meaning_core: ["memainkan musik", "melaporkan kepada raja"], onyomi: "ソウ", kunyomi: "かな(でる)",
      jukugo: [
        { word: "演奏", reading: "えんそう", meaning: "pertunjukan musik", priority: "🔥" },
        { word: "奏でる", reading: "かなでる", meaning: "memainkan alat musik", priority: "🔥" },
        { word: "奏者", reading: "そうしゃ", meaning: "pemain musik, musisi", priority: "🔥" },
        { word: "伴奏", reading: "ばんそう", meaning: "iringan musik", priority: "🔥" },
        { word: "独奏", reading: "どくそう", meaning: "solo (musik)", priority: "🔥" },
        { word: "合奏", reading: "がっそう", meaning: "ensemble, bermain bersama", priority: "🔥" },
        { word: "吹奏楽", reading: "すいそうがく", meaning: "musik band (tiup dan perkusi)", priority: "🔥" },
        { word: "奏効", reading: "そうこう", meaning: "efektif (obat/tindakan)", priority: "⭐" },
        { word: "協奏曲", reading: "きょうそうきょく", meaning: "concerto", priority: "🔥" },
        { word: "奏楽", reading: "そうがく", meaning: "musik/alunan musik", priority: "⭐" },
      ],
      family: "演奏・伴奏・独奏・合奏 → berbagai jenis 'memainkan musik'. 吹奏楽・協奏曲 → genre musik.",
      onyomi_pattern: "ソウ: 演奏(そう)、独奏(そう)、協奏曲(そう)。 ~100% sebagai ソウ.",
      quiz: [
        { type: "baca", question: "伴奏", answer: "ばんそう", hint: "iringan musik" },
        { type: "arti", question: "吹奏楽", answer: "musik band tiup dan perkusi", hint: "吹=meniup、楽=musik" },
        { type: "kanji", question: "どくそう (solo)", answer: "独奏", hint: "独=sendiri" },
        { type: "baca", question: "合奏", answer: "がっそう", hint: "ensemble" },
        { type: "arti", question: "協奏曲", answer: "concerto", hint: "協=bekerjasama" },
      ]
    },
    { kanji: "録", meaning_core: ["rekaman", "catatan", "mendaftarkan"], onyomi: "ロク", kunyomi: "-",
      jukugo: [
        { word: "記録", reading: "きろく", meaning: "catatan, rekaman, rekor", priority: "🔥" },
        { word: "録音", reading: "ろくおん", meaning: "rekaman suara", priority: "🔥" },
        { word: "録画", reading: "ろくが", meaning: "rekaman video", priority: "🔥" },
        { word: "登録", reading: "とうろく", meaning: "pendaftaran, registrasi", priority: "🔥" },
        { word: "収録", reading: "しゅうろく", meaning: "perekaman, pengumpulan", priority: "🔥" },
        { word: "目録", reading: "もくろく", meaning: "katalog, daftar barang", priority: "🔥" },
        { word: "付録", reading: "ふろく", meaning: "lampiran, suplemen", priority: "🔥" },
        { word: "回顧録", reading: "かいころく", meaning: "memoar", priority: "⭐" },
        { word: "採録", reading: "さいろく", meaning: "merekam/mencatat (untuk disimpan)", priority: "⭐" },
        { word: "議事録", reading: "ぎじろく", meaning: "risalah/notulen rapat", priority: "🔥" },
      ],
      family: "記録・録音・録画・収録 → berbagai jenis perekaman. 登録・目録 → pendaftaran/daftar.",
      onyomi_pattern: "ロク: 記録(ろく)、録音(ろく)、登録(ろく)。 ~100% sebagai ロク.",
      quiz: [
        { type: "baca", question: "登録", answer: "とうろく", hint: "pendaftaran" },
        { type: "arti", question: "議事録", answer: "risalah/notulen rapat", hint: "議事=urusan sidang" },
        { type: "kanji", question: "ふろく (lampiran)", answer: "付録", hint: "付=menambahkan" },
        { type: "baca", question: "収録", answer: "しゅうろく", hint: "perekaman" },
        { type: "arti", question: "目録", answer: "katalog, daftar barang", hint: "目=daftar/mata" },
      ]
    },
    { kanji: "喜", meaning_core: ["suka cita", "gembira", "senang"], onyomi: "キ", kunyomi: "よろこ(ぶ)、よろこ(び)",
      jukugo: [
        { word: "喜ぶ", reading: "よろこぶ", meaning: "merasa gembira", priority: "🔥" },
        { word: "喜び", reading: "よろこび", meaning: "kegembiraan, kebahagiaan", priority: "🔥" },
        { word: "歓喜", reading: "かんき", meaning: "kegirangan, sukacita besar", priority: "🔥" },
        { word: "喜劇", reading: "きげき", meaning: "komedi, drama lucu", priority: "🔥" },
        { word: "喜怒哀楽", reading: "きどあいらく", meaning: "suka duka kehidupan (4 emosi dasar)", priority: "🔥" },
        { word: "大喜び", reading: "おおよろこび", meaning: "sangat gembira", priority: "🔥" },
        { word: "お喜び", reading: "およろこび", meaning: "kegembiraan (hormat)", priority: "⭐" },
        { word: "喜寿", reading: "きじゅ", meaning: "ulang tahun ke-77 (perayaan khusus)", priority: "⭐" },
      ],
      family: "歓喜・大喜び → kegembiraan yang intens. 喜劇 → seni yang membuat orang senang. 喜怒哀楽 → empat emosi dasar manusia.",
      onyomi_pattern: "キ: 歓喜(き)、喜劇(き)。 Kunyomi よろこぶ/よろこび lebih dominan.",
      quiz: [
        { type: "baca", question: "歓喜", answer: "かんき", hint: "kegirangan" },
        { type: "arti", question: "喜怒哀楽", answer: "suka duka kehidupan (4 emosi)", hint: "哀=sedih、楽=senang" },
        { type: "kanji", question: "きげき (komedi)", answer: "喜劇", hint: "劇=drama" },
        { type: "baca", question: "大喜び", answer: "おおよろこび", hint: "sangat gembira" },
        { type: "arti", question: "喜寿", answer: "perayaan ulang tahun ke-77", hint: "寿=umur panjang" },
      ]
    },
    { kanji: "喫", meaning_core: ["makan/minum (kuno)", "merokok", "menderita"], onyomi: "キツ", kunyomi: "-",
      jukugo: [
        { word: "喫茶店", reading: "きっさてん", meaning: "kafe, kedai teh", priority: "🔥" },
        { word: "喫煙", reading: "きつえん", meaning: "merokok", priority: "🔥" },
        { word: "喫煙室", reading: "きつえんしつ", meaning: "ruang merokok", priority: "🔥" },
        { word: "禁煙喫煙", reading: "きんえんきつえん", meaning: "no smoking vs smoking", priority: "⭐" },
        { word: "喫水", reading: "きっすい", meaning: "draft (kedalaman kapal di air)", priority: "⭐" },
        { word: "満喫", reading: "まんきつ", meaning: "menikmati sepenuhnya", priority: "🔥" },
        { word: "喫緊", reading: "きっきん", meaning: "mendesak, urgent", priority: "🔥" },
        { word: "喫飯", reading: "きっぱん", meaning: "makan (kuno/sastra)", priority: "○" },
      ],
      family: "喫茶店・喫煙 → konteks 'minum/merokok'. 満喫 → menikmati sepenuhnya. 喫緊 → situasi mendesak.",
      onyomi_pattern: "キツ: 喫茶店(きつ→きっ)、喫煙(きつ)、満喫(きつ)。 100% sebagai キツ.",
      quiz: [
        { type: "baca", question: "喫茶店", answer: "きっさてん", hint: "kafe" },
        { type: "arti", question: "満喫", answer: "menikmati sepenuhnya", hint: "満=penuh" },
        { type: "kanji", question: "きつえん (merokok)", answer: "喫煙", hint: "煙=asap" },
        { type: "baca", question: "喫緊", answer: "きっきん", hint: "mendesak" },
        { type: "arti", question: "喫煙室", answer: "ruang merokok", hint: "室=ruangan" },
      ]
    },
    { kanji: "誕", meaning_core: ["lahir", "kelahiran (raja/khusus)"], onyomi: "タン", kunyomi: "-",
      jukugo: [
        { word: "誕生", reading: "たんじょう", meaning: "kelahiran, lahirnya sesuatu", priority: "🔥" },
        { word: "誕生日", reading: "たんじょうび", meaning: "hari ulang tahun", priority: "🔥" },
        { word: "誕生パーティー", reading: "たんじょうパーティー", meaning: "pesta ulang tahun", priority: "🔥" },
        { word: "生誕", reading: "せいたん", meaning: "kelahiran (tokoh besar/agama)", priority: "🔥" },
        { word: "誕生石", reading: "たんじょうせき", meaning: "batu kelahiran (birthstone)", priority: "⭐" },
        { word: "降誕", reading: "こうたん", meaning: "turunnya/lahirnya (agama, Natal)", priority: "⭐" },
      ],
      family: "誕生・生誕・降誕 → semua berkaitan dengan kelahiran dalam konteks yang berbeda.",
      onyomi_pattern: "タン: 誕生(たん)、生誕(たん)。 100% sebagai タン.",
      quiz: [
        { type: "baca", question: "誕生日", answer: "たんじょうび", hint: "hari ulang tahun" },
        { type: "arti", question: "生誕", answer: "kelahiran (tokoh besar)", hint: "生=hidup/lahir" },
        { type: "kanji", question: "たんじょう (kelahiran)", answer: "誕生", hint: "生=lahir" },
        { type: "baca", question: "降誕", answer: "こうたん", hint: "Natal/kelahiran agama" },
        { type: "arti", question: "誕生石", answer: "batu kelahiran (birthstone)", hint: "石=batu" },
      ]
    },
    { kanji: "許", meaning_core: ["mengizinkan", "memaafkan", "ijin"], onyomi: "キョ", kunyomi: "ゆる(す)、ゆる(し)",
      jukugo: [
        { word: "許可", reading: "きょか", meaning: "izin, persetujuan", priority: "🔥" },
        { word: "許す", reading: "ゆるす", meaning: "memaafkan, mengizinkan", priority: "🔥" },
        { word: "免許", reading: "めんきょ", meaning: "lisensi, SIM, ijin resmi", priority: "🔥" },
        { word: "特許", reading: "とっきょ", meaning: "paten", priority: "🔥" },
        { word: "認許", reading: "にんきょ", meaning: "persetujuan resmi", priority: "⭐" },
        { word: "許容", reading: "きょよう", meaning: "toleransi, penerimaan", priority: "🔥" },
        { word: "許諾", reading: "きょだく", meaning: "persetujuan, consent", priority: "⭐" },
        { word: "不許可", reading: "ふきょか", meaning: "ditolak, tidak diizinkan", priority: "🔥" },
        { word: "許可証", reading: "きょかしょう", meaning: "surat izin, permit", priority: "🔥" },
        { word: "黙許", reading: "もっきょ", meaning: "toleransi diam-diam (tanpa izin eksplisit)", priority: "○" },
      ],
      family: "許可・特許・免許 → jenis-jenis 'izin resmi'. 許す・許容 → 'memaafkan/toleransi'. 不許可 → kebalikannya.",
      onyomi_pattern: "キョ: 許可(きょ)、免許(きょ)、特許(きょ→っきょ)。 ~100% sebagai キョ.",
      quiz: [
        { type: "baca", question: "免許", answer: "めんきょ", hint: "SIM, lisensi" },
        { type: "arti", question: "特許", answer: "paten", hint: "特=khusus/istimewa" },
        { type: "kanji", question: "きょか (izin)", answer: "許可", hint: "可=boleh/setuju" },
        { type: "baca", question: "許容", answer: "きょよう", hint: "toleransi" },
        { type: "arti", question: "許可証", answer: "surat izin, permit", hint: "証=bukti/sertifikat" },
      ]
    },
    { kanji: "負", meaning_core: ["kalah", "menanggung", "terluka", "berhutang"], onyomi: "フ", kunyomi: "ま(ける)、お(う)、お(われる)",
      jukugo: [
        { word: "負ける", reading: "まける", meaning: "kalah", priority: "🔥" },
        { word: "負担", reading: "ふたん", meaning: "beban, tanggungan", priority: "🔥" },
        { word: "負傷", reading: "ふしょう", meaning: "cedera, terluka", priority: "🔥" },
        { word: "勝負", reading: "しょうぶ", meaning: "pertandingan, kalah menang", priority: "🔥" },
        { word: "負債", reading: "ふさい", meaning: "hutang, kewajiban finansial", priority: "🔥" },
        { word: "自負", reading: "じふ", meaning: "percaya diri, bangga diri", priority: "🔥" },
        { word: "正負", reading: "せいふ", meaning: "positif dan negatif", priority: "⭐" },
        { word: "負荷", reading: "ふか", meaning: "beban, load (teknis)", priority: "🔥" },
        { word: "借金負け", reading: "しゃっきんまけ", meaning: "terkalahkan oleh hutang", priority: "○" },
        { word: "敗負", reading: "はいふ", meaning: "kekalahan", priority: "○" },
        { word: "引き分け負け", reading: "-", meaning: "-", priority: "○" },
      ],
      family: "負担・負荷・負債 → 'menanggung beban'. 負傷 → 'terluka/menderita'. 勝負 → pertandingan (menang-kalah).",
      onyomi_pattern: "フ: 負担(ふ)、負傷(ふ)、負債(ふ)。 Kunyomi まける saat sebagai kata kerja.",
      quiz: [
        { type: "baca", question: "負担", answer: "ふたん", hint: "beban/tanggungan" },
        { type: "arti", question: "勝負", answer: "pertandingan, kalah menang", hint: "勝=menang" },
        { type: "kanji", question: "ふしょう (cedera)", answer: "負傷", hint: "傷=luka" },
        { type: "baca", question: "負債", answer: "ふさい", hint: "hutang" },
        { type: "arti", question: "自負", answer: "percaya diri, bangga diri", hint: "自=diri sendiri" },
      ]
    },
    { kanji: "倒", meaning_core: ["roboh", "jatuh", "mengalahkan", "kolaps"], onyomi: "トウ", kunyomi: "たお(れる)、たお(す)",
      jukugo: [
        { word: "倒れる", reading: "たおれる", meaning: "jatuh, roboh, kolaps", priority: "🔥" },
        { word: "倒す", reading: "たおす", meaning: "menjatuhkan, mengalahkan", priority: "🔥" },
        { word: "転倒", reading: "てんとう", meaning: "terjatuh, tergelincir", priority: "🔥" },
        { word: "圧倒", reading: "あっとう", meaning: "mengalahkan secara mutlak, overwhelming", priority: "🔥" },
        { word: "打倒", reading: "だとう", meaning: "menggulingkan, mengalahkan", priority: "🔥" },
        { word: "面倒", reading: "めんどう", meaning: "repot, merepotkan; merawat", priority: "🔥" },
        { word: "倒産", reading: "とうさん", meaning: "kebangkrutan", priority: "🔥" },
        { word: "卒倒", reading: "そっとう", meaning: "pingsan, sinkop", priority: "🔥" },
        { word: "逆倒", reading: "ぎゃくとう", meaning: "terbalik, terjungkir", priority: "⭐" },
        { word: "圧倒的", reading: "あっとうてき", meaning: "mutlak, overwhelming", priority: "🔥" },
      ],
      family: "倒れる・転倒・卒倒 → fisik 'jatuh/roboh'. 圧倒・打倒 → mengalahkan seseorang. 倒産 → 'jatuh/bangkrut' secara finansial. 面倒 → 'repot'.",
      onyomi_pattern: "トウ: 転倒(とう)、圧倒(とう)、倒産(とう)。 ~100% sebagai トウ.",
      quiz: [
        { type: "baca", question: "面倒", answer: "めんどう", hint: "repot" },
        { type: "arti", question: "圧倒的", answer: "mutlak, overwhelming", hint: "圧=tekanan/mutlak" },
        { type: "kanji", question: "とうさん (bangkrut)", answer: "倒産", hint: "産=harta/industri" },
        { type: "baca", question: "打倒", answer: "だとう", hint: "menggulingkan" },
        { type: "arti", question: "卒倒", answer: "pingsan, sinkop", hint: "卒=tiba-tiba" },
      ]
    },
    { kanji: "域", meaning_core: ["wilayah", "daerah", "zona", "ranah"], onyomi: "イキ", kunyomi: "-",
      jukugo: [
        { word: "地域", reading: "ちいき", meaning: "daerah, wilayah, kawasan", priority: "🔥" },
        { word: "地域社会", reading: "ちいきしゃかい", meaning: "masyarakat lokal/komunitas", priority: "🔥" },
        { word: "区域", reading: "くいき", meaning: "zona, distrik", priority: "🔥" },
        { word: "領域", reading: "りょういき", meaning: "wilayah, domain, ranah", priority: "🔥" },
        { word: "地域性", reading: "ちいきせい", meaning: "karakteristik daerah", priority: "⭐" },
        { word: "全域", reading: "ぜんいき", meaning: "seluruh wilayah", priority: "🔥" },
        { word: "域外", reading: "いきがい", meaning: "di luar wilayah/yurisdiksi", priority: "⭐" },
        { word: "広域", reading: "こういき", meaning: "wilayah luas", priority: "🔥" },
        { word: "範囲域", reading: "はんいいき", meaning: "kisaran wilayah", priority: "○" },
        { word: "不可侵域", reading: "ふかしんいき", meaning: "wilayah yang tidak boleh disentuh", priority: "○" },
      ],
      family: "地域・区域・領域・全域 → berbagai jenis 'wilayah/kawasan'. 広域 → wilayah yang besar.",
      onyomi_pattern: "イキ: 地域(いき)、区域(いき)、領域(いき)。 100% sebagai イキ.",
      quiz: [
        { type: "baca", question: "領域", answer: "りょういき", hint: "domain/wilayah kekuasaan" },
        { type: "arti", question: "広域", answer: "wilayah luas", hint: "広=luas" },
        { type: "kanji", question: "ちいき (daerah)", answer: "地域", hint: "地=tanah/daerah" },
        { type: "baca", question: "区域", answer: "くいき", hint: "zona, distrik" },
        { type: "arti", question: "全域", answer: "seluruh wilayah", hint: "全=seluruh" },
      ]
    },
    { kanji: "娯", meaning_core: ["hiburan", "kesenangan"], onyomi: "ゴ", kunyomi: "-",
      jukugo: [
        { word: "娯楽", reading: "ごらく", meaning: "hiburan, rekreasi", priority: "🔥" },
        { word: "娯楽施設", reading: "ごらくしせつ", meaning: "fasilitas hiburan", priority: "🔥" },
        { word: "娯楽番組", reading: "ごらくばんぐみ", meaning: "acara hiburan (TV)", priority: "🔥" },
        { word: "娯楽映画", reading: "ごらくえいが", meaning: "film hiburan (bukan seni)", priority: "⭐" },
        { word: "大衆娯楽", reading: "たいしゅうごらく", meaning: "hiburan massa/populer", priority: "⭐" },
      ],
      family: "娯楽 adalah inti kata 'hiburan'. Semua jukugo turunan adalah spesifikasi jenis hiburan.",
      onyomi_pattern: "ゴ: 娯楽(ご). 100% sebagai ゴ. Selalu muncul bersama 楽.",
      quiz: [
        { type: "baca", question: "娯楽", answer: "ごらく", hint: "hiburan/rekreasi" },
        { type: "arti", question: "娯楽施設", answer: "fasilitas hiburan", hint: "施設=fasilitas" },
        { type: "kanji", question: "ごらくばんぐみ (acara hiburan)", answer: "娯楽番組", hint: "番組=acara/program" },
        { type: "baca", question: "大衆娯楽", answer: "たいしゅうごらく", hint: "hiburan massa" },
        { type: "arti", question: "娯楽映画", answer: "film hiburan", hint: "映画=film" },
      ]
    },
    { kanji: "仲", meaning_core: ["hubungan antar orang", "teman dekat", "tengah"], onyomi: "チュウ", kunyomi: "なか",
      jukugo: [
        { word: "仲間", reading: "なかま", meaning: "teman, rekan, kelompok", priority: "🔥" },
        { word: "仲良し", reading: "なかよし", meaning: "berteman baik, akrab", priority: "🔥" },
        { word: "仲裁", reading: "ちゅうさい", meaning: "arbitrase, mediasi", priority: "🔥" },
        { word: "仲介", reading: "ちゅうかい", meaning: "perantara, mediasi", priority: "🔥" },
        { word: "仲直り", reading: "なかなおり", meaning: "berbaikan, rekonsiliasi", priority: "🔥" },
        { word: "仲たがい", reading: "なかたがい", meaning: "bertengkar, berselisih", priority: "🔥" },
        { word: "兄弟仲", reading: "きょうだいなか", meaning: "hubungan antar saudara", priority: "⭐" },
        { word: "仲人", reading: "なこうど", meaning: "mak comblang, perantara pernikahan", priority: "🔥" },
        { word: "仲買", reading: "なかがい", meaning: "broker, perantara dagang", priority: "⭐" },
      ],
      family: "仲間・仲良し → hubungan 'teman'. 仲裁・仲介・仲人 → peran 'perantara'. 仲直り・仲たがい → perubahan hubungan (baik/buruk).",
      onyomi_pattern: "チュウ: 仲裁(ちゅう)、仲介(ちゅう)。 Kunyomi なか lebih dominan dalam percakapan.",
      quiz: [
        { type: "baca", question: "仲介", answer: "ちゅうかい", hint: "perantara/mediasi" },
        { type: "arti", question: "仲直り", answer: "berbaikan, rekonsiliasi", hint: "直り=menjadi lurus/baik" },
        { type: "kanji", question: "なかま (teman/kelompok)", answer: "仲間", hint: "間=diantara/jarak" },
        { type: "baca", question: "仲裁", answer: "ちゅうさい", hint: "arbitrase" },
        { type: "arti", question: "仲人", answer: "mak comblang, perantara pernikahan", hint: "人=orang" },
      ]
    },
    { kanji: "憶", meaning_core: ["ingatan", "mengingat", "memori"], onyomi: "オク", kunyomi: "-",
      jukugo: [
        { word: "記憶", reading: "きおく", meaning: "ingatan, memori", priority: "🔥" },
        { word: "追憶", reading: "ついおく", meaning: "kenangan, nostalgia", priority: "🔥" },
        { word: "回憶", reading: "かいおく", meaning: "kilas balik, mengenang", priority: "⭐" },
        { word: "記憶力", reading: "きおくりょく", meaning: "daya ingat", priority: "🔥" },
        { word: "記憶喪失", reading: "きおくそうしつ", meaning: "amnesia", priority: "🔥" },
        { word: "憶測", reading: "おくそく", meaning: "spekulasi, dugaan tanpa dasar", priority: "🔥" },
        { word: "憶念", reading: "おくねん", meaning: "pemikiran tentang kenangan", priority: "○" },
        { word: "臆病", reading: "おくびょう", meaning: "pengecut, penakut", priority: "🔥" },
      ],
      family: "記憶・追憶・回憶 → berbagai bentuk 'mengingat masa lalu'. 憶測 → perkiraan tanpa dasar. 臆病 → 'gentar/kecut hati' (menggunakan kanji 臆 yang mirip).",
      onyomi_pattern: "オク: 記憶(おく)、追憶(おく)、憶測(おく)。 ~100% sebagai オク.",
      quiz: [
        { type: "baca", question: "記憶", answer: "きおく", hint: "ingatan" },
        { type: "arti", question: "憶測", answer: "spekulasi, dugaan tanpa dasar", hint: "測=mengukur/menduga" },
        { type: "kanji", question: "ついおく (kenangan)", answer: "追憶", hint: "追=mengejar/mengikuti" },
        { type: "baca", question: "記憶喪失", answer: "きおくそうしつ", hint: "amnesia" },
        { type: "arti", question: "記憶力", answer: "daya ingat", hint: "力=kekuatan/kemampuan" },
      ]
    },
    { kanji: "型", meaning_core: ["tipe", "model", "cetakan", "pola"], onyomi: "ケイ", kunyomi: "かた",
      jukugo: [
        { word: "型", reading: "かた", meaning: "cetakan, pola, tipe", priority: "🔥" },
        { word: "類型", reading: "るいけい", meaning: "kategori, pengelompokan tipe", priority: "🔥" },
        { word: "典型", reading: "てんけい", meaning: "tipikal, contoh klasik", priority: "🔥" },
        { word: "体型", reading: "たいけい", meaning: "bentuk tubuh", priority: "🔥" },
        { word: "血液型", reading: "けつえきがた", meaning: "golongan darah", priority: "🔥" },
        { word: "新型", reading: "しんがた", meaning: "model baru, tipe terbaru", priority: "🔥" },
        { word: "旧型", reading: "きゅうがた", meaning: "model lama", priority: "⭐" },
        { word: "小型", reading: "こがた", meaning: "ukuran kecil, tipe kecil", priority: "🔥" },
        { word: "大型", reading: "おおがた", meaning: "ukuran besar, tipe besar", priority: "🔥" },
        { word: "原型", reading: "げんけい", meaning: "prototipe, bentuk asli", priority: "🔥" },
        { word: "鋳型", reading: "いがた", meaning: "cetakan (logam)", priority: "⭐" },
        { word: "型破り", reading: "かたやぶり", meaning: "tidak biasa, out-of-the-box", priority: "🔥" },
      ],
      family: "血液型・小型・大型・新型 → tipe berdasarkan karakteristik. 典型・類型 → 'kategori/pengelompokan'. 型破り → keluar dari pola biasa.",
      onyomi_pattern: "ケイ: 典型(けい)、類型(けい)。 Kunyomi がた/かた dominan dalam percakapan (血液型・新型).",
      quiz: [
        { type: "baca", question: "典型", answer: "てんけい", hint: "tipikal/klasik" },
        { type: "arti", question: "型破り", answer: "tidak biasa, out-of-the-box", hint: "破り=memecahkan" },
        { type: "kanji", question: "けつえきがた (golongan darah)", answer: "血液型", hint: "血液=darah" },
        { type: "baca", question: "大型", answer: "おおがた", hint: "ukuran besar" },
        { type: "arti", question: "原型", answer: "prototipe, bentuk asli", hint: "原=asli/asal" },
      ]
    },
    { kanji: "財", meaning_core: ["kekayaan", "aset", "harta"], onyomi: "ザイ、サイ", kunyomi: "-",
      jukugo: [
        { word: "財産", reading: "ざいさん", meaning: "aset, kekayaan, warisan", priority: "🔥" },
        { word: "財政", reading: "ざいせい", meaning: "keuangan (pemerintah), fiskal", priority: "🔥" },
        { word: "財源", reading: "ざいげん", meaning: "sumber dana, pendanaan", priority: "🔥" },
        { word: "財務", reading: "ざいむ", meaning: "urusan keuangan, finance", priority: "🔥" },
        { word: "財団", reading: "ざいだん", meaning: "yayasan", priority: "🔥" },
        { word: "財閥", reading: "ざいばつ", meaning: "konglomerat (zaibatsu)", priority: "🔥" },
        { word: "文化財", reading: "ぶんかざい", meaning: "warisan budaya", priority: "🔥" },
        { word: "私財", reading: "しざい", meaning: "aset pribadi", priority: "⭐" },
        { word: "蓄財", reading: "ちくざい", meaning: "menumpuk kekayaan", priority: "⭐" },
        { word: "財布", reading: "さいふ", meaning: "dompet", priority: "🔥" },
      ],
      family: "財産・私財・蓄財 → kekayaan pribadi. 財政・財務・財源 → keuangan pemerintah/lembaga. 財団・財閥 → organisasi berbasis keuangan.",
      onyomi_pattern: "ザイ: 財産(ざい)、財政(ざい)、財源(ざい)。 サイ: 財布(さい→さいふ)。 Dominan ザイ (~90%).",
      quiz: [
        { type: "baca", question: "財政", answer: "ざいせい", hint: "keuangan pemerintah" },
        { type: "arti", question: "文化財", answer: "warisan budaya", hint: "文化=budaya" },
        { type: "kanji", question: "ざいさん (aset/kekayaan)", answer: "財産", hint: "産=menghasilkan/harta" },
        { type: "baca", question: "財閥", answer: "ざいばつ", hint: "konglomerat besar" },
        { type: "arti", question: "財布", answer: "dompet", hint: "布=kain/benda" },
      ]
    },
    { kanji: "酒", meaning_core: ["sake", "minuman beralkohol", "minuman keras"], onyomi: "シュ", kunyomi: "さけ、さか",
      jukugo: [
        { word: "酒", reading: "さけ", meaning: "sake, minuman beralkohol", priority: "🔥" },
        { word: "日本酒", reading: "にほんしゅ", meaning: "sake Jepang", priority: "🔥" },
        { word: "飲酒", reading: "いんしゅ", meaning: "minum alkohol", priority: "🔥" },
        { word: "禁酒", reading: "きんしゅ", meaning: "larangan minum alkohol, pantang", priority: "🔥" },
        { word: "飲酒運転", reading: "いんしゅうんてん", meaning: "mabuk berkendara, DUI", priority: "🔥" },
        { word: "酒類", reading: "しゅるい", meaning: "minuman beralkohol (sebagai kategori)", priority: "🔥" },
        { word: "酒屋", reading: "さかや", meaning: "toko minuman keras", priority: "🔥" },
        { word: "酒場", reading: "さかば", meaning: "bar, kedai minum", priority: "🔥" },
        { word: "洋酒", reading: "ようしゅ", meaning: "minuman keras Western (wine, whisky)", priority: "⭐" },
        { word: "酒癖", reading: "さけぐせ", meaning: "kebiasaan saat mabuk", priority: "⭐" },
        { word: "地酒", reading: "じざけ", meaning: "sake lokal/regional", priority: "⭐" },
      ],
      family: "日本酒・洋酒・地酒 → jenis-jenis minuman. 飲酒・禁酒・酒癖 → perilaku seputar alkohol. 酒屋・酒場 → tempat berkaitan alkohol.",
      onyomi_pattern: "シュ: 日本酒(しゅ)、飲酒(しゅ)、酒類(しゅ)。 Kunyomi さけ/さか saat berdiri sendiri.",
      quiz: [
        { type: "baca", question: "飲酒運転", answer: "いんしゅうんてん", hint: "mabuk berkendara" },
        { type: "arti", question: "地酒", answer: "sake lokal/regional", hint: "地=daerah/lokal" },
        { type: "kanji", question: "きんしゅ (pantang alkohol)", answer: "禁酒", hint: "禁=melarang" },
        { type: "baca", question: "酒類", answer: "しゅるい", hint: "kategori minuman keras" },
        { type: "arti", question: "酒場", answer: "bar, kedai minum", hint: "場=tempat" },
      ]
    },
    { kanji: "交", meaning_core: ["bertukar", "bergaul", "persimpangan", "berhubungan"], onyomi: "コウ", kunyomi: "ま(じる)、ま(ぜる)、か(わす)",
      jukugo: [
        { word: "交換", reading: "こうかん", meaning: "pertukaran, swap", priority: "🔥" },
        { word: "交通", reading: "こうつう", meaning: "lalu lintas, transportasi", priority: "🔥" },
        { word: "交流", reading: "こうりゅう", meaning: "pertukaran budaya/orang; arus AC", priority: "🔥" },
        { word: "交渉", reading: "こうしょう", meaning: "negosiasi, perundingan", priority: "🔥" },
        { word: "交際", reading: "こうさい", meaning: "hubungan sosial; berpacaran", priority: "🔥" },
        { word: "外交", reading: "がいこう", meaning: "diplomasi, hubungan luar negeri", priority: "🔥" },
        { word: "社交", reading: "しゃこう", meaning: "pergaulan sosial, bersosialisasi", priority: "🔥" },
        { word: "交代", reading: "こうたい", meaning: "pergantian, rotasi", priority: "🔥" },
        { word: "交差", reading: "こうさ", meaning: "bersilang, persimpangan", priority: "🔥" },
        { word: "性交", reading: "せいこう", meaning: "hubungan seksual (medis)", priority: "⭐" },
        { word: "国交", reading: "こっこう", meaning: "hubungan diplomatik", priority: "🔥" },
        { word: "混交", reading: "こんこう", meaning: "campuran, persilangan", priority: "⭐" },
        { word: "交響曲", reading: "こうきょうきょく", meaning: "simfoni", priority: "🔥" },
      ],
      family: "交換・交流・外交・社交 → berbagai jenis 'pertukaran'. 交通・交差 → bersilangnya jalur/gerakan. 交渉・交際・国交 → hubungan antar pihak.",
      onyomi_pattern: "コウ: 交換(こう)、交通(こう)、外交(こう)。 ~100% sebagai コウ.",
      quiz: [
        { type: "baca", question: "外交", answer: "がいこう", hint: "diplomasi" },
        { type: "arti", question: "交渉", answer: "negosiasi, perundingan", hint: "渉=melewati/terlibat" },
        { type: "kanji", question: "こうかん (pertukaran)", answer: "交換", hint: "換=mengganti" },
        { type: "baca", question: "国交", answer: "こっこう", hint: "hubungan diplomatik" },
        { type: "arti", question: "社交", answer: "pergaulan sosial", hint: "社=masyarakat" },
      ]
    },
    { kanji: "故", meaning_core: ["sebab", "alasan", "masa lalu", "mendiang"], onyomi: "コ、コ", kunyomi: "ゆえ、ふる(い)、こ(い)",
      jukugo: [
        { word: "故障", reading: "こしょう", meaning: "kerusakan, malfungsi", priority: "🔥" },
        { word: "事故", reading: "じこ", meaning: "kecelakaan, insiden", priority: "🔥" },
        { word: "故意", reading: "こい", meaning: "sengaja, dengan niat", priority: "🔥" },
        { word: "故人", reading: "こじん", meaning: "mendiang, almarhum", priority: "🔥" },
        { word: "故郷", reading: "こきょう", meaning: "kampung halaman", priority: "🔥" },
        { word: "原故", reading: "げんこ", meaning: "alasan, sebab (kuno)", priority: "○" },
        { word: "温故知新", reading: "おんこちしん", meaning: "belajar dari masa lalu untuk memahami masa kini", priority: "🔥" },
        { word: "典故", reading: "てんこ", meaning: "referensi sejarah/klasik", priority: "○" },
        { word: "故事", reading: "こじ", meaning: "kisah/anekdot sejarah", priority: "🔥" },
        { word: "縁故", reading: "えんこ", meaning: "koneksi, hubungan personal", priority: "⭐" },
      ],
      family: "事故・故障 → sesuatu yang 'rusak/terjadi tidak sengaja'. 故意 → sebaliknya (sengaja). 故人・故郷 → 'dulu/masa lalu'. 温故知新 → idiom belajar dari masa lalu.",
      onyomi_pattern: "コ: 故障(こ)、事故(こ)、故意(こ)、故人(こ)。 ~100% sebagai コ.",
      quiz: [
        { type: "baca", question: "事故", answer: "じこ", hint: "kecelakaan" },
        { type: "arti", question: "故意", answer: "sengaja, dengan niat", hint: "意=niat/pikiran" },
        { type: "kanji", question: "こきょう (kampung halaman)", answer: "故郷", hint: "郷=kampung/daerah" },
        { type: "baca", question: "温故知新", answer: "おんこちしん", hint: "belajar dari masa lalu" },
        { type: "arti", question: "故人", answer: "mendiang, almarhum", hint: "人=orang" },
      ]
    },
    { kanji: "飛", meaning_core: ["terbang", "melompat", "melayang"], onyomi: "ヒ", kunyomi: "と(ぶ)、と(ばす)",
      jukugo: [
        { word: "飛ぶ", reading: "とぶ", meaning: "terbang, melompat", priority: "🔥" },
        { word: "飛行機", reading: "ひこうき", meaning: "pesawat terbang", priority: "🔥" },
        { word: "飛行", reading: "ひこう", meaning: "penerbangan, terbang", priority: "🔥" },
        { word: "飛躍", reading: "ひやく", meaning: "lompatan besar, kemajuan pesat", priority: "🔥" },
        { word: "飛来", reading: "ひらい", meaning: "terbang dan datang", priority: "⭐" },
        { word: "飛距離", reading: "ひきょり", meaning: "jarak tempuh (terbang/bola golf)", priority: "⭐" },
        { word: "飛び込む", reading: "とびこむ", meaning: "terjun, menceburkan diri", priority: "🔥" },
        { word: "吹き飛ぶ", reading: "ふきとぶ", meaning: "terbang karena angin, menghilang seketika", priority: "🔥" },
        { word: "飛び出す", reading: "とびだす", meaning: "melompat keluar, muncul tiba-tiba", priority: "🔥" },
        { word: "飛び越える", reading: "とびこえる", meaning: "melompati, melampaui", priority: "🔥" },
        { word: "奇飛", reading: "きひ", meaning: "terbang aneh (jarang dipakai)", priority: "○" },
      ],
      family: "飛行機・飛行 → konteks 'terbang'. 飛躍 → 'lompatan' kemajuan. 飛び込む・飛び出す・飛び越える → berbagai aksi 'terbang/melompat'.",
      onyomi_pattern: "ヒ: 飛行(ひ)、飛躍(ひ)。 Kunyomi とぶ/とばす dominan.",
      quiz: [
        { type: "baca", question: "飛行機", answer: "ひこうき", hint: "pesawat terbang" },
        { type: "arti", question: "飛躍", answer: "lompatan besar, kemajuan pesat", hint: "躍=melompat" },
        { type: "kanji", question: "とびこむ (terjun)", answer: "飛び込む", hint: "込む=masuk/terbenam" },
        { type: "baca", question: "飛来", answer: "ひらい", hint: "terbang dan datang" },
        { type: "arti", question: "飛び越える", answer: "melompati, melampaui", hint: "越える=melampaui" },
      ]
    },
    { kanji: "庭", meaning_core: ["halaman", "taman", "rumah tangga"], onyomi: "テイ", kunyomi: "にわ",
      jukugo: [
        { word: "庭", reading: "にわ", meaning: "halaman, taman", priority: "🔥" },
        { word: "庭園", reading: "ていえん", meaning: "taman (yang tertata)", priority: "🔥" },
        { word: "庭師", reading: "にわし", meaning: "tukang taman, paisajis", priority: "🔥" },
        { word: "家庭", reading: "かてい", meaning: "keluarga, rumah tangga", priority: "🔥" },
        { word: "家庭的", reading: "かていてき", meaning: "homey, bersifat rumah tangga", priority: "🔥" },
        { word: "法廷", reading: "ほうてい", meaning: "pengadilan", priority: "🔥" },
        { word: "宮廷", reading: "きゅうてい", meaning: "istana, kerajaan", priority: "🔥" },
        { word: "中庭", reading: "なかにわ", meaning: "taman tengah, inner court", priority: "🔥" },
        { word: "前庭", reading: "ぜんてい", meaning: "halaman depan, vestibulum", priority: "⭐" },
        { word: "裏庭", reading: "うらにわ", meaning: "halaman belakang", priority: "🔥" },
      ],
      family: "庭・庭園・中庭・前庭・裏庭 → berbagai jenis taman/halaman. 家庭・法廷・宮廷 → 'lingkup/arena' suatu aktivitas.",
      onyomi_pattern: "テイ: 庭園(てい)、家庭(てい)、宮廷(てい)。 Kunyomi にわ untuk taman fisik.",
      quiz: [
        { type: "baca", question: "家庭", answer: "かてい", hint: "keluarga/rumah tangga" },
        { type: "arti", question: "宮廷", answer: "istana, kerajaan", hint: "宮=istana" },
        { type: "kanji", question: "ていえん (taman tertata)", answer: "庭園", hint: "園=taman/kebun" },
        { type: "baca", question: "中庭", answer: "なかにわ", hint: "taman tengah" },
        { type: "arti", question: "法廷", answer: "pengadilan", hint: "法=hukum" },
      ]
    },
    { kanji: "患", meaning_core: ["penyakit", "khawatir", "menderita"], onyomi: "カン", kunyomi: "わずら(う)",
      jukugo: [
        { word: "患者", reading: "かんじゃ", meaning: "pasien", priority: "🔥" },
        { word: "疾患", reading: "しっかん", meaning: "penyakit (istilah medis)", priority: "🔥" },
        { word: "患う", reading: "わずらう", meaning: "menderita penyakit, sakit", priority: "🔥" },
        { word: "心患い", reading: "こころわずらい", meaning: "kekhawatiran, gundah gulana", priority: "⭐" },
        { word: "患難", reading: "かんなん", meaning: "kesukaran, musibah", priority: "⭐" },
        { word: "内患", reading: "ないかん", meaning: "masalah dalam negeri", priority: "○" },
        { word: "外患", reading: "がいかん", meaning: "ancaman dari luar", priority: "○" },
        { word: "完患", reading: "-", meaning: "-", priority: "○" },
      ],
      family: "患者・疾患 → konteks medis. 患う・心患い → 'menderita/khawatir'. 患難 → kesukaran/musibah.",
      onyomi_pattern: "カン: 患者(かん)、疾患(かん)。 Kunyomi わずらう untuk kata kerja.",
      quiz: [
        { type: "baca", question: "患者", answer: "かんじゃ", hint: "pasien" },
        { type: "arti", question: "疾患", answer: "penyakit (istilah medis)", hint: "疾=penyakit" },
        { type: "kanji", question: "かんじゃ (pasien)", answer: "患者", hint: "者=orang" },
        { type: "baca", question: "患難", answer: "かんなん", hint: "kesukaran, musibah" },
        { type: "arti", question: "患う", answer: "menderita penyakit, sakit", hint: "bentuk kata kerja" },
      ]
    },
    { kanji: "活", meaning_core: ["aktif", "hidup", "bersemangat", "aktivitas"], onyomi: "カツ", kunyomi: "-",
      jukugo: [
        { word: "活動", reading: "かつどう", meaning: "aktivitas, kegiatan", priority: "🔥" },
        { word: "生活", reading: "せいかつ", meaning: "kehidupan sehari-hari, cara hidup", priority: "🔥" },
        { word: "活用", reading: "かつよう", meaning: "pemanfaatan; konjugasi (tata bahasa)", priority: "🔥" },
        { word: "活発", reading: "かっぱつ", meaning: "aktif, bersemangat, energik", priority: "🔥" },
        { word: "活躍", reading: "かつやく", meaning: "berperan aktif, tampil gemilang", priority: "🔥" },
        { word: "活力", reading: "かつりょく", meaning: "vitalitas, energi", priority: "🔥" },
        { word: "活性化", reading: "かっせいか", meaning: "aktivasi, merevitalisasi", priority: "🔥" },
        { word: "復活", reading: "ふっかつ", meaning: "kebangkitan kembali, revival", priority: "🔥" },
        { word: "就活", reading: "しゅうかつ", meaning: "pencarian kerja (aktivitas)", priority: "🔥" },
        { word: "部活", reading: "ぶかつ", meaning: "kegiatan klub (sekolah)", priority: "🔥" },
        { word: "活字", reading: "かつじ", meaning: "huruf cetak", priority: "⭐" },
        { word: "活気", reading: "かっき", meaning: "semangat, kegairahan", priority: "🔥" },
      ],
      family: "活動・活発・活気・活力・活躍 → berbagai aspek 'keaktifan'. 生活・就活・部活 → konteks 'kehidupan/aktivitas'. 復活・活性化 → memulihkan keaktifan.",
      onyomi_pattern: "カツ: 活動(かつ)、生活(かつ)、復活(かつ)。 ~100% sebagai カツ.",
      quiz: [
        { type: "baca", question: "生活", answer: "せいかつ", hint: "kehidupan sehari-hari" },
        { type: "arti", question: "就活", answer: "pencarian kerja", hint: "就=mendapatkan pekerjaan" },
        { type: "kanji", question: "ふっかつ (kebangkitan)", answer: "復活", hint: "復=kembali" },
        { type: "baca", question: "活躍", answer: "かつやく", hint: "berperan aktif" },
        { type: "arti", question: "活性化", answer: "aktivasi, merevitalisasi", hint: "性=sifat、化=menjadi/-isasi" },
      ]
    },
    { kanji: "果", meaning_core: ["buah", "hasil", "akhirnya", "terwujud"], onyomi: "カ", kunyomi: "は(てる)、はた(す)、くだもの",
      jukugo: [
        { word: "結果", reading: "けっか", meaning: "hasil, akibat", priority: "🔥" },
        { word: "果物", reading: "くだもの", meaning: "buah-buahan", priority: "🔥" },
        { word: "成果", reading: "せいか", meaning: "pencapaian, hasil", priority: "🔥" },
        { word: "効果", reading: "こうか", meaning: "efek, dampak", priority: "🔥" },
        { word: "果たす", reading: "はたす", meaning: "memenuhi, melaksanakan", priority: "🔥" },
        { word: "因果", reading: "いんが", meaning: "sebab akibat, karma", priority: "🔥" },
        { word: "果敢", reading: "かかん", meaning: "berani, tegas, tidak ragu", priority: "🔥" },
        { word: "果汁", reading: "かじゅう", meaning: "sari buah, jus", priority: "🔥" },
        { word: "果実", reading: "かじつ", meaning: "buah (istilah formal/ilmiah)", priority: "🔥" },
        { word: "自業自得", reading: "じごうじとく", meaning: "menerima akibat perbuatan sendiri", priority: "🔥" },
        { word: "対果", reading: "たいか", meaning: "hubungan sebab akibat langsung", priority: "○" },
        { word: "果てしない", reading: "はてしない", meaning: "tidak terbatas, tanpa batas", priority: "🔥" },
      ],
      family: "結果・成果・効果・因果 → berbagai aspek 'sebab dan akibat/hasil'. 果物・果実・果汁 → buah dan produk buah. 果たす・果敢 → 'melaksanakan/berani'.",
      onyomi_pattern: "カ: 結果(か)、成果(か)、効果(か)、果実(か)。 ~100% sebagai カ.",
      quiz: [
        { type: "baca", question: "効果", answer: "こうか", hint: "efek, dampak" },
        { type: "arti", question: "因果", answer: "sebab akibat, karma", hint: "因=sebab" },
        { type: "kanji", question: "せいか (pencapaian)", answer: "成果", hint: "成=berhasil/menjadi" },
        { type: "baca", question: "果敢", answer: "かかん", hint: "berani, tegas" },
        { type: "arti", question: "果てしない", answer: "tidak terbatas, tanpa batas", hint: "果て=ujung/akhir" },
      ]
    },
    { kanji: "奇", meaning_core: ["aneh", "menakjubkan", "ganjil", "luar biasa"], onyomi: "キ", kunyomi: "く(しい)",
      jukugo: [
        { word: "奇妙", reading: "きみょう", meaning: "aneh, ganjil", priority: "🔥" },
        { word: "奇跡", reading: "きせき", meaning: "keajaiban, mukjizat", priority: "🔥" },
        { word: "好奇心", reading: "こうきしん", meaning: "rasa ingin tahu", priority: "🔥" },
        { word: "奇術", reading: "きじゅつ", meaning: "sulap, trik aneh", priority: "🔥" },
        { word: "奇数", reading: "きすう", meaning: "bilangan ganjil", priority: "🔥" },
        { word: "奇想天外", reading: "きそうてんがい", meaning: "ide yang sangat aneh/tidak terduga", priority: "🔥" },
        { word: "奇遇", reading: "きぐう", meaning: "kebetulan yang mengejutkan", priority: "🔥" },
        { word: "奇抜", reading: "きばつ", meaning: "eksentrik, unik sekali", priority: "🔥" },
        { word: "奇才", reading: "きさい", meaning: "bakat yang luar biasa, jenius", priority: "⭐" },
        { word: "猟奇", reading: "りょうき", meaning: "kegilaan, kecenderungan patologis", priority: "⭐" },
      ],
      family: "奇妙・奇抜・奇術・猟奇 → berbagai aspek 'keanehan'. 奇跡 → sesuatu yang luar biasa/ajaib. 好奇心 → rasa ingin tahu terhadap hal aneh.",
      onyomi_pattern: "キ: 奇妙(き)、奇跡(き)、好奇心(き)。 ~100% sebagai キ.",
      quiz: [
        { type: "baca", question: "好奇心", answer: "こうきしん", hint: "rasa ingin tahu" },
        { type: "arti", question: "奇跡", answer: "keajaiban, mukjizat", hint: "跡=jejak/bekas" },
        { type: "kanji", question: "きみょう (aneh)", answer: "奇妙", hint: "妙=menakjubkan/aneh" },
        { type: "baca", question: "奇数", answer: "きすう", hint: "bilangan ganjil" },
        { type: "arti", question: "奇抜", answer: "eksentrik, unik sekali", hint: "抜=luar biasa/cabut" },
      ]
    },
  ]
};
