
// ========== PERTEMUAN 10 ==========
const pertemuan10 = {
  id: 10, title: "Pertemuan 10",
  kanji: [
    { kanji:"修", meaning_core:["memperbaiki","belajar","berlatih","merawat"], onyomi:"シュウ、シュ", kunyomi:"おさ(める)、おさ(まる)",
      jukugo:[
        {word:"修理",reading:"しゅうり",meaning:"perbaikan",priority:"🔥"},
        {word:"修正",reading:"しゅうせい",meaning:"koreksi, revisi",priority:"🔥"},
        {word:"研修",reading:"けんしゅう",meaning:"pelatihan, training",priority:"🔥"},
        {word:"修学旅行",reading:"しゅうがくりょこう",meaning:"study tour, wisata edukasi",priority:"🔥"},
        {word:"修了",reading:"しゅうりょう",meaning:"penyelesaian kursus/program",priority:"🔥"},
        {word:"修復",reading:"しゅうふく",meaning:"restorasi, pemulihan",priority:"🔥"},
        {word:"修業",reading:"しゅうぎょう",meaning:"latihan/pelatihan keterampilan",priority:"🔥"},
        {word:"修士",reading:"しゅうし",meaning:"master (gelar S2)",priority:"🔥"},
        {word:"修行",reading:"しゅぎょう",meaning:"latihan spiritual, asketisme",priority:"🔥"},
        {word:"修飾",reading:"しゅうしょく",meaning:"modifikasi (tata bahasa), dekorasi",priority:"🔥"},
        {word:"改修",reading:"かいしゅう",meaning:"renovasi, perbaikan",priority:"🔥"},
      ],
      family:"修理・修正・修復・改修 → berbagai jenis 'perbaikan/restorasi'. 研修・修業・修行 → 'berlatih/belajar'. 修士 → gelar akademis.",
      onyomi_pattern:"シュウ: 修理(しゅう)、研修(しゅう)、修正(しゅう)。 シュ: 修行(しゅ)。 Dominan シュウ.",
      quiz:[
        {type:"baca",question:"研修",answer:"けんしゅう",hint:"pelatihan/training"},
        {type:"arti",question:"修学旅行",answer:"study tour, wisata edukasi",hint:"修学=belajar"},
        {type:"kanji",question:"しゅうし (gelar S2)",answer:"修士",hint:"士=orang terlatih"},
        {type:"baca",question:"修行",answer:"しゅぎょう",hint:"latihan spiritual"},
        {type:"arti",question:"修飾",answer:"modifikasi (tata bahasa), dekorasi",hint:"飾=menghias"},
      ]
    },
    { kanji:"費", meaning_core:["biaya","pengeluaran","menghabiskan"], onyomi:"ヒ", kunyomi:"つい(やす)、つい(える)",
      jukugo:[
        {word:"費用",reading:"ひよう",meaning:"biaya, pengeluaran",priority:"🔥"},
        {word:"消費",reading:"しょうひ",meaning:"konsumsi, penggunaan",priority:"🔥"},
        {word:"経費",reading:"けいひ",meaning:"biaya operasional",priority:"🔥"},
        {word:"学費",reading:"がくひ",meaning:"biaya pendidikan/kuliah",priority:"🔥"},
        {word:"食費",reading:"しょくひ",meaning:"biaya makan",priority:"🔥"},
        {word:"交通費",reading:"こうつうひ",meaning:"biaya transportasi",priority:"🔥"},
        {word:"医療費",reading:"いりょうひ",meaning:"biaya medis/kesehatan",priority:"🔥"},
        {word:"浪費",reading:"ろうひ",meaning:"pemborosan",priority:"🔥"},
        {word:"節費",reading:"せつひ",meaning:"penghematan biaya",priority:"⭐"},
        {word:"諸費",reading:"しょひ",meaning:"berbagai biaya/pengeluaran",priority:"⭐"},
        {word:"実費",reading:"じっぴ",meaning:"biaya aktual/nyata",priority:"🔥"},
      ],
      family:"費用・経費・学費・食費 → berbagai jenis 'biaya'. 消費・浪費 → cara 'menghabiskan/mengeluarkan'.",
      onyomi_pattern:"ヒ: 費用(ひ)、消費(ひ)、経費(ひ)、学費(ひ)。 ~100% sebagai ヒ.",
      quiz:[
        {type:"baca",question:"消費",answer:"しょうひ",hint:"konsumsi"},
        {type:"arti",question:"浪費",answer:"pemborosan",hint:"浪=ombak/mengalir liar"},
        {type:"kanji",question:"こうつうひ (biaya transportasi)",answer:"交通費",hint:"交通=lalu lintas"},
        {type:"baca",question:"経費",answer:"けいひ",hint:"biaya operasional"},
        {type:"arti",question:"実費",answer:"biaya aktual/nyata",hint:"実=nyata/sesungguhnya"},
      ]
    },
    { kanji:"陽", meaning_core:["matahari","positif","sisi terang","yang"], onyomi:"ヨウ", kunyomi:"ひ",
      jukugo:[
        {word:"太陽",reading:"たいよう",meaning:"matahari",priority:"🔥"},
        {word:"陽気",reading:"ようき",meaning:"ceria, riang; iklim/cuaca",priority:"🔥"},
        {word:"陰陽",reading:"いんよう",meaning:"yin dan yang",priority:"🔥"},
        {word:"陽性",reading:"ようせい",meaning:"positif (tes)",priority:"🔥"},
        {word:"陽光",reading:"ようこう",meaning:"sinar matahari",priority:"🔥"},
        {word:"夕陽",reading:"ゆうひ",meaning:"matahari terbenam",priority:"🔥"},
        {word:"陽射し",reading:"ひざし",meaning:"sinar matahari (yang terasa)",priority:"🔥"},
        {word:"太陽光",reading:"たいようこう",meaning:"sinar surya",priority:"🔥"},
        {word:"太陽系",reading:"たいようけい",meaning:"tata surya",priority:"🔥"},
        {word:"春陽",reading:"しゅんよう",meaning:"sinar musim semi",priority:"○"},
      ],
      family:"太陽・陽光・夕陽 → berkaitan dengan 'matahari'. 陽気・陽性 → keceriaan/hasil positif.",
      onyomi_pattern:"ヨウ: 太陽(よう)、陽気(よう)、陽性(よう)。 Kunyomi ひ dalam 夕陽・陽射し.",
      quiz:[
        {type:"baca",question:"太陽",answer:"たいよう",hint:"matahari"},
        {type:"arti",question:"陽性",answer:"positif (tes)",hint:"性=sifat/karakter"},
        {type:"kanji",question:"たいようけい (tata surya)",answer:"太陽系",hint:"系=sistem/rangkaian"},
        {type:"baca",question:"陽気",answer:"ようき",hint:"ceria/riang"},
        {type:"arti",question:"陰陽",answer:"yin dan yang",hint:"陰=bayangan/negatif"},
      ]
    },
    { kanji:"抵", meaning_core:["menolak","setara","bertahan"], onyomi:"テイ", kunyomi:"-",
      jukugo:[
        {word:"抵抗",reading:"ていこう",meaning:"perlawanan, resistensi",priority:"🔥"},
        {word:"大抵",reading:"たいてい",meaning:"biasanya, umumnya",priority:"🔥"},
        {word:"抵触",reading:"ていしょく",meaning:"bertentangan, konflik (hukum)",priority:"🔥"},
        {word:"抵当",reading:"ていとう",meaning:"jaminan, agunan (pinjaman)",priority:"🔥"},
        {word:"低抵",reading:"ていてい",meaning:"(jarang) tingkat rendah",priority:"○"},
      ],
      family:"抵抗・抵触 → 'menolak/bertentangan'. 抵当 → 'jaminan'. 大抵 → penggunaan umum sehari-hari.",
      onyomi_pattern:"テイ: 抵抗(てい)、大抵(たい+てい)。 100% sebagai テイ.",
      quiz:[
        {type:"baca",question:"抵抗",answer:"ていこう",hint:"perlawanan/resistensi"},
        {type:"arti",question:"大抵",answer:"biasanya, umumnya",hint:"大=besar/umum"},
        {type:"kanji",question:"ていとう (agunan)",answer:"抵当",hint:"当=mengenai"},
        {type:"baca",question:"抵触",answer:"ていしょく",hint:"bertentangan"},
        {type:"arti",question:"抵抗",answer:"perlawanan, resistensi",hint:"抵=menolak、抗=melawan"},
      ]
    },
    { kanji:"抗", meaning_core:["melawan","menolak","resistensi"], onyomi:"コウ", kunyomi:"-",
      jukugo:[
        {word:"抵抗",reading:"ていこう",meaning:"perlawanan, resistensi",priority:"🔥"},
        {word:"反抗",reading:"はんこう",meaning:"pemberontakan, pembangkangan",priority:"🔥"},
        {word:"抗議",reading:"こうぎ",meaning:"protes, keberatan formal",priority:"🔥"},
        {word:"抗体",reading:"こうたい",meaning:"antibodi",priority:"🔥"},
        {word:"抗生物質",reading:"こうせいぶっしつ",meaning:"antibiotik",priority:"🔥"},
        {word:"対抗",reading:"たいこう",meaning:"melawan, bersaing",priority:"🔥"},
        {word:"抵抗力",reading:"ていこうりょく",meaning:"daya tahan, imunitas",priority:"🔥"},
        {word:"拮抗",reading:"きっこう",meaning:"antagonisme, persaingan ketat",priority:"⭐"},
        {word:"抗争",reading:"こうそう",meaning:"konflik, pertengkaran",priority:"🔥"},
        {word:"抗癌",reading:"こうがん",meaning:"anti-kanker",priority:"⭐"},
      ],
      family:"抵抗・反抗・対抗・抗争 → berbagai jenis 'perlawanan'. 抗議 → protes verbal. 抗体・抗生物質 → istilah medis 'melawan penyakit'.",
      onyomi_pattern:"コウ: 反抗(こう)、抗議(こう)、抗体(こう)。 ~100% sebagai コウ.",
      quiz:[
        {type:"baca",question:"反抗",answer:"はんこう",hint:"pembangkangan"},
        {type:"arti",question:"抗体",answer:"antibodi",hint:"体=tubuh"},
        {type:"kanji",question:"こうぎ (protes)",answer:"抗議",hint:"議=berdiskusi/protes"},
        {type:"baca",question:"対抗",answer:"たいこう",hint:"bersaing/melawan"},
        {type:"arti",question:"抗生物質",answer:"antibiotik",hint:"生=hidup、物質=zat"},
      ]
    },
    { kanji:"涼", meaning_core:["sejuk","segar","sepoi"], onyomi:"リョウ", kunyomi:"すず(しい)、すず(む)",
      jukugo:[
        {word:"涼しい",reading:"すずしい",meaning:"sejuk, segar (udara)",priority:"🔥"},
        {word:"涼む",reading:"すずむ",meaning:"menikmati udara sejuk",priority:"🔥"},
        {word:"涼風",reading:"りょうふう",meaning:"angin sepoi-sepoi yang sejuk",priority:"🔥"},
        {word:"清涼",reading:"せいりょう",meaning:"segar, sejuk dan bersih",priority:"🔥"},
        {word:"冷涼",reading:"れいりょう",meaning:"sejuk dingin (iklim)",priority:"🔥"},
        {word:"涼感",reading:"りょうかん",meaning:"sensasi kesejukan",priority:"⭐"},
        {word:"涼しげ",reading:"すずしげ",meaning:"terlihat sejuk",priority:"⭐"},
        {word:"夕涼み",reading:"ゆうすずみ",meaning:"menikmati kesejukan sore hari",priority:"⭐"},
        {word:"清涼飲料",reading:"せいりょういんりょう",meaning:"minuman segar/soft drink",priority:"🔥"},
      ],
      family:"清涼・冷涼 → nuansa 'sejuk'. 涼風・夕涼み → menikmati kesejukan. 清涼飲料 → produk yang diasosiasikan dengan kesegaran.",
      onyomi_pattern:"リョウ: 清涼(りょう)、涼風(りょう)。 Kunyomi すず lebih dominan.",
      quiz:[
        {type:"baca",question:"清涼",answer:"せいりょう",hint:"segar dan bersih"},
        {type:"arti",question:"清涼飲料",answer:"minuman segar/soft drink",hint:"飲料=minuman"},
        {type:"kanji",question:"りょうふう (angin sepoi)",answer:"涼風",hint:"風=angin"},
        {type:"baca",question:"冷涼",answer:"れいりょう",hint:"sejuk dingin"},
        {type:"arti",question:"夕涼み",answer:"menikmati kesejukan sore",hint:"夕=sore"},
      ]
    },
    { kanji:"暖", meaning_core:["hangat","menghangatkan"], onyomi:"ダン", kunyomi:"あたた(かい)、あたた(まる)、あたた(める)",
      jukugo:[
        {word:"暖かい",reading:"あたたかい",meaning:"hangat (suhu/perasaan)",priority:"🔥"},
        {word:"暖房",reading:"だんぼう",meaning:"pemanas ruangan",priority:"🔥"},
        {word:"温暖",reading:"おんだん",meaning:"hangat (iklim)",priority:"🔥"},
        {word:"暖流",reading:"だんりゅう",meaning:"arus laut hangat",priority:"🔥"},
        {word:"地球温暖化",reading:"ちきゅうおんだんか",meaning:"pemanasan global",priority:"🔥"},
        {word:"暖冬",reading:"だんとう",meaning:"musim dingin yang hangat",priority:"🔥"},
        {word:"暖気",reading:"だんき",meaning:"udara hangat",priority:"⭐"},
        {word:"暖色",reading:"だんしょく",meaning:"warna hangat (merah, kuning, oranye)",priority:"🔥"},
        {word:"温暖前線",reading:"おんだんぜんせん",meaning:"front hangat (meteorologi)",priority:"⭐"},
      ],
      family:"暖房・暖気 → sesuatu yang 'menghangatkan'. 温暖・暖流・暖冬 → kondisi iklim 'hangat'. 暖色 → warna yang memberi kesan hangat.",
      onyomi_pattern:"ダン: 暖房(だん)、温暖(だん)、暖流(だん)。 Kunyomi あたたかい untuk kata sifat.",
      quiz:[
        {type:"baca",question:"暖房",answer:"だんぼう",hint:"pemanas ruangan"},
        {type:"arti",question:"地球温暖化",answer:"pemanasan global",hint:"地球=bumi、化=menjadi"},
        {type:"kanji",question:"おんだん (iklim hangat)",answer:"温暖",hint:"温=hangat (温度)"},
        {type:"baca",question:"暖色",answer:"だんしょく",hint:"warna hangat"},
        {type:"arti",question:"暖流",answer:"arus laut hangat",hint:"流=arus/mengalir"},
      ]
    },
    { kanji:"層", meaning_core:["lapisan","strata","kelas sosial"], onyomi:"ソウ", kunyomi:"-",
      jukugo:[
        {word:"階層",reading:"かいそう",meaning:"lapisan sosial, strata",priority:"🔥"},
        {word:"地層",reading:"ちそう",meaning:"lapisan tanah, formasi geologis",priority:"🔥"},
        {word:"大気層",reading:"たいきそう",meaning:"lapisan atmosfer",priority:"🔥"},
        {word:"年齢層",reading:"ねんれいそう",meaning:"kelompok usia",priority:"🔥"},
        {word:"雲層",reading:"うんそう",meaning:"lapisan awan",priority:"⭐"},
        {word:"成層圏",reading:"せいそうけん",meaning:"stratosfer",priority:"🔥"},
        {word:"表層",reading:"ひょうそう",meaning:"lapisan permukaan",priority:"🔥"},
        {word:"深層",reading:"しんそう",meaning:"lapisan dalam",priority:"🔥"},
        {word:"底層",reading:"ていそう",meaning:"lapisan bawah/terbawah",priority:"⭐"},
        {word:"上層",reading:"じょうそう",meaning:"lapisan atas, kelas atas",priority:"🔥"},
        {word:"下層",reading:"かそう",meaning:"lapisan bawah, kelas bawah",priority:"🔥"},
      ],
      family:"地層・大気層・雲層 → lapisan fisik alam. 階層・年齢層・上層・下層 → lapisan sosial/kategori manusia. 表層・深層・底層 → posisi lapisan (atas/dalam/bawah).",
      onyomi_pattern:"ソウ: 階層(そう)、地層(そう)、成層圏(そう)。 ~100% sebagai ソウ.",
      quiz:[
        {type:"baca",question:"地層",answer:"ちそう",hint:"lapisan tanah/geologi"},
        {type:"arti",question:"成層圏",answer:"stratosfer",hint:"圏=lingkup/zona"},
        {type:"kanji",question:"かいそう (strata sosial)",answer:"階層",hint:"階=lantai/tingkat"},
        {type:"baca",question:"深層",answer:"しんそう",hint:"lapisan dalam"},
        {type:"arti",question:"年齢層",answer:"kelompok usia",hint:"年齢=usia"},
      ]
    },
    { kanji:"階", meaning_core:["lantai gedung","tangga","tahap","tingkatan"], onyomi:"カイ", kunyomi:"-",
      jukugo:[
        {word:"階段",reading:"かいだん",meaning:"tangga",priority:"🔥"},
        {word:"階層",reading:"かいそう",meaning:"lapisan sosial, strata",priority:"🔥"},
        {word:"三階",reading:"さんかい",meaning:"lantai tiga",priority:"🔥"},
        {word:"地下階",reading:"ちかかい",meaning:"lantai bawah tanah",priority:"🔥"},
        {word:"段階",reading:"だんかい",meaning:"tahap, fase",priority:"🔥"},
        {word:"音階",reading:"おんかい",meaning:"tangga nada, skala musik",priority:"🔥"},
        {word:"位階",reading:"いかい",meaning:"tingkat/pangkat (sistem peringkat)",priority:"⭐"},
        {word:"一階",reading:"いっかい",meaning:"lantai satu",priority:"🔥"},
      ],
      family:"階段・音階 → 'tangga/skala' yang berjenjang. 段階 → 'tahap/fase'. 三階・一階・地下階 → nomor lantai bangunan.",
      onyomi_pattern:"カイ: 階段(かい)、段階(かい)、音階(かい)。 ~100% sebagai カイ.",
      quiz:[
        {type:"baca",question:"段階",answer:"だんかい",hint:"tahap/fase"},
        {type:"arti",question:"音階",answer:"tangga nada, skala musik",hint:"音=suara/nada"},
        {type:"kanji",question:"かいだん (tangga)",answer:"階段",hint:"段=anak tangga"},
        {type:"baca",question:"地下階",answer:"ちかかい",hint:"lantai bawah tanah"},
        {type:"arti",question:"階層",answer:"lapisan sosial, strata",hint:"層=lapisan"},
      ]
    },
    { kanji:"蚕", meaning_core:["ulat sutera","industri sutera"], onyomi:"サン", kunyomi:"かいこ",
      jukugo:[
        {word:"蚕",reading:"かいこ",meaning:"ulat sutera",priority:"🔥"},
        {word:"養蚕",reading:"ようさん",meaning:"budidaya ulat sutera",priority:"🔥"},
        {word:"蚕業",reading:"さんぎょう",meaning:"industri ulat sutera",priority:"🔥"},
        {word:"蚕食",reading:"さんしょく",meaning:"menggerogoti secara bertahap",priority:"🔥"},
        {word:"蚕糸",reading:"さんし",meaning:"sutera mentah dari ulat",priority:"⭐"},
        {word:"春蚕",reading:"しゅんさん",meaning:"ulat sutera musim semi",priority:"○"},
      ],
      family:"養蚕・蚕業 → industri ulat sutera. 蚕食 → idiom 'menggerogoti seperti ulat'.",
      onyomi_pattern:"サン: 養蚕(さん)、蚕食(さん)。 Kunyomi かいこ saat berdiri sendiri.",
      quiz:[
        {type:"baca",question:"養蚕",answer:"ようさん",hint:"budidaya ulat sutera"},
        {type:"arti",question:"蚕食",answer:"menggerogoti secara bertahap",hint:"食=makan"},
        {type:"kanji",question:"ようさん (budidaya ulat)",answer:"養蚕",hint:"養=memelihara"},
        {type:"baca",question:"蚕業",answer:"さんぎょう",hint:"industri ulat sutera"},
        {type:"arti",question:"蚕糸",answer:"sutera mentah dari ulat",hint:"糸=benang"},
      ]
    },
    { kanji:"飼", meaning_core:["memelihara hewan","memberi makan (hewan)"], onyomi:"シ", kunyomi:"か(う)",
      jukugo:[
        {word:"飼う",reading:"かう",meaning:"memelihara (hewan peliharaan)",priority:"🔥"},
        {word:"飼育",reading:"しいく",meaning:"pemeliharaan/pengembangbiakan hewan",priority:"🔥"},
        {word:"飼料",reading:"しりょう",meaning:"pakan ternak, makanan hewan",priority:"🔥"},
        {word:"飼い主",reading:"かいぬし",meaning:"pemilik hewan peliharaan",priority:"🔥"},
        {word:"飼い犬",reading:"かいいぬ",meaning:"anjing peliharaan",priority:"🔥"},
        {word:"飼育員",reading:"しいくいん",meaning:"penjaga kebun binatang, animal keeper",priority:"🔥"},
        {word:"家畜飼育",reading:"かちくしいく",meaning:"peternakan",priority:"⭐"},
      ],
      family:"飼育・飼料 → pemeliharaan dan kebutuhan hewan. 飼い主・飼い犬 → pemilik dan hewan peliharaan.",
      onyomi_pattern:"シ: 飼育(し)、飼料(し)。 Kunyomi か(う) untuk aksi sehari-hari.",
      quiz:[
        {type:"baca",question:"飼育",answer:"しいく",hint:"pemeliharaan hewan"},
        {type:"arti",question:"飼料",answer:"pakan ternak, makanan hewan",hint:"料=bahan/makanan"},
        {type:"kanji",question:"しいくいん (animal keeper)",answer:"飼育員",hint:"員=anggota/pegawai"},
        {type:"baca",question:"飼い主",answer:"かいぬし",hint:"pemilik hewan peliharaan"},
        {type:"arti",question:"飼い犬",answer:"anjing peliharaan",hint:"犬=anjing"},
      ]
    },
    { kanji:"製", meaning_core:["pembuatan","manufaktur","buatan"], onyomi:"セイ", kunyomi:"-",
      jukugo:[
        {word:"製造",reading:"せいぞう",meaning:"manufaktur, pembuatan",priority:"🔥"},
        {word:"製品",reading:"せいひん",meaning:"produk",priority:"🔥"},
        {word:"製作",reading:"せいさく",meaning:"produksi (film/seni)",priority:"🔥"},
        {word:"製薬",reading:"せいやく",meaning:"industri farmasi",priority:"🔥"},
        {word:"製鉄",reading:"せいてつ",meaning:"pembuatan baja",priority:"🔥"},
        {word:"日本製",reading:"にほんせい",meaning:"buatan Jepang",priority:"🔥"},
        {word:"国産品",reading:"こくさんひん",meaning:"produk dalam negeri",priority:"🔥"},
        {word:"製図",reading:"せいず",meaning:"menggambar teknis, drafting",priority:"⭐"},
        {word:"既製品",reading:"きせいひん",meaning:"barang jadi/siap pakai",priority:"🔥"},
        {word:"手製",reading:"てせい",meaning:"buatan tangan",priority:"🔥"},
        {word:"木製",reading:"もくせい",meaning:"terbuat dari kayu",priority:"🔥"},
      ],
      family:"製造・製作・製品 → proses dan hasil manufaktur. 日本製・手製・木製 → asal/bahan pembuatan. 製薬・製鉄 → industri spesifik.",
      onyomi_pattern:"セイ: 製造(せい)、製品(せい)、日本製(せい)。 ~100% sebagai セイ.",
      quiz:[
        {type:"baca",question:"製品",answer:"せいひん",hint:"produk"},
        {type:"arti",question:"既製品",answer:"barang jadi/siap pakai",hint:"既=sudah/terlanjur"},
        {type:"kanji",question:"にほんせい (buatan Jepang)",answer:"日本製",hint:"日本=Jepang"},
        {type:"baca",question:"製薬",answer:"せいやく",hint:"industri farmasi"},
        {type:"arti",question:"手製",answer:"buatan tangan",hint:"手=tangan"},
      ]
    },
    { kanji:"辺", meaning_core:["sekitar","tepi","daerah","lingkungan"], onyomi:"ヘン", kunyomi:"あた(り)、べ",
      jukugo:[
        {word:"辺り",reading:"あたり",meaning:"sekitar, daerah",priority:"🔥"},
        {word:"周辺",reading:"しゅうへん",meaning:"sekitar, lingkungan, pinggiran",priority:"🔥"},
        {word:"近辺",reading:"きんぺん",meaning:"sekitar sini, daerah dekat",priority:"🔥"},
        {word:"身辺",reading:"しんぺん",meaning:"sekitar diri, urusan pribadi",priority:"🔥"},
        {word:"辺境",reading:"へんきょう",meaning:"daerah perbatasan, frontier",priority:"🔥"},
        {word:"海辺",reading:"うみべ",meaning:"tepi laut, pantai",priority:"🔥"},
        {word:"川辺",reading:"かわべ",meaning:"tepi sungai",priority:"🔥"},
        {word:"路辺",reading:"ろへん",meaning:"tepi jalan",priority:"⭐"},
        {word:"この辺",reading:"このへん",meaning:"sekitar sini, daerah ini",priority:"🔥"},
      ],
      family:"周辺・近辺・辺り → konsep 'sekitar/lingkungan'. 海辺・川辺 → 'tepi' suatu wilayah alam. 辺境 → 'daerah perbatasan/terpencil'.",
      onyomi_pattern:"ヘン: 周辺(へん)、辺境(へん)、近辺(へん)。 Kunyomi あたり/べ dalam percakapan.",
      quiz:[
        {type:"baca",question:"周辺",answer:"しゅうへん",hint:"lingkungan/sekitar"},
        {type:"arti",question:"辺境",answer:"daerah perbatasan, frontier",hint:"境=batas/perbatasan"},
        {type:"kanji",question:"うみべ (tepi laut)",answer:"海辺",hint:"海=laut"},
        {type:"baca",question:"身辺",answer:"しんぺん",hint:"urusan pribadi"},
        {type:"arti",question:"近辺",answer:"sekitar sini, daerah dekat",hint:"近=dekat"},
      ]
    },
    { kanji:"農", meaning_core:["pertanian","petani","agraris"], onyomi:"ノウ", kunyomi:"-",
      jukugo:[
        {word:"農業",reading:"のうぎょう",meaning:"pertanian",priority:"🔥"},
        {word:"農家",reading:"のうか",meaning:"rumah tangga petani, keluarga petani",priority:"🔥"},
        {word:"農村",reading:"のうそん",meaning:"desa pertanian",priority:"🔥"},
        {word:"農地",reading:"のうち",meaning:"lahan pertanian",priority:"🔥"},
        {word:"農薬",reading:"のうやく",meaning:"pestisida, agrokimia",priority:"🔥"},
        {word:"農産物",reading:"のうさんぶつ",meaning:"produk pertanian",priority:"🔥"},
        {word:"農協",reading:"のうきょう",meaning:"koperasi pertanian (JA)",priority:"🔥"},
        {word:"酪農",reading:"らくのう",meaning:"peternakan sapi perah",priority:"🔥"},
        {word:"農耕",reading:"のうこう",meaning:"bercocok tanam, pertanian tradisional",priority:"🔥"},
        {word:"稲作農業",reading:"いなさくのうぎょう",meaning:"pertanian padi",priority:"⭐"},
      ],
      family:"農業・農村・農地・農家 → aspek-aspek dunia pertanian. 農薬・農産物・農協 → produk dan organisasi pertanian.",
      onyomi_pattern:"ノウ: 農業(のう)、農村(のう)、酪農(のう)。 ~100% sebagai ノウ.",
      quiz:[
        {type:"baca",question:"農業",answer:"のうぎょう",hint:"pertanian"},
        {type:"arti",question:"農薬",answer:"pestisida, agrokimia",hint:"薬=obat/kimia"},
        {type:"kanji",question:"らくのう (peternakan sapi perah)",answer:"酪農",hint:"酪=susu/produk susu"},
        {type:"baca",question:"農産物",answer:"のうさんぶつ",hint:"produk pertanian"},
        {type:"arti",question:"農協",answer:"koperasi pertanian",hint:"協=kerjasama/koperasi"},
      ]
    },
    { kanji:"内", meaning_core:["dalam","bagian dalam","keluarga"], onyomi:"ナイ、ダイ", kunyomi:"うち",
      jukugo:[
        {word:"国内",reading:"こくない",meaning:"dalam negeri, domestik",priority:"🔥"},
        {word:"内容",reading:"ないよう",meaning:"isi, konten",priority:"🔥"},
        {word:"内部",reading:"ないぶ",meaning:"bagian dalam, interior",priority:"🔥"},
        {word:"以内",reading:"いない",meaning:"dalam batas, tidak melebihi",priority:"🔥"},
        {word:"室内",reading:"しつない",meaning:"dalam ruangan, interior",priority:"🔥"},
        {word:"内科",reading:"ないか",meaning:"penyakit dalam (klinik)",priority:"🔥"},
        {word:"内閣",reading:"ないかく",meaning:"kabinet pemerintahan",priority:"🔥"},
        {word:"海内",reading:"かいない",meaning:"dalam negara/bangsa (sastra)",priority:"○"},
        {word:"内外",reading:"ないがい",meaning:"dalam dan luar negeri",priority:"🔥"},
        {word:"境内",reading:"けいだい",meaning:"lingkungan kuil/shrine",priority:"🔥"},
        {word:"内訳",reading:"うちわけ",meaning:"rincian, breakdown",priority:"🔥"},
        {word:"内緒",reading:"ないしょ",meaning:"rahasia, diam-diam",priority:"🔥"},
      ],
      family:"国内・室内・内部 → 'dalam/interior'. 内容・内訳 → isi/rincian dari sesuatu. 内閣・内科 → lembaga/divisi 'di dalam'.",
      onyomi_pattern:"ナイ: 国内(ない)、内容(ない)、以内(ない)。 ダイ: 境内(だい→けい)。 Dominan ナイ.",
      quiz:[
        {type:"baca",question:"内容",answer:"ないよう",hint:"isi/konten"},
        {type:"arti",question:"内閣",answer:"kabinet pemerintahan",hint:"閣=bangunan tinggi/kabinet"},
        {type:"kanji",question:"ないしょ (rahasia)",answer:"内緒",hint:"緒=tali/awal"},
        {type:"baca",question:"境内",answer:"けいだい",hint:"lingkungan kuil/shrine"},
        {type:"arti",question:"内訳",answer:"rincian, breakdown",hint:"訳=penjelasan/terjemahan"},
      ]
    },
    { kanji:"条", meaning_core:["pasal","aturan","kondisi","strip"], onyomi:"ジョウ", kunyomi:"-",
      jukugo:[
        {word:"条件",reading:"じょうけん",meaning:"kondisi, syarat",priority:"🔥"},
        {word:"条例",reading:"じょうれい",meaning:"peraturan daerah, ordinansi",priority:"🔥"},
        {word:"条約",reading:"じょうやく",meaning:"perjanjian internasional",priority:"🔥"},
        {word:"信条",reading:"しんじょう",meaning:"kepercayaan, prinsip",priority:"🔥"},
        {word:"第一条",reading:"だいいちじょう",meaning:"pasal pertama",priority:"🔥"},
        {word:"条文",reading:"じょうぶん",meaning:"teks pasal hukum",priority:"🔥"},
        {word:"箇条書き",reading:"かじょうがき",meaning:"daftar poin (bullet points)",priority:"🔥"},
        {word:"別条",reading:"べつじょう",meaning:"hal lain; tidak ada yang berbeda (慣用)",priority:"⭐"},
        {word:"無条件",reading:"むじょうけん",meaning:"tanpa syarat",priority:"🔥"},
      ],
      family:"条件・無条件 → tentang 'syarat'. 条例・条約・条文 → dokumen hukum/peraturan. 信条 → 'pasal/prinsip' dalam kepercayaan.",
      onyomi_pattern:"ジョウ: 条件(じょう)、条約(じょう)、条例(じょう)。 ~100% sebagai ジョウ.",
      quiz:[
        {type:"baca",question:"条件",answer:"じょうけん",hint:"syarat/kondisi"},
        {type:"arti",question:"条約",answer:"perjanjian internasional",hint:"約=janji/perjanjian"},
        {type:"kanji",question:"むじょうけん (tanpa syarat)",answer:"無条件",hint:"無=tidak ada"},
        {type:"baca",question:"条例",answer:"じょうれい",hint:"peraturan daerah"},
        {type:"arti",question:"箇条書き",answer:"daftar poin (bullet points)",hint:"書き=menulis"},
      ]
    },
    { kanji:"貢", meaning_core:["kontribusi","membayar upeti","mempersembahkan"], onyomi:"コウ、ク", kunyomi:"みつ(ぐ)",
      jukugo:[
        {word:"貢献",reading:"こうけん",meaning:"kontribusi, sumbangsih",priority:"🔥"},
        {word:"年貢",reading:"ねんぐ",meaning:"pajak tahunan, upeti tahunan",priority:"🔥"},
        {word:"貢ぐ",reading:"みつぐ",meaning:"memberikan upeti, membiayai seseorang",priority:"🔥"},
        {word:"朝貢",reading:"ちょうこう",meaning:"persembahan/upeti kepada raja/kaisar",priority:"⭐"},
        {word:"貢物",reading:"みつぎもの",meaning:"persembahan, hadiah upeti",priority:"⭐"},
      ],
      family:"貢献 adalah jukugo paling penting. 年貢・朝貢・貢物 → konteks 'upeti' historis.",
      onyomi_pattern:"コウ: 貢献(こう)。 ク: 年貢(く). Dominan コウ dalam penggunaan modern.",
      quiz:[
        {type:"baca",question:"貢献",answer:"こうけん",hint:"kontribusi"},
        {type:"arti",question:"年貢",answer:"pajak tahunan, upeti",hint:"年=tahun"},
        {type:"kanji",question:"こうけん (sumbangsih)",answer:"貢献",hint:"献=persembahan"},
        {type:"baca",question:"朝貢",answer:"ちょうこう",hint:"upeti ke raja"},
        {type:"arti",question:"貢物",answer:"persembahan, hadiah upeti",hint:"物=barang/benda"},
      ]
    },
    { kanji:"期", meaning_core:["periode","waktu yang ditentukan","mengharapkan"], onyomi:"キ、ゴ", kunyomi:"ご",
      jukugo:[
        {word:"期間",reading:"きかん",meaning:"periode, jangka waktu",priority:"🔥"},
        {word:"期待",reading:"きたい",meaning:"harapan, antisipasi",priority:"🔥"},
        {word:"学期",reading:"がっき",meaning:"semester, triwulan akademik",priority:"🔥"},
        {word:"時期",reading:"じき",meaning:"waktu, musim",priority:"🔥"},
        {word:"定期",reading:"ていき",meaning:"berkala, tetap (jadwal)",priority:"🔥"},
        {word:"期末",reading:"きまつ",meaning:"akhir periode/semester",priority:"🔥"},
        {word:"長期",reading:"ちょうき",meaning:"jangka panjang",priority:"🔥"},
        {word:"短期",reading:"たんき",meaning:"jangka pendek",priority:"🔥"},
        {word:"初期",reading:"しょき",meaning:"periode awal",priority:"🔥"},
        {word:"末期",reading:"まっき",meaning:"tahap akhir (penyakit dll)",priority:"🔥"},
        {word:"期限",reading:"きげん",meaning:"batas waktu, deadline",priority:"🔥"},
        {word:"有効期限",reading:"ゆうこうきげん",meaning:"tanggal kedaluwarsa",priority:"🔥"},
      ],
      family:"長期・短期・初期・末期 → mengukur 'durasi waktu'. 期間・時期・定期 → kondisi waktu tertentu. 期待・期末 → konteks 'harapan/akhir dari suatu periode'.",
      onyomi_pattern:"キ: 期間(き)、期待(き)、学期(き)。 ゴ: (jarang, dalam nama). Dominan キ.",
      quiz:[
        {type:"baca",question:"期待",answer:"きたい",hint:"harapan/antisipasi"},
        {type:"arti",question:"有効期限",answer:"tanggal kedaluwarsa",hint:"有効=berlaku"},
        {type:"kanji",question:"ちょうき (jangka panjang)",answer:"長期",hint:"長=panjang"},
        {type:"baca",question:"定期",answer:"ていき",hint:"berkala/tetap"},
        {type:"arti",question:"末期",answer:"tahap akhir (penyakit dll)",hint:"末=ujung/akhir"},
      ]
    },
    { kanji:"城", meaning_core:["kastil","benteng","kota berbenteng"], onyomi:"ジョウ", kunyomi:"しろ",
      jukugo:[
        {word:"城",reading:"しろ",meaning:"kastil",priority:"🔥"},
        {word:"城下",reading:"じょうか",meaning:"kota di bawah kastil",priority:"🔥"},
        {word:"城下町",reading:"じょうかまち",meaning:"kota yang tumbuh di sekitar kastil",priority:"🔥"},
        {word:"落城",reading:"らくじょう",meaning:"jatuhnya kastil (ke musuh)",priority:"🔥"},
        {word:"城主",reading:"じょうしゅ",meaning:"pemilik/penguasa kastil",priority:"🔥"},
        {word:"入城",reading:"にゅうじょう",meaning:"memasuki kastil",priority:"⭐"},
        {word:"山城",reading:"やましろ",meaning:"kastil di gunung",priority:"⭐"},
        {word:"平城",reading:"ひらじろ",meaning:"kastil di dataran",priority:"○"},
        {word:"大阪城",reading:"おおさかじょう",meaning:"Kastil Osaka",priority:"🔥"},
      ],
      family:"城・城下町・城主 → aspek kehidupan feodalisme kastil. 落城・入城 → aksi terhadap kastil.",
      onyomi_pattern:"ジョウ: 城下(じょう)、落城(じょう)。 Kunyomi しろ saat berdiri sendiri.",
      quiz:[
        {type:"baca",question:"落城",answer:"らくじょう",hint:"kastil jatuh ke musuh"},
        {type:"arti",question:"城下町",answer:"kota yang tumbuh di sekitar kastil",hint:"町=kota kecil"},
        {type:"kanji",question:"じょうしゅ (penguasa kastil)",answer:"城主",hint:"主=pemimpin/tuan"},
        {type:"baca",question:"入城",answer:"にゅうじょう",hint:"memasuki kastil"},
        {type:"arti",question:"城下",answer:"kota di bawah kastil",hint:"下=bawah"},
      ]
    },
    { kanji:"掘", meaning_core:["menggali","menambang"], onyomi:"クツ", kunyomi:"ほ(る)",
      jukugo:[
        {word:"掘る",reading:"ほる",meaning:"menggali",priority:"🔥"},
        {word:"発掘",reading:"はっくつ",meaning:"ekskavasi, penggalian arkeologi; menemukan bakat",priority:"🔥"},
        {word:"採掘",reading:"さいくつ",meaning:"penambangan",priority:"🔥"},
        {word:"掘削",reading:"くっさく",meaning:"pengerukan, pengeboran",priority:"🔥"},
        {word:"掘り起こす",reading:"ほりおこす",meaning:"menggali ke atas, mengungkap",priority:"🔥"},
        {word:"穴掘り",reading:"あなほり",meaning:"penggali lubang",priority:"⭐"},
        {word:"掘り下げる",reading:"ほりさげる",meaning:"menggali lebih dalam, menganalisis lebih dalam",priority:"🔥"},
      ],
      family:"発掘・採掘・掘削 → berbagai jenis 'penggalian' (arkeologi, tambang, teknik). 掘り起こす・掘り下げる → menggali secara figuratif.",
      onyomi_pattern:"クツ: 発掘(くつ)、採掘(くつ)。 Kunyomi ほる untuk kata kerja sehari-hari.",
      quiz:[
        {type:"baca",question:"発掘",answer:"はっくつ",hint:"ekskavasi/menemukan"},
        {type:"arti",question:"採掘",answer:"penambangan",hint:"採=mengambil/memanen"},
        {type:"kanji",question:"くっさく (pengeboran)",answer:"掘削",hint:"削=mengikis/mengebor"},
        {type:"baca",question:"掘り下げる",answer:"ほりさげる",hint:"menganalisis lebih dalam"},
        {type:"arti",question:"掘り起こす",answer:"menggali ke atas, mengungkap",hint:"起こす=membangkitkan"},
      ]
    },
    { kanji:"豊", meaning_core:["berlimpah","makmur","kaya","subur"], onyomi:"ホウ", kunyomi:"ゆた(か)",
      jukugo:[
        {word:"豊か",reading:"ゆたか",meaning:"berlimpah, makmur, kaya",priority:"🔥"},
        {word:"豊富",reading:"ほうふ",meaning:"berlimpah, banyak",priority:"🔥"},
        {word:"豊作",reading:"ほうさく",meaning:"panen berlimpah",priority:"🔥"},
        {word:"豊年",reading:"ほうねん",meaning:"tahun panen berlimpah",priority:"🔥"},
        {word:"豊穣",reading:"ほうじょう",meaning:"kemakmuran, kesuburan",priority:"🔥"},
        {word:"豊満",reading:"ほうまん",meaning:"berlimpah, tubuh yang berisi",priority:"⭐"},
        {word:"豊臣",reading:"とよとみ",meaning:"klan Toyotomi (historis)",priority:"⭐"},
        {word:"食料豊富",reading:"しょくりょうほうふ",meaning:"sumber pangan yang berlimpah",priority:"⭐"},
      ],
      family:"豊か・豊富・豊満 → berbagai nuansa 'kelimpahan'. 豊作・豊年・豊穣 → kelimpahan dalam konteks pertanian.",
      onyomi_pattern:"ホウ: 豊富(ほう)、豊作(ほう)、豊穣(ほう)。 Kunyomi ゆたか untuk kata sifat.",
      quiz:[
        {type:"baca",question:"豊富",answer:"ほうふ",hint:"berlimpah/banyak"},
        {type:"arti",question:"豊作",answer:"panen berlimpah",hint:"作=hasil/membuat"},
        {type:"kanji",question:"ほうじょう (kesuburan)",answer:"豊穣",hint:"穣=berlimpah/kaya"},
        {type:"baca",question:"豊年",answer:"ほうねん",hint:"tahun panen berlimpah"},
        {type:"arti",question:"豊か",answer:"berlimpah, makmur, kaya",hint:"kata sifat langsung"},
      ]
    },
    { kanji:"権", meaning_core:["hak","kekuasaan","wewenang"], onyomi:"ケン", kunyomi:"-",
      jukugo:[
        {word:"権利",reading:"けんり",meaning:"hak, hak asasi",priority:"🔥"},
        {word:"人権",reading:"じんけん",meaning:"hak asasi manusia",priority:"🔥"},
        {word:"権力",reading:"けんりょく",meaning:"kekuasaan, power",priority:"🔥"},
        {word:"政権",reading:"せいけん",meaning:"kekuasaan politik, rezim",priority:"🔥"},
        {word:"主権",reading:"しゅけん",meaning:"kedaulatan",priority:"🔥"},
        {word:"著作権",reading:"ちょさくけん",meaning:"hak cipta",priority:"🔥"},
        {word:"特許権",reading:"とっきょけん",meaning:"hak paten",priority:"🔥"},
        {word:"選挙権",reading:"せんきょけん",meaning:"hak pilih",priority:"🔥"},
        {word:"権威",reading:"けんい",meaning:"wewenang, otoritas",priority:"🔥"},
        {word:"棄権",reading:"きけん",meaning:"abstain, melepas hak",priority:"🔥"},
        {word:"越権",reading:"えっけん",meaning:"melampaui wewenang",priority:"⭐"},
        {word:"権限",reading:"けんげん",meaning:"batas kewenangan",priority:"🔥"},
      ],
      family:"権利・人権・選挙権・著作権 → jenis-jenis 'hak'. 権力・政権・主権 → bentuk-bentuk 'kekuasaan'. 権威・権限 → 'otoritas/kewenangan'.",
      onyomi_pattern:"ケン: 権利(けん)、人権(けん)、政権(けん)。 ~100% sebagai ケン.",
      quiz:[
        {type:"baca",question:"人権",answer:"じんけん",hint:"HAM"},
        {type:"arti",question:"著作権",answer:"hak cipta",hint:"著作=karya tulis"},
        {type:"kanji",question:"けんりょく (kekuasaan)",answer:"権力",hint:"力=kekuatan"},
        {type:"baca",question:"棄権",answer:"きけん",hint:"abstain"},
        {type:"arti",question:"主権",answer:"kedaulatan",hint:"主=utama/tuan"},
      ]
    },
    { kanji:"植", meaning_core:["menanam","tanaman","koloni"], onyomi:"ショク", kunyomi:"う(える)、う(わる)",
      jukugo:[
        {word:"植物",reading:"しょくぶつ",meaning:"tanaman, flora",priority:"🔥"},
        {word:"植える",reading:"うえる",meaning:"menanam",priority:"🔥"},
        {word:"植物園",reading:"しょくぶつえん",meaning:"kebun raya",priority:"🔥"},
        {word:"植林",reading:"しょくりん",meaning:"penanaman hutan",priority:"🔥"},
        {word:"植民地",reading:"しょくみんち",meaning:"koloni, daerah jajahan",priority:"🔥"},
        {word:"植樹",reading:"しょくじゅ",meaning:"penanaman pohon",priority:"🔥"},
        {word:"移植",reading:"いしょく",meaning:"transplantasi (organ/tanaman)",priority:"🔥"},
        {word:"定植",reading:"ていしょく",meaning:"penanaman tetap/final",priority:"⭐"},
        {word:"植生",reading:"しょくせい",meaning:"vegetasi suatu daerah",priority:"🔥"},
      ],
      family:"植物・植物園・植生 → berkaitan dengan 'tanaman'. 植林・植樹 → 'menanam pohon'. 植民地 → koloni (secara historis 'menanam' orang di suatu wilayah).",
      onyomi_pattern:"ショク: 植物(しょく)、植林(しょく)、植民地(しょく)。 ~100% sebagai ショク.",
      quiz:[
        {type:"baca",question:"植物",answer:"しょくぶつ",hint:"tanaman/flora"},
        {type:"arti",question:"植民地",answer:"koloni, daerah jajahan",hint:"民=rakyat"},
        {type:"kanji",question:"いしょく (transplantasi)",answer:"移植",hint:"移=memindahkan"},
        {type:"baca",question:"植林",answer:"しょくりん",hint:"penanaman hutan"},
        {type:"arti",question:"植生",answer:"vegetasi suatu daerah",hint:"生=hidup/tumbuh"},
      ]
    },
  ]
};
